### ISSUE TITLE
Inverse of equivalence not displaying

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1000]
Since 8.9 is out the code in #975 should work. However:
```
Require Import Basics.

Definition foo {A B} (e : A <~> B) (b : B) : A.
Proof.
  pose (a := e^-1 b).
```
Gives the following hypothesis:
```
a := _^-1 b : A
```

How can this be fixed?

**Comment by JasonGross** [comment]
Reported as https://github.com/coq/coq/issues/9703

**Comment by JasonGross** [comment]
You can fix this with `Set Printing Primitive Projection Parameters.`  Maybe we should set this by default?
