### ISSUE TITLE
trunc_index addition is completely wrong

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1002]
I am currently playing around with spheres. They are (weirdly) defined with `trunc_index`. When playing around with `1 -2+ 1` I get a result of `4`. Clearly this is completely absurd.

Also what is the best "nat" to use in the library? Are we stuck with Coq's?

**Comment by mikeshulman** [comment]
I guess the notation `-2+` is misleading, it should be `+2+`.  `trunc_index_add` is addition of the corresponding 0-based "h-levels", i.e. add two to both arguments to make them 0-based, then add them, then subtract two from the result to get back to a (-2)-based `trunc_index`.

is there something wrong with Coq's `nat`?  There are some theorems about it in `Spaces/Nat`.

**Comment by Alizter** [comment]
There is nothing wrong with Coq's nat, I just don't want to use coq standard libraries if I don't need to. Thanks for pointing me to spaces, I was rummaging around in mathclasses looking for it.

**Comment by Alizter** [comment]
I'm still a bit stuck however. It seems to me things like `<=` are defined as DProps. And if I want to do induction on a natural number, how can I get it to start from say 4 if I have `4 <= n` floating around.

**Comment by mikeshulman** [comment]
Is there a problem with DProps?  They can be coerced to Props; the extra information is just that you can use `dec` on them.

Isn't induction starting with a base other than zero a standard exercise in an undergraduate logic course?  Just induct on n-4 which starts from 0.

**Comment by Alizter** [comment]
Regarding DProps: Cool, I will investigate.

Regarding induction: Yes apparently I am too tired to notice this. Thanks anyway.
