### ISSUE TITLE
trunc_index addition in Freudenthal.v

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1005]
So trunc_index addition, now known as `n +2+ m` is used all over Freudenthal. I am fairly certain this is not correct. I have started a branch trying to go through the proof anyway, trying to clean it up a bit.

What would have to be written here instead?

Wouldn't it be convenient to have a normal addition for trunc_index as long as both arguments are nonnegative?

**Comment by mikeshulman** [comment]
Why do you think it's wrong?

**Comment by Alizter** [comment]
Never mind I have managed to understand it. The trunc indexes starting from -1 is really confusing me when following with the book.

**Comment by mikeshulman** [comment]
Can you explain that?  The numbers are the same as they are in the book, and I would have said they start from -2 instead of -1.

**Comment by mikeshulman** [comment]
Also, FWIW I think it's probably not the best use of time to do any work on the Freudenthal proof.  The "right" thing to do is to prove the ABFJ generalized Blakers-Massey theorem and derive Freudenthal from that.  (-:

**Comment by Alizter** [comment]
In the book 2n is written, which in my mind is n+n, when I see `n +2+ n` I got confused. What I hadn’t noticed is that `n >= -1`, rather than n>=0 in the book. It’s perfectly valid but I naively thought it was the same n.

**Comment by Alizter** [comment]
I am currently trying to get my EM spaces to work. For that I needed some Freudenthal, so I had a quick look and got a bit confused.

Writing the correct induction principle for EM spaces isn’t easy, proving the 3x3 Lemma isnt so easy. Whilst I ponder these I am trying to eat some low hanging fruit.
