### ISSUE TITLE
Anomaly in hoqtop on inversion tactic

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#101]
The following code run through hoqtop/hoqc gives an anomaly.  (This is where my global Coq is the trunk of HoTT/coq; I'm working on compiling the stable branch now.)  (I realize that this is something that shouldn't be done with "fake higher inductive types", but I figured I'd report it, in case it was an unintended anomaly...)

```coq
Require Import Overture.

Inductive interval := zero | one.
Axiom seg : zero = one.
Goal False.
  pose proof seg as P.
  inversion P.
(* Toplevel input, characters 0-11:
Anomaly: in Coqlib: cannot find Coq.Init.Logic.eq:
Coqlib: cannot find Coq.Init.Logic.eq. Please report.
*)
```

**Comment by andrejbauer** [comment]
This issue is now obsolete simply because it's grown too old.
