### ISSUE TITLE
behaviour for simpl on spheres

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1018]
So I have the following code:
```
Require Import Basics.
Require Import HIT.Suspension.
Require Import HIT.Spheres.

Goal Sphere 4.
Proof.
  simpl.
Admitted.

Lemma foo n : Susp (Sphere n) = Sphere n.+1.
Proof.
  simpl.
Admitted.
```
Now the first Goal gives desired behaviour, it turns `Sphere 4` into a string of suspensions. However the second one turns:
```
Susp (Sphere n) = Sphere n.+1
```
into
```
Susp (Sphere n) = match n with
                  | -2 => Empty
                  | _.+1 => Susp (Sphere n)
                  end
```
How can we get coq to only unfold the first case, but when the `n` isn't known, keep it written, or even simplify into `Sphere n.+1`?

**Comment by mikeshulman** [comment]
`Arguments Sphere n : simpl nomatch`

(By the way, your `foo` is false for `n=-2`).
