### ISSUE TITLE
Porting SSR tactics to HoTT

### ISSUE THREAD

**Issue by andreaslyn** [HoTT/HoTT#1037]
In branch [hott-ssr](https://github.com/andreaslyn/coq/tree/hott-ssr) I have started a port of SSReflect to HoTT. The SSR files at https://github.com/andreaslyn/HoTT/tree/ssr/theories/ssr in the [ssr](https://github.com/andreaslyn/HoTT/tree/ssr) branch of HoTT are all compiling with some admits in [ssrbool.v](https://github.com/andreaslyn/HoTT/blob/ssr/theories/ssr/ssrbool.v) and [ssrfun.v](https://github.com/andreaslyn/HoTT/blob/ssr/theories/ssr/ssrfun.v).

One problem that I have encountered is already reported in issue https://github.com/coq/coq/issues/9336.

There is another problem with the `congr` tactic (**edit: this problem has been resolved**):
```
Lemma congr_test A (x y : A) (f : A -> A) (p : x = y) : f x = f y.
Proof. congr (f _).
```
The above code gives a universe error, assuming HoTT branch [ssr](https://github.com/andreaslyn/HoTT/tree/ssr) together with Coq branch [hott-ssr](https://github.com/andreaslyn/coq/tree/hott-ssr).

There is also a problem (**edit: this problem is fixed now**):
```
Goal forall A (x y : A), Some x = Some y -> x = y.
Proof. move=> A x y. move=> [].
```
The last `move` gives a "Failed to decompose equality" error.

In the following code, the `case` gives a universe error (**edit: this problem has been resolved**):
```
Goal forall (b:Bool), Unit.
Proof. move=> b. case def_b: b.
```

It takes a long time for me to debug these things, since I am just getting used to the Coq sources. @mattam82 and @CohenCyril do you have suggestions on how to fix some of these issues?

**Comment by mattam82** [comment]
The intro pattern bug is probably because it’s using the wrong injectivity lemma or not expecting an equality in type. I don’t know ssrs code enough to infer what could be wrong. And in the last example what is `case def_b: b.` supposed to do?

**Comment by andreaslyn** [comment]
> The intro pattern bug is probably because it’s using the wrong injectivity lemma or not expecting an equality in type.

Thanks. I will take another look at this one.



> I don’t know ssrs code enough to infer what could be wrong. And in the last example what is `case def_b: b.` supposed to do?

The `case def_b: b` corresponds to something like: `destruct b eqn:def_b`.

**Comment by mattam82** [comment]
> > I don’t know ssrs code enough to infer what could be wrong. And in the last example what is `case def_b: b.` supposed to do?
> 
> The `case def_b: b` corresponds to something like: `destruct b eqn:def_b`.

Makes sense then, it's probably using the wrong equality / not instantiating it properly to generate the equation.

**Comment by andreaslyn** [comment]
> > The intro pattern bug is probably because it’s using the wrong injectivity lemma or not expecting an equality in type.
> 
> Thanks. I will take another look at this one.

This one is fixed now. The problem was that the `core.sigT.*` globals were not registered in HoTT.

**Comment by andreaslyn** [comment]
The issue with `congr` has been resolved.

**Comment by andreaslyn** [comment]
There are solutions to all the problems now. I am however not entirely sure about all of the code. I am particularly worried about the trick I am using to merge universe contexts at https://github.com/andreaslyn/coq/blob/8170bcdbd9b39761528b5e9f88ff709846b005cc/plugins/ssr/ssrelim.ml#L396 and https://github.com/andreaslyn/coq/blob/8170bcdbd9b39761528b5e9f88ff709846b005cc/plugins/ssr/ssrequality.ml#L627.

Does it look right?

**Comment by mattam82** [comment]
I don’t know for the first one, but the second should be unnecessary I think, e.g. doing
```
let (sigma, t) = interp_term gt gl in
...
```

Should be enough, as the returned sigma will be an extension of gl. Does that produce an error?
Maybe @gares can tell us more about how this should go.

**Comment by gares** [comment]
I agree it is not necessary, but it does not hurt either.

Thanks for working on ssr by the way!

Can you open a issue on the coq bug tracker for the last issue here (that seems to be still open I believe)?

**Comment by andreaslyn** [comment]
> I don’t know for the first one, but the second should be unnecessary I think, e.g. doing
> 
> ```
> let (sigma, t) = interp_term gt gl in
> ...
> ```

Using this, the following code gives the error `Some unresolved existential variables remain`.
```
Definition d (A:Type) := 0.
Lemma test : 0 = 0.
Proof. rewrite -/(d _). reflexivity. Qed.
```
The `d _` pattern creates an existential variable, which should probably not be in the context of the proof. Does that make sense?

**Comment by andreaslyn** [comment]
> Can you open a issue on the coq bug tracker for the last issue here (that seems to be still open I believe)?

There is a solution for the last issue also. Let me make a coq issue and submit a PR for that one.
