### ISSUE TITLE
coqide with -indices-matter was not found during configuration

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1040]
A fresh build of the HoTT library is unable to run hoqide since
```
Fatal error: coqide with -indices-matter was not found during configuration.
```
I have tried this on two different Ubuntu 18 machines. One of them was definitely able to compile and run coqide with no issues before.

I am fairly certain this has something to do with LablGtk3. This is because when I run `./etc/install_coq.sh` I get:
```
LablGtk3 not found:
=> no CoqIde will be built.
```

But when I run `./etc/install_coq_deps.sh` it says it is already installed...

I did some digging in the configure.ml scripts that come with coq, and see that this is the part telling me no CoqIde will be built:

```
(** * lablgtk3 and CoqIDE *)

(** Detect and/or verify the Lablgtk3 location *)

let get_lablgtkdir () =
  tryrun camlexec.find ["query";"lablgtk3-sourceview3"]

(** Detect and/or verify the Lablgtk2 version *)

let check_lablgtk_version () =
  let v, _ = tryrun camlexec.find ["query"; "-format"; "%v"; "lablgtk3"] in
  (true, v)

(* ejgallego: we wait to do version checks until an official release is out *)
(*  try
    let vi = numeric_prefix_list v in
    (* Temporary hack *)
    if vi = ["3";"0";"beta3"] then (false, v) else
    let vi = List.map s2i vi in
    if vi < [3; 0; 0] then
      (false, v)
    else
      (true, v)
  with _ -> (false, v)
*)

let pr_ide = function No -> "no" | Byte -> "only bytecode" | Opt -> "native"

exception Ide of ide

(** If the user asks an impossible coqide, we abort the configuration *)

let set_ide ide msg = match ide, !prefs.coqide with
  | No, Some (Byte|Opt)
  | Byte, Some Opt -> die (msg^":\n=> cannot build requested CoqIde")
  | _ ->
    cprintf "%s:\n=> %s CoqIde will be built." msg (pr_ide ide);
    raise (Ide ide)

let lablgtkdir = ref ""

(** Which CoqIde is possible ? Which one is requested ?
    This function also sets the lablgtkdir reference in case of success. *)
```

So it seems to me this code is failing to identify that LablGtk3 is installed.

**Comment by SkySkimmer** [comment]
>But when I run ./etc/install_coq_deps.sh it says it is already installed...

install_coq_deps says gtk2 not gtk3 AFAICT...

**Comment by Alizter** [comment]
@SkySkimmer Should we update the script to install gtk3 as well?

**Comment by SkySkimmer** [comment]
Try and see if it works I guess.
You can find specific package names in Coq's Dockerfile https://github.com/coq/coq/blob/master/dev/ci/docker/bionic_coq/Dockerfile#L13

**Comment by Alizter** [comment]
The problem is I don't actually understand how to install gtk3. It is not clear how I am supposed to do this. Moreover I have tried the one from the INSTALL file in the main coq repo, but it doesn't seem to get picked up by ./install_coq.sh . Can you confirm that you are able to build coqide?

**Comment by SkySkimmer** [comment]
What specific commands did you run?
I confirm that Coq builds coqide in that docker image

**Comment by Alizter** [comment]
On this page
[https://github.com/coq/coq/wiki/Installation-of-Coq-on-Linux](https://github.com/coq/coq/wiki/Installation-of-Coq-on-Linux)
In the section "Installation from sources" it says these commands should be run:
```
sudo apt-get install build-essential   # gcc and more
sudo apt-get install ocaml

# only for Coq <8.10
sudo apt-get install camlp5

# needed for coqide (Coq <8.10)
sudo apt-get install liblablgtk2-ocaml
sudo apt-get install liblablgtk2-ocaml-dev
sudo apt-get install libgtk2.0
sudo apt-get install liblablgtk-extras-ocaml-dev
sudo apt-get install libcanberra-gtk-dev

# needed for coqide (Coq >=8.10)
sudo apt-get install liblablgtksourceview3-ocaml-dev
```
But I cannot locate this package:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package liblablgtksourceview3-ocaml-dev
```

Perhaps my apt is broken? But I do not know how to fix this?

**Comment by SkySkimmer** [comment]
As specified in the docker file the package name is libgtksourceview-3.0-dev, the wiki is just wrong

**Comment by SkySkimmer** [comment]
It's a relatively recent package so maybe it doesn't exist yet on whatever version of whatever distro you use.

**Comment by Alizter** [comment]
OK for what ever reason I had this installed already. But when I try to run install_coq it is now working, albeit with a warning:
```
Warning: Your installed lablgtk reports as 2.16.0.
It is possible that the installed version is actually more recent
but reports an incorrect version. If the installed version is
actually more recent than 2.18.3, that's fine; if it is not,

CoqIDE will compile but may be very unstable.

```

I think you are spot on with that package however. I will try my other machine just to make sure.

**Comment by Alizter** [comment]
On my other machine
```
sudo apt install libgtksourceview-3.0-dev
```
says I already have it installed. When I try to run install_coq it says it cannot find LablGtk3...

**Comment by SkySkimmer** [comment]
I made a post saying libgtksourceview-3.0-dev was enough, which I then realized is incorrect. I had hoped I deleted it before it was seen but it seems that too was incorrect.
You need either liblablgtksourceview3-ocaml-dev, or libgtksourceview-3.0-dev and then install lablgtk3-sourceview3 through opam (or any other method I guess)

**Comment by Alizter** [comment]
Opam can't find `lablgtk3-sourceview3`. Do I need to configure something?

**Comment by guillaumebrunerie** [comment]
> Opam can't find `lablgtk3-sourceview3`. Do I need to configure something? My version is 1.2.2.

You need opam 2.0.x.

**Comment by Alizter** [comment]
This was because my current coq submodule wasn't up to date. Everything gets resolved when starting from scratch.
