### ISSUE TITLE
How to prove transport_equiv

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1044]
I have the following hypothesis:
```
transport (fun y : Susp X => susp_fibration y <~> X) (merid x) (reflexive_equiv X) 
= reflexive_equiv X
```
I couldn't find a lemma such as transport_equiv which allows me to break apart this transport. I was thinking perhaps if we have a family of equivalences `fun x => P x <~> Q x`, then maybe we might get an equivalence of transports `transport P <~> transport Q` in some way. Then using univalence somehow I can turn this into a transport_paths situation which I can work with. But I haven't been able to do any of this. Any ideas?

**Comment by SkySkimmer** [comment]
I think the usual thing to do when you have transport over a path constructor of some HIT (here `merid`) is to rewrite using `transport_compose` to get `ap`(D if dependent) applied to the induction principle, then use the computation principle for the path constructor.
See eg `transport_S1_code_loop` in Circle.v, or the following (assuming I got the right definition for `susp_fibration`, if I didn't hopefully you can adapt):
~~~coq
Require Import HoTT.
Generalizable All Variables.

Definition susp_fibration {X:Type} : Susp X -> Type := Susp_rec X X (fun _ : X => idpath).

Goal `(transport (fun y : Susp X => susp_fibration y <~> X) (merid x) (reflexive_equiv X)
       = reflexive_equiv X).
  intros.
  rewrite (@transport_compose _ _ _ _ (fun Y => Y <~> X)).
  (* rewrite transport_compose with (P:=fun Y => Y <~> X). is the same thing *)
  unfold susp_fibration.
  rewrite Susp_rec_beta_merid.
  reflexivity.
Qed.
~~~

>I have the following hypothesis:

Do you mean goal?
If you did mean hypothesis you can still do the rewrites to show that your hypothesis has type equivalent to `reflexive_equiv X = reflexive_equiv X`.

**Comment by Alizter** [comment]
Sorry yes I meant goal. [This is my formalisation that I am working on currently](https://github.com/Alizter/HoTT/blob/080cf543b92bbc4bec06d4861a32777ae4b420ac/contrib/HopfConstruction.v#L107).

I had tried the transport_compose before but I couldn't get it to unify, I will try again.

**Comment by Alizter** [comment]
OK excellent that has worked. Thanks for the help! :-)
