### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by andreaslyn** [HoTT/HoTT#1046]
While compiling the library we receive a lot of warnings. Most kinds of warnings are straight forward to fix, but I am unsure about a couple of them.

The first kind of warning that I am unsure about is the the following from `coqdep`:
```
*** Warning: in file coq/theories/Init/Prelude.v, declared ML module numeral_notation_plugin has not been found!
```
How can `coqdep` be provided with the path to the `numeral_notation_plugin.cmxs` ocaml module?

The other warning is the following kind:
```
File "./theories/Categories/InitialTerminalCategory/NaturalTransformations.v", line 4, characters 0-40:
Warning: Ambiguous paths: [nat_category; object] : nat >-> Sortclass
```
What does this warning mean and how to fix it?

**Comment by Alizter** [comment]
I am also getting a lot of warning about using `autoapply ... using` instead of `autoapply ... with`. This mostly seems to come from mathclasses but I can't seem to understand why they are happening, since the errors are being generated by apply tactics?

**Comment by andreaslyn** [comment]
> I am also getting a lot of warning about using `autoapply ... using` instead of `autoapply ... with`. 

We can get rid of these warnings by changing `class_apply` in `Overture.v` to
```
Ltac class_apply c := autoapply c with typeclass_instances.
```

**Comment by spitters** [comment]
Google gives this answer:
https://coq.inria.fr/refman/addendum/implicit-coercions.html

Perhaps related:
https://github.com/coq/coq/pull/9743

**Comment by SkySkimmer** [comment]
The ambiguous path warning may be easier to investigate if you run Coq with the change from https://github.com/coq/coq/pull/10336 included.

**Comment by andreaslyn** [comment]
Now that https://github.com/HoTT/HoTT/pull/1047 has been merged, only the two `coqdep` warnings remain:
```
*** Warning: in file coq/theories/Init/Prelude.v, declared ML module numeral_notation_plugin has not been found!
```

**Comment by Alizter** [comment]
@andreaslyn Open a new issue for those?
