### ISSUE TITLE
Automatically unfolding Sect

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1050]
Would anybody be opposed to having
```
  Arguments Sect _ _ /.
```

I have had many occasions where I wanted cbn to unfold Sect as well.

**Comment by spitters** [comment]
If the diff is not too big, it would be fine with me.

**Comment by Alizter** [comment]
I will be making a pull request soon, so I will add this change then.

**Comment by mikeshulman** [comment]
Please don't incorporate this into another pull request, make it as its own PR so we can discuss its merits separately.
