### ISSUE TITLE
Page94  maybe wrong prove step when showing decode ( x, encode ( x, p )) = p

### ISSUE THREAD

**Issue by MuseBoy** [HoTT/HoTT#1056]
The 4th line in prove $\equiv inl(refl_{a_0})$ is unnecessary and wrong.
If I am wrong, teach me please.

**Comment by Alizter** [comment]
@MuseBoy Are you talking about the book? If so this is the wrong repository, you want [HoTT/book](https://github.com/HoTT/book).

 Also different additions of the HoTT book have different page numbers so a section number is a better pointer.

**Comment by MuseBoy** [comment]
@Alizter  thank you.
