### ISSUE TITLE
timing scripts are not working

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1059]
I have not been able to get the timing scripts to work. Whenever they finish they say "No timing data". Are there some dependencies that I am missing? How can I debug this?

**Comment by Alizter** [comment]
Perhaps we need some more documentation on how to get timing scripts to work?

**Comment by spitters** [comment]
@JasonGross created these.

**Comment by Alizter** [comment]
For now, if anyone else is interested, the timing scripts are working fine in travis. So it is possible to modify the travis script and push to your own branch. If you have set up travis to check these then it will do the job and give you the timing data.

**Comment by JasonGross** [comment]
You need a version of `time` that accepts `-f` and you need python (possibly python 2.7), and you also need bash, make, coqc, etc.  I'm not really sure how it could be not working, as all it does is run `make TIMED=1 | tee`, and then process the build logs...

**Comment by JasonGross** [comment]
What commands are you running, exactly?

**Comment by Alizter** [comment]
I am running make-pretty-timed.sh from etc/coq-scripts/timing/. It builds the whole library and then says No timing data.

**Comment by Alizter** [comment]
I think my issue is time that accepts -f

**Comment by Alizter** [comment]
So it appears that I have two time commands. I read that I have an inbuilt time and a non-inbuild one which can be called as \time.

**Comment by Alizter** [comment]
Which one is the intended one?
```
(xenial)ali@localhost:~/HoTT$ time ls
aclocal.m4      contrib      hoqchk         html         proviola-html
autogen.sh      coq          hoq-config     INSTALL.md   proviola-xml
autom4te.cache  coq-HoTT     hoq-config.in  LICENSE.txt  README.md
config.log      _CoqProject  hoqdep         Makefile     STYLE.md
config.status   CREDITS.txt  hoqide         Makefile.am  theories
configure       etc          hoqtop         Makefile.in  UNICODE.txt
configure.ac    hoqc         hoqtop.byte    proviola

real	0m0.037s
user	0m0.003s
sys	0m0.005s
(xenial)ali@localhost:~/HoTT$ \time ls
aclocal.m4	contrib      hoqchk	    html	 proviola-html
autogen.sh	coq	     hoq-config     INSTALL.md	 proviola-xml
autom4te.cache	coq-HoTT     hoq-config.in  LICENSE.txt  README.md
config.log	_CoqProject  hoqdep	    Makefile	 STYLE.md
config.status	CREDITS.txt  hoqide	    Makefile.am  theories
configure	etc	     hoqtop	    Makefile.in  UNICODE.txt
configure.ac	hoqc	     hoqtop.byte    proviola
0.00user 0.00system 0:00.02elapsed 17%CPU (0avgtext+0avgdata 2532maxresident)k
0inputs+0outputs (0major+110minor)pagefaults 0swaps

```

**Comment by JasonGross** [comment]
The configure script looks for a `time` binary in `$PATH`, and assumes that it can run `/path/to/time -f "STUFF (user: %U mem: %M ko)"`.  If you install gnu time (?), I believe the `time` binary will live in `/usr/bin/time`.

**Comment by Alizter** [comment]
@JasonGross Ah OK, it was the configure script I was missing. We should add that the timing scripts won't work unless gnu time is installed and ./configure has found it.

**Comment by JasonGross** [comment]
Would you be willing to prepare such a documentation pull request?

**Comment by Alizter** [comment]
@JasonGross Yes, I will look at it tomorrow.
