### ISSUE TITLE
Mapping of contrib folder on hoq___.sh leads to issues with CoqIDE (all platforms)

### ISSUE THREAD

**Issue by MSoegtropIMC** [HoTT/HoTT#1063]
The -Q option for the contrib folder in e.g. (https://github.com/HoTT/HoTT/blob/master/hoqide), that is `-Q "$HOTTCONTRIB" ""` leads to issues in CoqIDE, as far as I can tell on all platforms. Compile Buffer won't work with this option because the empty string "" is not properly quoted.

Unless there are good reasons to keep it like this, I would suggest to change this to `-Q "$HOTTCONTRIB" "Contrib"`. See the discussion in (https://github.com/coq/coq/issues/10590) and (#1058)

Of cause this will most likely be fixed in CoqIDE some time, but it might take a while.

**Comment by Alizter** [comment]
This is fixed by #1433
