### ISSUE TITLE
Can univeres be indexed by nat?

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1069]
I am guessing the answer to this question is no, but I have seen in many places something along these lines:

The type of n-truncated types in the nth universe.

Surely these can't be the same n? Because the above statement would have to live in a universe that contains all the other universes it is indexing, no?

Such statements appear in [Kraus-Sattler](https://arxiv.org/pdf/1311.4002.pdf) which I have been trying to formalise for the last week or so.

There is probably a Coq hack we can use to simulate something like this, but I am not sure it even makes sense.

**Comment by mikeshulman** [comment]
In general, it depends on the underlying type theory.  In Coq, the n in "the nth universe" does not even belong to an internal type.  In Agda, there is a type of "levels" containing such n's, but it is not the same as the internal nat (e.g. it doesn't have an induction principle) and I think doesn't belong to any universe itself.  I don't think it's intrinsically inconsistent to have the type of universes indexed by the internal nat, but I don't know of any type theory that does it that way (and the semantics of such a theory is quite fiddly, I'm not sure I would know how to model it at all).

**Comment by Alizter** [comment]
Is it even possible for a type theory to have the type of universes indexed by the internal nat?

If there was some "biggest" universe V in which every other universe lived, this could be a place for `U : nat -> V` to live. With the (possible inconsistent) assumption that V : V. If we also had some "axioms" that can place Un in the correct (small) universe. We might be able to keep it consistent by saying that you have to use these "axioms".

**Comment by mikeshulman** [comment]
Yes.  One way it's possible is to have a universe `U_omega` that does not belong to itself but rather to a next universe `U_{omega+1}`, and so on.  Another simpler way is not to demand that every type family belong to a universe, so we have `n:nat |- U_n type` but can't abstract it into a function.

**Comment by SkySkimmer** [comment]
I'm not sure how the constraints would work when indexing universes by nat, wouldn't you risk being able to build non terminating terms in inconsistent contexts? ie `0 < 0 |- U_0 : U_0` and then build the usual proof of False.

**Comment by EgbertRijke** [comment]
If there is a family of universes indexed by the type nat then there are
types that do not belong to any of the universes in this family. For
example

Sigma (n:nat), U(n)

would be such a type. In agda this problem is addressed by an omega-th
universe. In the book this problem is addressed by having the indexing
externally, so U(n) is not a type family over nat.

**Comment by mikeshulman** [comment]
@SkySkimmer that's an interesting point; it does seem that at least if the universe constraints are identified with the internal operations on nat, then an internally nat-indexed family of universes would induce local nontermination.

@EgbertRijke Agda pretends to have an omega-th universe, but my impression from reading the docs about how it behaves is that it's really more like syntactic sugar for an `A type` judgment for types not belonging to any universe.

**Comment by Alizter** [comment]
I forgot to mention this at the time so I will now.

I spoke with Nicolai about what exactly is meant by using the "same n" in the main theorem of the paper. He told me that the theorem is really a meta theorem about HoTT, or a family of theorems in HoTT if you will.

He said given any external n, say 4, it is always possible to construct the internal version, analyse a hierarchy of 4 universes and state the result.

The only issue here is that you really cannot formalise such statements. Although it might be possible to do something hacky in coq, and generate these theorems "on the fly". Perhaps with modules?

I will close this issue for now, since I don't think it is really an issue anymore.
