### ISSUE TITLE
Rename pp

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#1080]
I think the name `pp` for the glue in a `pushout` is not good.  It's too short and ambiguous for a global name.  Moreover, it leads to lemmas like `equiv_pushout_pp`, which is potentially conflicty with our convention of `pp` in lemmas to refer to a concatenation of paths (e.g. `transport_pp`).  Maybe something like `pglue`?

**Comment by Alizter** [comment]
I'm in favour of pglue.

**Comment by Alizter** [comment]
What was the original meaning of pp anyway? pushout path?

**Comment by mikeshulman** [comment]
I don't know, but "pushout path" seems like a good guess.

**Comment by Alizter** [comment]
Here are all the files infected with pp at the moment. 

```
theories/HIT/Colimits/Flattening.v
theories/HIT/Colimits/Pushout.v
theories/HIT/epi.v
theories/HIT/Pushout.v
theories/HIT/SpanPushout.v
theories/HIT/Join.v
theories/HIT/Suspension.v
theories/Homotopy/BlakersMassey.v
theories/Homotopy/Smash.v
theories/Homotopy/Wedge.v
```
