### ISSUE TITLE
Require Import UnivalenceAxiom leaks Univalence

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1081]
If I have a file A.v that has `Require Import UnivalenceAxiom.` in it, and I have another file B.v that Require Imports A, then we currently have Univalence in B also.

This has caused me a few headaches since things that require Univalence suddenly work without wanting them to.

There are two solutions:
 - Don't use UnivalenceAxiom anywhere in the library (but then why does it exist?)
 - Somehow stop UnivalenceAxiom from leaking Univalence

I would prefer the second option, but I have no idea how to do this.

**Comment by JasonGross** [comment]
I seem to recall @ppedrot implementing some option to make typeclass instances follow `Import` rather than `Require`?  If so, we could probably use that.

**Comment by ppedrot** [comment]
Unfortunately, this option affects the client code, not the code defining the instance. I guess we can also provide the dual option that makes instance *declarations* being import-scoped?

**Comment by ppedrot** [comment]
@Alitzer anyways if you want to be sure that inside one of your modules the typeclass instance doesn't get triggered, use `Set Loose Hint Behavior "Strict"` in the header of that file.

**Comment by mikeshulman** [comment]
`UnivalenceAxiom` is not intended for use anywhere in the library.  The reason it exists is for client code where people want to be lazy.  But inside the library we are not lazy and assume our instances of `Univalence` wherever we need it.

**Comment by Alizter** [comment]
@mikeshulman I wonder if we can detect uses with `make strict` that way we can avoid accidental use.

**Comment by SkySkimmer** [comment]
If you put `Fail Check HoTT.UnivalenceAxiom.univalence_axiom.` in HoTT.v after all the requires it will ensure the axiom isn't required by any of the files HoTT.v depends on.

**Comment by Alizter** [comment]
@SkySkimmer That sounds like a good idea. I will keep this issue open so we can discuss doing it, and perhaps try it in the future.
