### ISSUE TITLE
Faking the join construction

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1083]
In Theorem 2.25 of Localization in homotopy type theory (CORS), the L-seperated subuniverse is shown to be a reflective subuniverse (RSU).

I have something like this going on:

```coq
Require Import Basics.
Require Import Types.
Require Import Modalities.ReflectiveSubuniverse.
Require Import HIT.Truncations.
Require Import Factorization.
Import TrM.

Definition image_uni (X : Type) (Y : X -> X -> Type)
  := image -1 (fun p =>  Y (fst p) (snd p)).

Module Seperated_ReflectiveSubuniverse (Ls : ReflectiveSubuniverses)
  <: ReflectiveSubuniverses.

  Import Ls.

  Definition O_reflector : ReflectiveSubuniverse@{u a} -> Type@{i} -> Type@{i}.
  Proof.
    intros L X.
    erapply intermediate.
    rapply (image_uni X).
    intros x y.
    apply (O_reflector L).
    exact (x = y).    
```

Now this results in an unsuprising universe inconsistency. In CORS they overcome this by defining the image using the join construction, hence the universe levels work out. I was hoping I could somehow fake having the join construction, so that the above code can be made to work.

Is there something I can do to `image_uni` to make this work?

The correct answer is obviously "go formalise the join construction", but this will be too large a detour for the moment.

Any ideas?

**Comment by mikeshulman** [comment]
Well, one possibility would be to stick to the accessible case, where L' is localization at the suspension of the generators of L.
