### ISSUE TITLE
Swapping order of truncation

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1084]
Is there an easy proof for the following lemma?
```coq
Require Import Basics Types HIT.Truncations.
Import TrM.

Definition Trunc_swap n m X : Tr n (Tr m X) <~> Tr m (Tr n X).
Proof.
Admitted.
```

I managed to prove it by defining a min function on truncindex, showing that truncations cummulate their indexes in a min and then showing that min can have its order swapped. This seems a bit long winded to me, but is ok I guess.

**Comment by mikeshulman** [comment]
I can't think of any way to prove it without passing through a min somehow.

**Comment by SkySkimmer** [comment]
You can do it if you prove `IsTrunc n X -> IsTrunc n (Tr m X)`
~~~coq
Definition Trunc_ind2 {n A}
  (P : Trunc n A -> Trunc n A -> Type) {Pt : forall aa bb, IsTrunc n (P aa bb)}
  : (forall a b, P (tr a) (tr b)) -> (forall aa bb, P aa bb).
Proof.
  intros f aa;refine (Trunc_ind _ _).
  intros b;revert aa;refine (Trunc_ind _ _).
  intros a;apply f.
Defined.


Lemma istrunc_truncation_alt {univalence:Univalence} n : forall m X `{IsTrunc n X}, IsTrunc n (Tr m X).
Proof.
  induction n as [|n IHn];intros m X Hx.
  - exists (tr (center X)).
    refine (Trunc_ind _ _).
    intros;apply ap,contr.
  - hnf;change IsTrunc_internal with IsTrunc;cbv -[IsTrunc] in *.
    refine (Trunc_ind2 _ _).
    + intros. destruct m as [|m].
      * exists _. intros;apply path_ishprop.
      * eapply trunc_leq;[|exact (HProp.hprop_trunc _ _)]. exact tt.
    + destruct m as [|m].
      * intros. apply (trunc_leq (m:=minus_two) tt).
      * intros. pose proof (@equiv_path_Tr univalence m X a b) as f. cbv in f.
        apply  (@trunc_equiv _ _ f n _ _).
Defined.
Existing Instance istrunc_truncation_alt.

Definition Trunc_swap `{Univalence} n m X : Tr n (Tr m X) <~> Tr m (Tr n X).
Proof.
  simple refine (equiv_adjointify _ _ _ _).
  - refine (Trunc_ind _ _).
    apply Trunc_functor,tr.
  - refine (Trunc_ind _ _).
    apply Trunc_functor,tr.
  - red. refine (Trunc_ind _ _).
    refine (Trunc_ind _ _).
    reflexivity.
  - red. refine (Trunc_ind _ _).
    refine (Trunc_ind _ _).
    reflexivity.
Defined.
~~~
I don't know if there's a way to do it without univalence though.

**Comment by EgbertRijke** [comment]
Note that the n-truncation preserves all truncation levels, i.e. if X is
m-truncated, then ||X||_n is m-truncated. Therefore it follows that ||
||X||_m ||_n is m-truncated. To show that || ||X||_m ||_n is the
m-truncation of ||X||_n it is equivalent to show that the map

||eta_m||_n : ||X||_n -> || ||X||_m ||_n

induced by the unit of the m-truncation eta_m : X -> ||X||_m is an
m-connected map. This is easy, because eta_m is an m-connected map and the
n-truncation also preserves the m-connectedness of any map for any m.

Good luck with the formalization!

**Comment by Alizter** [comment]
Thank you for your suggestions. I came up with another proof as follows:

It can be shown that the less than or equals to relation on truncation indicies is decidable. This allows us to split up the proof into two relatively easy cases. Of course `not (n <= m)` is not exactly `m <= n` but does imply it.

I think I may open (yet another) issue for organising various lemmas about truncations. Its not entirely obvious to me what should go where. In fact, having a truncations folder containing various things on truncations and connectedness would be beneficial as we collect more and more lemmas. We can also move HIT.Truncations and HIT.Connectedness in here too.
