### ISSUE TITLE
Organising truncations

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1085]
Here are some suggestions on the organisation of truncations. This is somewhat related to #1067.

Firstly I would like to create a folder called Truncations in theories. This would contain the following files:
 - Core.v for the definition of Truncation and basic properties (i.e. what is currently in HIT.Truncations).
 - Truncations.v for various lemmas deriving from truncations
 - Connectedness.v for various lemmas about connectedness
 - TruncIndex.v for various lemmas about trunc indexes, their arithemetic etc.

I would also like to make some changes to `trunc_index_leq` by declaring it to be a class.

These would all be packaged up in an index file called Truncations.v, so whenever you want a lemma about truncations, Require Importing Truncations.v will cover it for you.

I am open to keeping the definition of truncation (what would be in Core.v) in HIT since it is a "raw" HIT as discussed in #1067.

A seperate file for the arithmetic of trunc indexes would be beneficial since it is not require by most things that import Basics.

Please tell me how you like this idea, and any suggestions you might have.

**Comment by Alizter** [comment]
@mikeshulman The difference being, Core contains the definition and Truncations (or Truncation) contains lemmas about it. It could be that the later depends on TruncIndex for example so to save these all being stuffed into a big file I suggest splitting these up.

**Comment by mikeshulman** [comment]
Hmm.  I don't like the name Truncations/Truncations, it is very uninformative.  Can you give a more descriptive name to those lemmas?

**Comment by Alizter** [comment]
@mikeshulman Actually putting them in Core shouldn't be such an issue. Core can depend on TruncIndex stuff, and connectedness will depend on them both most likely.
