### ISSUE TITLE
Tactic for "issig"ing any record

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1097]
As discussed in #1093, we should implement the tactic "issign" mentioned in that discussion. Currently I propose replacing all issig tactics with this one tactic.

The advantage of this is now it is really easy to prove a record is equivalent to a sigma type. Since this is completely routine style of proof, I don't see what benefit we get from not doing it this way.

I have a branch with this done, but there are 3 cases where the new issig doesn't have the same behavior as the old. Which is discussed in the PR above. I have yet to add documentation too.

This issue serves mainly as a note that it is being done.

**Comment by mikeshulman** [comment]
You may want to add a timing diff to the eventual PR, so we can see whether it impacts performance any.  IIRC there was at least one place in categories where ordinary `issig` was already too slow.

**Comment by Alizter** [comment]
@mikeshulman OK will do.

**Comment by Alizter** [comment]
@JasonGross  So continuing the discussion from #1093, the issign tactic works for every issig I could find except for `issig_isomorphic` in `Classes/theory/ua_isomorphic.v`. Even after changing the refines to notypeclasses.

Here is the exact code that doesn't work. At the end, issign fails at unifying.

```coq
Require Export HoTT.Classes.theory.ua_homomorphism.

Require Import
  HoTT.Basics.Overture
  HoTT.Basics.Trunc
  HoTT.Basics.Equivalences
  HoTT.Types.Forall
  HoTT.Types.Sigma
  HoTT.Types.Record
  HoTT.Types.Universe
  HoTT.Tactics.

Ltac require_as_test_cps require if_yes if_no :=
  let res := match constr:(Set) with
             | _ => let __ := match constr:(Set) with _ => require () end in
                    ltac:(if_yes)
             | _ => ltac:(if_no)
             end in
  res ().
Ltac peel_evars term :=
  lazymatch term with
  | ?f ?x
    => require_as_test_cps ltac:(fun _ => has_evar x)
                                  ltac:(fun _ => peel_evars f)
                                         ltac:(fun _ => term)
  | _ => term
  end.

Ltac pi_to_sig ty :=
  lazymatch (eval cbv beta in ty) with
  | forall (x : ?T) (y : @?A x), @?P x y
    => let x' := fresh in
       constr:(@sigT T (fun x' : T => ltac:(let res := pi_to_sig (forall y : A x', P x' y) in exact res)))
  | ?T -> _ => T
  end.

Ltac ctor_to_sig ctor :=
  let ctor := peel_evars ctor in
  let t := type of ctor in
  pi_to_sig t.

Ltac unify_first_evar_with term u :=
  lazymatch term with
  | ?f ?x
    => tryif has_evar f
    then unify_first_evar_with f u
    else unify x u
  end.

Ltac unify_with_projections term u :=
  (unify_first_evar_with term u.1; unify_with_projections term u.2) +
  (unify_first_evar_with term u;
   tryif has_evar term then fail 0 term "has evars remaining" else idtac).

Ltac refine_with_existT_as_much_as_needed_then_destruct v :=
  ((destruct v; shelve) +
   (simple notypeclasses refine (_ ; _);
    [ destruct v; shelve
    | refine_with_existT_as_much_as_needed_then_destruct v ])).

Ltac issign :=
  hnf;
  let A := match goal with |- ?A <~> ?B => constr:(A) end in
  let B := match goal with |- ?A <~> ?B => constr:(B) end in
  let u := fresh "u" in
  let v := fresh "v" in
  simple notypeclasses refine
         (BuildEquiv A B _
                     (BuildIsEquiv
                        A B
                        (fun u => _)
                        (fun v => _)
                        (fun v => _)
                        (fun u => _)
                        (fun _ => _)));
  [ let T := match goal with |- ?T => T end in
    let built := open_constr:(ltac:(econstructor) : T) in
    let A' := ctor_to_sig built in
    unify A A';
    unify_with_projections built u;
    refine built
  | refine_with_existT_as_much_as_needed_then_destruct v
  | destruct v; cbn [pr1 pr2]; reflexivity
  | reflexivity
  | reflexivity ].


(** Two algebras [A B : Algebra σ] are isomorphic if there is an
    isomorphism [∀ s, A s → B s]. *)

Record Isomorphic {σ : Signature} (A B : Algebra σ) := BuildIsomorphic
  { def_isomorphic : ∀ s, A s → B s
  ; is_homomorphism_isomorphic : IsHomomorphism def_isomorphic
  ; is_isomorphism_isomorphic : IsIsomorphism def_isomorphic }.

Arguments BuildIsomorphic {σ A B} def_isomorphic
            {is_homomorphism_isomorphic} {is_isomorphism_isomorphic}.

Arguments def_isomorphic {σ A B}.
Arguments is_homomorphism_isomorphic {σ A B}.
Arguments is_isomorphism_isomorphic {σ A B}.

Global Existing Instance is_homomorphism_isomorphic.
Global Existing Instance is_isomorphism_isomorphic.

Module isomorphic_notations.
  Global Notation "A ≅ B" := (Isomorphic A B)
                             (at level 75, no associativity)
                             : Algebra_scope.
End isomorphic_notations.

Import isomorphic_notations.

Definition SigIsomorphic {σ : Signature} (A B : Algebra σ) :=
  { def_iso : ∀ s, A s → B s
  | { _ : IsHomomorphism def_iso | IsIsomorphism def_iso }}.

Lemma issig_isomorphic {σ : Signature} (A B : Algebra σ)
  : SigIsomorphic A B <~> A ≅ B.
Proof.
(*   issign. *)
  serapply BuildEquiv.
  { intro u.
    refine (@BuildIsomorphic _ _ _ u.1 u.2.1 u.2.2). }
  serapply BuildIsEquiv.
  { intro v.
    exact (def_isomorphic v; _; is_isomorphism_isomorphic v). }
  1: by intros [].
  1: exact eta2_sigma.
  reflexivity.
Defined.
```

**Comment by Alizter** [comment]
@JasonGross So I managed to find where the problem occurs. `unify_with_projections` is never called successfully it seems. Probing with idtac I found `unify_first_evar_with` has the problems. I should note that this has nothing to do with the way the sigma type has been written since the tactic cannot even guess it. The issign tactic just does not work for the record `Isomorphic` for whatever reason.

**Comment by JasonGross** [comment]
Interesting.  If, for each call to unify, you first print out the terms and their types, what do you see?  What's the unification problem that should succeed but doesn't?  And what are the `term` and `u` passed to `unify_with_projections` in the first place?

**Comment by JasonGross** [comment]
> I should note that this has nothing to do with the way the sigma type has been written since the tactic cannot even guess it.

But the tactic does guess it, or else `unify_with_projections` would never be called.  The tactic responsible for guessing the sigma type is `ctor_to_sig`.

**Comment by Alizter** [comment]
@JasonGross What I meant with the guessing is that if I let it infer the sigma type the tactic still fails so it was nothing to do with a dodgy sigma or anything.

**Comment by JasonGross** [comment]
@Alizter The problem is that `econstructor` invokes typeclass resolution.  If you define the following and then replace `ltac:(econstructor)` with `ltac:(ntceconstructor)` in `issign`, then it works:
```coq
Tactic Notation "ntcrefine" uconstr(term) := notypeclasses refine term.

Ltac ntcrapply p :=
  ntcrefine p ||
  ntcrefine (p _) ||
  ntcrefine (p _ _) ||
  ntcrefine (p _ _ _) ||
  ntcrefine (p _ _ _ _) ||
  ntcrefine (p _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _ _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _ _ _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _ _ _ _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _ _ _ _ _ _ _ _ _) ||
  ntcrefine (p _ _ _ _ _ _ _ _ _ _ _ _ _ _ _).

Ltac get_builder T :=
  let x := fresh in
  let x' := fresh in
  let h := open_constr:(_) in
  let __ := constr:(fun (x : T)
                    => let x' := x in
                       ltac:(destruct x;
                             let x' := (eval cbv delta [x'] in x') in
                             let x' := head x' in
                             unify h x';
                             exact I)) in
  h.

Ltac ntceconstructor :=
  lazymatch goal with
  | [ |- ?G ] => let build := get_builder G in
                 ntcrapply build
  end.
```

**Comment by Alizter** [comment]
@JasonGross Will this affect performance, should we only use it if it fails first time?

**Comment by Alizter** [comment]
@JasonGross What is `head`?

**Comment by JasonGross** [comment]
I expect the impact on performance here to be relatively minor.  Roughly the time it takes to destruct the record type once + the time it takes to unify the record type with itself as many times as there are fields.  I think it's not worth complicating the tactic even more by trying one and then the other.

**Comment by JasonGross** [comment]
`head` is one of the tactics available after all of the imports, defined somewhere in the library.  It recursively finds the head of an application chain.

**Comment by Alizter** [comment]
@JasonGross Ah ok I found it in Tactics.v.

**Comment by mikeshulman** [comment]
Jason's timing scripts give an easy way to measure whether any given change has a performance impact.

**Comment by Alizter** [comment]
@mikeshulman Yes, I will provide the timing changes when I do the PR.
