### ISSUE TITLE
Change name of PropResizing/Truncations

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1100]
I would like to change the name of PropResizing/Truncations to something else for two reasons:

1. It stops anyone ever importing it instead of HIT.Truncations without knowing.
2. It stops a naming conflict to that we don't have to write HIT. everytime.

The second one is more important since in #1085, I am planning to have an index file Truncations.v which will export the contents of a Truncations folder. This currently clashes with PropResizing.

Since this is only about propositional truncation, perhaps a name like `PropTrunc.v` might be in order.

Another suggestion is `ImpredicativeTrunc.v` or some variant thereof.

**Comment by mikeshulman** [comment]
I would probably go for `ImpredicativeTruncations`.
