### ISSUE TITLE
UnivalenceImpliesFunext being leaked

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1101]
It was suggested in #1081 that there be checks in HoTT.v to make sure none of the axiom files are being leaked.

I added the following at the end of HoTT.v:
```coq
(** We check that UnivalenceAxiom, FunextAxiom, UnivalenceImpliesFunext, IntervalImpliesFunext and TruncImpliesFunext aren't being leaked. *)
Fail Check HoTT.UnivalenceAxiom.univalence_axiom.
Fail Check HoTT.FunextAxiom.funext_axiom.
Fail Check HoTT.UnivalenceImpliesFunext.Univalence_implies_Funext.
Fail Check HoTT.HIT.IntervalImpliesFunext.funext_from_interval.
Fail Check HoTT.TruncImpliesFunext.funext_from_trunc.
```
Only `Univalence_implies_Funext` is failing. I notice that we are using this everywhere (in at least 20 files). The problem seems to be that if one file imports it than anything that imports this file inherits UnivalenceImpliesFunext.

Now I see two solutions to this:
 - Somehow stop the leakage. I don't know how to do this.
 - Assume UnivalenceImpliesFunext in Basics (i.e. move it there) so that it always holds.

I can't imagine why you would have univalence but not funext so the second option is more appealing to me. I won't suggest it however since I could be shortsighted.

**Comment by mikeshulman** [comment]
UnivalenceImpliesFunext, IntervalImpliesFunext, and TruncImpliesFunext are different than UnivalenceAxiom and FunextAxiom, and can be used anywhere in the library; there's no reason to try to prevent them from "leaking".  They are all statements that can be *proven* (and indeed, are proven in the relevant files).  In fact I don't remember exactly why the "used" version is technically implemented as "axioms" instead; maybe to make them (more) universe-polymorphic?

**Comment by mikeshulman** [comment]
In other words, the solution is to just drop the last three lines from your code.

**Comment by Alizter** [comment]
I think this points to a different issue however. Shouldn't we have UnivalenceImpliesFunext everywhere? Since we inherit it from importing any files that use it. It doesn't really make sense to have to import it every time we want to use it.

**Comment by Alizter** [comment]
As in why not add it as an instance in Basics/Overture.v and get rid of UnivalenceImpliesFunext?

**Comment by mikeshulman** [comment]
Why not?  When we want to make use of any other theorem, we import the file in which it's proven.  Just think of "univalence implies funext" as a theorem and forget that it's technically an axiom.

**Comment by Alizter** [comment]
The problem I have is this. If A.v imports UIF, and then I import A, then I already have this. This means UIF starts from 20 different places in the library. I propose it starts from 1.

**Comment by Alizter** [comment]
Here is an example:
```coq
Require Import Basics Types.

Section bar.

Context `{Univalence}.

Fail Definition foo : Funext := _.

Require Import Connectedness.

Definition foo : Funext := _.
```
I think adding the contents of UnivalenceImpliesFunext in Types/Universe would be better than having to guess if it appears.

**Comment by mikeshulman** [comment]
This is no different from the behavior of any other typeclass instance.  If module (e.g. file) A declares an instance of typeclass `foo`, and module B imports module A, then any module that imports module B will be able to find that instance of `foo` through typeclass search, whether or not it explicitly imports module A.  One can argue that that's a bug or misfeature in Coq's handling of typeclass instances, but if so it's one we have to live with everywhere unless and until it's fixed, so I don't see any reason to treat UIF specially.

**Comment by Alizter** [comment]
Is there any reason to keep it in it's own file however? Why not prove it as early as possible so that you don't need to explicitly import UIF?

**Comment by Alizter** [comment]
Is there any reason to keep it in it's own file however? Why not prove it as early as possible so that you don't need to explicitly import UIF?

**Comment by mikeshulman** [comment]
The proof uses stuff from `Types`, so it can't go in `Basics`.

**Comment by Alizter** [comment]
So would it be ok in Types/Universe?

**Comment by Alizter** [comment]
OK I have decided to leave it alone since I am not convinced I understand what is going on. I will close this issue once I merge a PR where the Fail Checks are implemented. Thanks for you help @mikeshulman !

**Comment by mikeshulman** [comment]
It doesn't belong in Types/Universe because it's not a basic theorem about the universe.

I remembered why UIF has to be an axiom: it's because the typeclasses Funext and Univalence aren't technically the statements of those axioms but rather dummies, in a technical trick that makes them universe-polymorphic.  But this trick shouldn't interfere with the logico-mathematical structure of the library, namely that UIF is a theorem that, like other theorems, depends on previous results and is depended on by further results.
