### ISSUE TITLE
Quotient has the wrong universes

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1103]
In #1088 I tried defining `quotient` as a truncated coequalizer, which broke the rest of the library, notably V.v. I originally thought this was a problem with V.v, but I noticed after omitting it from the _CoqProject, other things break too.

A careful analysis of quotient.v led me to note that given a type A:U and a relation A -> A -> V, the quotient was living in U. There is the following comment in quotient.v which Jason wrote in #374 after noting that quotients had the wrong universe in #372.

`
Note: If we wanted to be really accurate, we'd need to put [@quotient A R sr] in the max [U_{sup(i, j)}] of the universes of [A : U_i] and [R : A -> A -> U_j].  But this requires some hacky code, at the moment, and the only thing we gain is avoiding making use of an implicit hpropositional resizing "axiom".
`

I made the following changes (I have omitted comments for brevity):
```coq
  Section Domain.

    Universe i j.

    Context {A : Type@{i}} (R:relation@{i j} A) {sR: is_mere_relation _ R}.

    Private Inductive quotient {sR: is_mere_relation _ R} : Type@{max(i,j)} :=
    | class_of : A -> quotient.
```
but as I said, V.v and other files rely on the quotient living in the same type as the one we are taking a quotient of in a crucial way.

Is I understand, with the way quotients are implemented in the HoTT book, unless propositional resizing is assumed, the truncated coequalizer definition doesn't seem to work. Funnily enough the HoTT book gives another definition of the quotient, as the set of equivalence classes, and makes careful note about its use of propositional resizing.

The HoTT book talks about using the Rezk completion as a third construction of the quotient. This however doesn't seem like it will land the quotient in the correct universe. Namely the universe of the type we are taking a quotient of.

- What is going on here?
- Am I correct in saying that unless we have propositional resizing, it is not immediate that quotient lives in the claimed universe?
- How can we fix this?

**Comment by JasonGross** [comment]
I think you must mean something other than #342; that was a small change to documentation of how to build HoTT.  Regarding `Type@{max(i,j)}`, I will note that at the time I wrote the comment, this was not valid syntax.  If it were, I probably would have used it.

> What is going on here?

Here is how I think of this: higher inductive types freely add path structure.  Since the path type lives in the same universe as the type of points, if you add paths that are too big for a smaller universe, you also need to enlarge the size of the base type.

> Am I correct in saying that unless we have propositional resizing, it is not immediate that quotient lives in the claimed universe?

That's correct.  Note in fact that having quotient land in the universe of the type you're quotienting should in fact be equivalent to hprop resizing: if you quotient Bool by the reflexive closure of the relation `fun _ _ => P` for `P` an hProp, and that quotient lives in Set, then the type of equality between the two inhabitants of this quotient type should be equivalent to `P` while living in Set.

I'll let someone else answer "How can we fix this?"

**Comment by Alizter** [comment]
@JasonGross Yes I meant #372 rather than #342.

**Comment by mikeshulman** [comment]
The max universe is the correct one (in the absence of prop-resizing), as Jason says, and it's what you'll also get from the truncated coequalizer, so I think the book is right.  I think the problem is with V.

**Comment by Alizter** [comment]
There are a few files in mathclasses that also rely on this universe arrangement. But I suppose @spitters knows more about this.

**Comment by spitters** [comment]
@andreaslyn is working on a monomorphization. This will likely make the problems in V.v more readable. 
About math-classes. Not sure which files you mean. @SkySkimmer may have written those files.

**Comment by Alizter** [comment]
@spitters natpair_integers and field_of_fractions.

**Comment by SkySkimmer** [comment]
I looked a bit at natpair, it doesn't seem like a fundamental issue. It's just that universes were optimised with the current version of quotients and such optimisation is sensitive to universe changes.

**Comment by Alizter** [comment]
@SkySkimmer Are the optimisations necessary?

**Comment by SkySkimmer** [comment]
Yes, before them I would get around 10k universes on later lemmas. It's possible to fix them, it's just annoying.

**Comment by Alizter** [comment]
The problem with V.v arises from being able to factor a map f : A -> B with A, B : U such that im f : U also. Currently, the quotient which lives in some universe above U, doesn't meet this criteria. However it ought to be true that there is some type T : U such that im f <~> T. This is exactly what something like the join construction achieves. Can we define an epi/mono factorization which lives in the correct universe without the join construction?

**Comment by Alizter** [comment]
Or maybe we can just use the (-1)-truncation factorization....

**Comment by mikeshulman** [comment]
> factor a map f : A -> B with A, B : U such that im f : U also.

There's no problem with doing that.  The (-1)-truncation factorization does it, as does the coequalizer of the kernel pair, regardless of issues with coequalizer.  The join construction is about factoring maps where B is in a *larger* universe but nevertheless "locally U-small".

**Comment by Alizter** [comment]
@mikeshulman I tried to manually (-1)-factor in monic_set_present but I couldn't get past universe restrictions. As I understand, V has two univereses i and j where i > j. The Au in monic_set_present should live in Type@{j} otherwise it doesn't work. Going through the proof, I cannot use any of the factorization stuff since they are two restrictive with the universes. I couldn't even manage to define the image manually.

**Comment by mikeshulman** [comment]
Sorry, maybe my last point was confusing.  I agree that in V.v we are in the situation solved by the join construction, where the codomain is larger, and that the (-1)-truncation alone won't do it.  I was just saying that your description that I quoted isn't what's going on here.

I do think that since all the types are sets, the coequalizer factorization should work here rather than having to recourse to the join construction.

**Comment by Alizter** [comment]
I am considering cleaning up quotient (as in continue #1088) but call it Quotient.v and put it in Colimits which Mike suggested in #1104. The new Quotient.v will be defined using a coequalizer and have some style changes to the functions in the file. I wish to leave quotient.v for now, since V.v depends on it in a way I can't seem to fix, and I don't want to drop support. In the future we should work on porting more files to use Quotient instead of quotient, after which we can finally drop the old one.

Currently changing V.v and the mathclasses files is a bit tedious, and I would like to get on with my other projects. Does anybody object to having two quotients?

**Comment by mikeshulman** [comment]
Hmm.  Why don't you make your Quotient.v and then maybe someone can figure out what's up with V.

**Comment by SkySkimmer** [comment]
I can fix hottclasses (it's not mathclasses btw) once the new quotient is in master.
