### ISSUE TITLE
Organising results about sets

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1104]
In the same spirit as #1067 I would like to start collecting results about sets in one place. Notably the files quotient.v, Card.v and V.v. I see this as a place to put future set theoretic results.

I am envisioning a place we can play around with large cardinal concepts, forcing, continuum hypothesis, etc. There are many results about what you can do and show with models of ZFC, which V.v is (almost?) an example of. It might be interesting to investigate in the future.

This is of course a suggestion, since I am not completely sure we should do this, but it would make for an interesting discussion. I don't think putting HSet.v here would be a good idea however.

**Comment by mikeshulman** [comment]
Why don't we wait on something like that until someone actually has definite plans to investigate such things?

**Comment by Alizter** [comment]
@mikeshulman That's why I created an issue not a pull request O:-)

**Comment by mikeshulman** [comment]
Ok, your phrasing suggested that you wanted to move quotient, Card, and V into a new directory now.  If not, then I suggest we close this issue until there's a reason to worry about it; we have too many open issues sitting around already that no one is doing anything about.

**Comment by Alizter** [comment]
Well I did want to do this, as part of an effort to clean up the HIT folder but since there is no real reason to do it now, I will close this issue.

**Comment by mikeshulman** [comment]
If you want to put stuff where it properly goes, I would say that `quotient` should be in `Colimits`, and `V` should be in `Spaces` along with `Card`.

**Comment by mikeshulman** [comment]
`epi` should really also go somewhere else...
