### ISSUE TITLE
Many hottclasses classes are properties rather than structures.

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1107]
In hottclasses we have many structures such as Group which I think should really be called IsGroup. If we wanted to talk about the type of groups, we would have to use the sigma type `sig Group` which isn't valid since `Group` needs other data too. I propose we rename some of these structures X to IsX in order to make this clear. If we want to discuss the type of Groups we would then have the appropriate total space `Group` which would consist of all the group data.

This would be more inline with the HoTT book too. A similar thing happens with pointed types, equivalences etc.

**Comment by mikeshulman** [comment]
That seems reasonable to me.

**Comment by spitters** [comment]
Seems reasonable.

from my phone
