### ISSUE TITLE
Better computationally behaved path_pmap?

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1111]
I want to prove the following:
```coq
Require Import Basics.
Require Import Types.
Require Import Pointed.

Local Open Scope path_scope.
Local Open Scope pointed_scope.

Definition foo `{Funext} {A B} {f : A ->* B}
 : (equiv_path_pmap f f)^-1 1 = {| pointed_htpy := apD10 1; point_htpy := concat_1p (point_eq f) |}.
Proof.
  cbn.
  apply ap.
  pointed_reduce.
  unfold ap10_path_forall.
  unfold apD10_path_forall.
  rewrite eisadj.
  
Admitted.
```

But the funext's get in the way and I quickly get lost trying to prove it. I want to also prove similar lemmas, such as path_pmap preserving concatenation etc. Currently the definition of path_pmap is a long string of equivalences which is fine but makes reasoning with quite difficult.

I have things I am trying to prove which have goals that look like the following:
```coq
ap bar (path_pmap H) @ path_pmap Q = path_pmap  {| pointed_htpy := apD10 1; point_htpy := concat_1p (point_eq f) |}
```
This is a made up goal, but you can see that if I had some lemmas allowing me to move around the path_pmaps, show that they preserve concatentation (i.e. `@*` to `@`) and commute with the phomotopy version of ap, then I can get rid of the path_pmaps.

Any ideas how to make path_pmap behave better, so that we can prove such things about them?

**Comment by mikeshulman** [comment]
I'm doubtful that there's any easy fix to this; it feels like one of those annoying path-algebra-wrangling issues that's intrinsic to Book HoTT.  One technique that I've had success with in the past for computations involving equivalence-chains is to manually prove a computation lemma for each step of the chain and then string them together at the end.  (For example, see the `codeglue*_pushl` lemmas in `BlakersMassey.v`.)

**Comment by Alizter** [comment]
@mikeshulman Thanks for pointing that out. It looks like I will have to carefully babysit the computations like you did for codeglue. Am I correct to think that funext is causing these issues? If so it is unfortunately, since it doesn't look like I can easily rid myself of its use.

**Comment by mikeshulman** [comment]
Yes, it's mainly funext, but more generally it's the fact that the characterizations of path-types and so on in `Types` are not definitional.

**Comment by mikeshulman** [comment]
Well, score one for optimism over pessimism: I just learned a new trick from Egbert that makes this lemma not just easy to prove but *true definitionally*!  See #1112.

**Comment by Alizter** [comment]
#1112 has been merged.
