### ISSUE TITLE
./etc/install_coq_deps.sh needs to be updated for 8.10

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1115]
We need to update `./etc/install_coq_deps.sh` as the dependencies of coq have changed. Notably coqide now compiles with gtk3. See coq/coq#9279.

I've also noticed that I still cannot compile coqide. There is something wrong with the configure scripts.

If I run ./configure in a clone of the latest version of coq (nothing to do with this library) I get:
```
LablGtk3 found (3.0.beta6), with native threads:
=> native CoqIde will be built.
```
As expected. However when trying to install coq using the `install_coq.sh` I get
```
LablGtk3 not found:
=> no CoqIde will be built.
```
which is very strange. So I don't think it is a problem with coq, but rather with the scripts in the library. This is also related to #1040. This appears to be the same issue but I am sure if we can get our configure script to detect gtk3, we will be able to compile coqide.

**Comment by spitters** [comment]
I may be misremembering, but I thought we removed the need to compile your
own coqide.
Hoqide is just coqide with a flag, isn't it?
https://github.com/HoTT/HoTT/blob/master/hoqide

**Comment by Alizter** [comment]
@spitters This is correct, but I ought to be able to compile coqide in the HoTT library. It is strange that coq inside of HoTT cannot detect gtk3 but coq outside of can.

One of the ways to install the library is to compile a special version of coq. This is the way I am using. This should also build a coqide which isn't working for me for some reason.

**Comment by Alizter** [comment]
I think what is needed is a way to reset the coq installation when we update coq. I think the trouble I am having right now is that the new version of coq isn't being used...
