### ISSUE TITLE
Travis doesn't restart when master gets changed

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1117]
In #1094 travis ran sucessfully but then master was changed. It did not come to mind that this had happened so it went ahead and merged. This caused master to fail on the main library. As I write this, this is being fixed in #1116.

To avoid such problems in the future ejgallego has suggested we use bors. [Here is a description of what it does](https://bors.tech/). I think this is worth discussing in detail to make sure master never fails to build again.

**Comment by mikeshulman** [comment]
It's an interesting idea, but I'm not sure that it's worth the effort.  This sort of thing happens quite rarely, and it's not like we're developing some enterprise mission-critical software; master failing to build is not the end of the world.
