### ISSUE TITLE
Travis can't build master

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1123]
I vacuously [pushed master on my fork](https://travis-ci.org/Alizter/HoTT/builds/608192137) and so far the travis build seems to be failing.

I got the same issue in #1122 too. At least I now know it has nothing to do with that PR.

This is the error:
```
make[1]: Leaving directory `/home/travis/build/Alizter/HoTT'
$ hoqtop
$ echo
Welcome to Coq 8.11+alpha (November 2019)
Error: Unable to locate library
Prelude with prefix Coq. (While searching for a .vos file.)
```

Weirdly not all the jobs fail, about half.

@JasonGross Do you know what might be causing this?

**Comment by JasonGross** [comment]
Presumably it has something to do with the recent PR that added .vos files to Coq.  Maybe somewhere we install .vo files but neglect to install or copy .vos files?  No idea what would make it occur only half the time...

**Comment by JasonGross** [comment]
Probably related to https://github.com/coq/coq/issues/11057#issuecomment-550377645

**Comment by Alizter** [comment]
@JasonGross By half I meant out of the 8 travis jobs, 3, 4and 7 fail.

**Comment by Alizter** [comment]
@JasonGross I take it this is happening because our makefile if from 8.10 but travis is using 8.11?

I would have thought that running travis on 8.11 is a bit risky since it is not the intended version of coq...

**Comment by JasonGross** [comment]
> By half I meant out of the 8 travis jobs, 3, 4and 7 fail.

Ah, yes, that makes more sense.  We aim to maintain compatibility with both the latest released version and also current master, though if at any point the burden becomes too much, we can tag a "this is the last commit that works with this released version of Coq" and then have master branch be compatible with only the latest unreleased version.

**Comment by Alizter** [comment]
OK we are currently on 4/8 travis builds after coq/coq#11075 was merged. Currently coqtop is still not happy with no .vos file. I am therefore reported this to the coq development: coq/coq#11153.

**Comment by Alizter** [comment]
OK so it turns out everthing is working fine with coq, it is just the coq daily builds that are not updated. @JasonGross will this just update tomorrow?

**Comment by Alizter** [comment]
This seems to have all been fixed now.
