### ISSUE TITLE
Stable opam release

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#1132]
Our current opam package is still in dev. (8.10.dev)
We should make a stable release.

https://github.com/coq/opam-coq-archive/tree/master/released

**Comment by Alizter** [comment]
I think it's `extra-dev` not `released`

[https://github.com/coq/opam-coq-archive/tree/master/extra-dev](https://github.com/coq/opam-coq-archive/tree/master/extra-dev)

**Comment by spitters** [comment]
I understand that proper releases are in release...

**Comment by Alizter** [comment]
OK, I misunderstood. I was pointing to where the hott package is, but I see you are pointing to where you want it to be.

**Comment by spitters** [comment]
@palmskog just reminded me about this issue.

**Comment by Alizter** [comment]
@palmskog Are you able to help me do a release? I would like to help, but I have very little idea what needs to be done to do a release for opam.

**Comment by palmskog** [comment]
@Alizter for most purposes, OPAM is simply a format for metadata about software releases, e.g., in the form of tarballs on GitHub (generated by using GitHub's release interface). The most recent HoTT OPAM definition I've seen is this one: https://github.com/coq/opam-coq-archive/blob/master/extra-dev/packages/coq-hott/coq-hott.8.10.dev/opam

Can you check whether those installation steps still make sense? And if you do a release on GitHub, will that release be for Coq 8.11 only or will more versions be supported?

**Comment by Alizter** [comment]
Our current release on github is for Coq 8.10.

I don't know if we will be doing a release for 8.11 yet.

The build instructions in the dev version still make sense to me.

**Comment by palmskog** [comment]
In this case, I suggest you adapt that OPAM file to the HoTT 8.10 release and do a pull request like the following one: https://github.com/coq/opam-coq-archive/pull/1132/files

**Comment by palmskog** [comment]
Also note that if you actually need `autoconf` to build the project, you need to add the following as a dependency: `conf-autoconf {build}`

**Comment by JasonGross** [comment]
Note that we now have [an 8.11 release](https://github.com/HoTT/HoTT/releases/tag/V8.11)
