### ISSUE TITLE
Clean up Finite.v

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1135]
I propose we split up Finite.v into a few files and do some code cleanup. Currently Finite.v is just over 1000 lines which is way too long for any file really.

I haven't yet got a plan for how exactly we will split it up, but I suppose it will have it's own folder `Finite` and `Finite.v` will become an index file for whatever is in that folder. Finite.v is already nicely sectioned so it shouldn't be too big a task.

While we are doing this we should add #1034.

In #1133 it was noticed that some proofs have some redundant steps from a time when typeclass search was dumber. I suggest we clean up these proofs too, and perhaps even document them while we are at it.

**Comment by mikeshulman** [comment]
Seems reasonable.

**Comment by andreaslyn** [comment]
Maybe split into a file with type Fin related results, and a file with class Finite related results.

**Comment by Alizter** [comment]
I think `Finite` should be renamed `IsFinite`.

**Comment by mikeshulman** [comment]
I suppose that would be the consistent thing to do.  Do you want to rename `Contr` to `IsContr` also?

**Comment by Alizter** [comment]
@mikeshulman I think it makes sense to rename `Contr` to `IsContr` given that's how it is named in the HoTT book. However there are some other things that need to be considered so I will keep it a separate issue. For example, do we really need `Contr_internal`?

**Comment by Alizter** [comment]
@mikeshulman Are you still OK with renaming Finite to IsFinite?

**Comment by mikeshulman** [comment]
Is there an argument for it?

**Comment by Alizter** [comment]
The type of finite types should be called `Finite`.

**Comment by mikeshulman** [comment]
Hmm... I'm not sure about that, wouldn't `FiniteType` be better?  Or `FiniteSet`?  The word "finite" is an adjective, not a noun.

**Comment by Alizter** [comment]
OK so arguments for:
 * It’s a prop so it fits with the naming scheme.
 Arguments against:
 * It’s two extra letters which can be annoying to type.

Eh I guess it is OK as it is. I will change my PR tomorrow.

**Comment by Alizter** [comment]
All right in #1230 I have changed IsFinite back to FInite.

**Comment by Alizter** [comment]
I'm closing this as I don't think it is an issue anymore. Feel free to reopen if anybody thinks otherwise.
