### ISSUE TITLE
Free groups

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1139]
I would like to construct the free group of a type A. I will probably need A to be a hset. The universal property of the free group F(-) will look something like this:

GroupHom(F(A), G) <~> (A -> G)

Now my plan for doing this is as follows:

 1. Define the free group of a set A as F(A) := Pi 1 (Susp (A + 1)). 
 2. Start with a group homomorphism h : F(A) -> G
 3. Promote this to the world of oo-groups using the classifying space construction: BF(A) -> BG, whereby it becomes a pointed map.
 4. Observe that B ( Pi 1 X) <~> ||X||_1 which can be proven using the truncated Whitehead theorem from the HoTT book. Hence we have a pointed map: Susp (A + 1) -> BG.
 5. Use the loop-susp adjunction to get a pointed map:  A + 1 -> loops BG, and observe that loops BG is pointed equivalent to G (pointed by identity element).
 6. Observe that pointed maps A + 1 -> X are equivalent to maps A -> X. So we are done.

So we can get a recursion principal from this definition of free group for "free". The work that needs to be done is as follows:

1. Prove the truncated Whitehead's theorem (The proof is in the book).
2. Prove an isomorphism : Pi 1 X -> G implies a pointed equivalence X -> B G.
3. Show that classifying spaces can turn groups into oo-groups.

I am making a note of this argument here so I don't forget it in the future, as of now I have a formalization of classifying spaces but nothing about B (Pi 1 (X)).

**Comment by mikeshulman** [comment]
It would be interesting to compare this route with the direct construction in Theorem 6.11.6 of the book.

**Comment by Alizter** [comment]
Yes, Kraus and Altenkirch give another HIT construction which is kind of in between the two in the book. From experimenting with the James construction, recursive HITs can be very painful to work with, and the classical method of reduced words is very technical.

It seems that this way of constructing the free group might be simpler to define and work with than all three. I guess we will see :-)
