### ISSUE TITLE
A dearth of pairs of eyes

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#1166]
I feel like the two-pairs-of-eyes rule isn't working very well.  In principle I still like having two people review each PR, and when it actually happens there is often useful feedback.  However, when it takes weeks or more for a PR to get a second pair of eyes on it, whereas one or two people are actively working on development and would like to merge stuff more often than monthly, I feel like the rule is getting in the way of progress.  I hesitate to propose simply scaling back to one pair of eyes, but can anyone think of a better solution?  Perhaps we could set a time limit of a few days, say, after which, if no one has expressed any reservations, a PR can be merged with one approval?

**Comment by Alizter** [comment]
It should also be noted that some changes are more in need of review than others. I would be more content if a "core" change, in Basics say, was reviewed properly than a change to a comment in some relatively unimportant file.

**Comment by SkySkimmer** [comment]
2 approvals is pretty heavy, we only require 1 for Coq and that's 
without dependent types saving us from doing total nonsense.

Gaëtan Gilbert

**Comment by Alizter** [comment]
What about 2POE within 3 (or some other amount of) days is enough for a merge. Otherwise 1 is enough.

**Comment by spitters** [comment]
Sorry I've too busy to keep up with your progress. Yes, please go ahead,
say after 2 days.

from my phone
