### ISSUE TITLE
Sphere induction

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1167]
How can we derive the dependent eliminator for sphere induction?

In Licata and Brunerie's paper on Pi n (S n), one of the important things they do is characterize what sphere induction should be. They introduce a notion of "loops over a loop" which allows them to specify "dependent n-paths".

The HoTT book partially manages to show that the suspension definition of the sphere and the HIT definition are the same using the loop-susp adjunction allowing the characterization of sphere recursion. But it is never shown that we have a dependent eliminator for the n-sphere.

I remember seeing a mailing list discussion about this a few months ago also.

It would be nice to collect some of those results here, especially since the PinSn paper is becoming less relevant due to being overshadowed by Freudenthal.

Defining this "dependent loop space" seems to be quite tricky. Here is a start I made on the rest:

```coq
Require Import Basics.
Require Import Types.
Require Import Pointed.
Require Import Homotopy.Suspension.
Require Import HIT.Spheres.

Local Open Scope pointed_scope.

Definition base {n : nat} : psphere n.
Proof.
  destruct n; exact North.
Defined.

Definition loop {n : nat} : iterated_loops n (psphere n).
Proof.
  induction n.
  { cbn.
    exact South. }
  Search pEquiv iterated_loops.
  apply unfold_iterated_loops'.
  revert IHn.
  apply iterated_loops_functor.
  apply loop_susp_unit.
Defined.

Notation pt := (point _).

(** Dependent iterated loops *)
Definition dloops (n : nat) {A : pType} (P : A -> Type)
  (p : iterated_loops n A) : pType.
Proof.
  induction n.
  + serapply Build_pType.
    - apply P, p.
    - simpl in *.
Admitted.

Context `{Funext}.

Definition psphere_rec {n : nat} (P : pType) (l : iterated_loops n P)
  : psphere n ->* P.
Proof.
  serapply Build_pMap.
  { revert P l.
    induction n.
    + intros P l.
      exact (Susp_rec pt l (Empty_ind _)).
    + intros P l.
      change (psusp (psphere n) -> P).
      serapply Susp_rec.
      1,2: exact pt.
      serapply (IHn (loops P)).
      apply unfold_iterated_loops'.
      exact l. }
  destruct n; reflexivity.
Defined.

Definition psphere_ind {n : nat} (P : psphere n -> Type) (b : P base)
  (l : dloops n P loop) (x : psphere n) : P x.
Proof.
Admitted.
```

**Comment by mikeshulman** [comment]
Why exactly do you want to collect results about a definition that is becoming *less* relevant?

**Comment by Alizter** [comment]
@mikeshulman Sorry, what is becoming *less* relevent is the proof of PinSn that Licata and Brunerie have. But there are things about sphere induction in that paper that might get forgotten as a result.

I don't think it is seriously known that the suspension definition of the sphere is equivalent to the HIT definition.

**Comment by mikeshulman** [comment]
But since the suspension definition is more easily seen to be correct semantically, and seems to always be easier to work with, is it worth messing around with the HIT one at all?

**Comment by Alizter** [comment]
I can't come up with a good reason other than it was mentioned in the book 0:-)

**Comment by mikeshulman** [comment]
I don't think that's a good enough reason.  (-:

**Comment by mikeshulman** [comment]
Can we close this?
