### ISSUE TITLE
`@h` notation is clashing

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1173]
We use the `@h` notation for horizontal square concatenation. It seems to be clashing with coq's parser however. Observe the following:

```coq
Require Import Basics Types.

Definition hello {X Y : Type} : Type := Unit.

Check hello.

Check @hello.

Require Import Cubical.

Check @hello.

(* Syntax error: [constr:lconstr] expected after 'Check' (in [vernac:query_command]). *)
```

I suppose we will have to lock away these notations (`@v` too) in some module...

**Comment by mikeshulman** [comment]
Hmm, or maybe use a different notation for square concatenation.  We already have `@@` for `concat2`, what about `@@h` and `@@v` (since squares are, of course, two-dimensional)?  Would those be less confusing to the parser?

**Comment by Alizter** [comment]
@mikeshulman I think I will probably get rid of the notation all together. I'm not sure we actually gain anything from it.

**Comment by mikeshulman** [comment]
It would admittedly be more useful if we could define a 2-dimensional notation.  (-:

**Comment by JasonGross** [comment]
I think you might be able to keep it if you make the notation `'@' h` or `@ 'h'` or something (look at what ssreflect does with `@id` or `@idfun` or something)

**Comment by JasonGross** [comment]
You could also try putting them in a custom entry
