### ISSUE TITLE
Remove unnecessery univalence in Quotient.v

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1182]
Is it possible to write in_class without univalence? I couldn't work this out.

**Comment by mikeshulman** [comment]
No, it isn't.

**Comment by Alizter** [comment]
Alright, then can we prove `class_of R x = class_of R y -> R x y`? Currently the proof changes `R x y` definitionally into `in_class (class_of R x) y` which can be transported along.

```coq
  Lemma related_quotient_paths : forall x y,
    class_of R x = class_of R y -> R x y.
  Proof.
    intros x y p.
    change (in_class (class_of R x) y).
    destruct p^.
    cbv; reflexivity.
  Defined.
```

The issue is that this requires univalence, and hence so does QuotientGroup.

**Comment by mikeshulman** [comment]
No, this requires univalence too.  But the only use of `path_quotient` in `QuotientGroup` is in the forwards direction, which is just `qglue` and doesn't require univalence.

**Comment by Alizter** [comment]
OK, cool. I also removed univalence from Quotient_rec2 where only funext is needed. This means we only need funext for quotient groups now.

**Comment by mikeshulman** [comment]
Any chance of removing funext too, by reshuffling the quotient inductions in a similar way to the multiplication on the circle?

**Comment by Alizter** [comment]
@mikeshulman Yes, I am currently doing that, it seems to be possible.

**Comment by SkySkimmer** [comment]
Quotients imply funext so not sure what the point would be.

**Comment by mikeshulman** [comment]
Yes, that's a reasonable point...

**Comment by mikeshulman** [comment]
oops.

Mightn't the definition of the multiplication on the quotient type compute better if it isn't defined using funext?

**Comment by Alizter** [comment]
I would have thought it would compute better too.

**Comment by SkySkimmer** [comment]
Does it not compute properly?

**Comment by Alizter** [comment]
Well not really. But when doing Quotient_rec we require the target to be a hset, which for function types typically needs funext. I think these proofs are still better since we still don't need to assume or prove funext.
