### ISSUE TITLE
Reduce clashes with Coq

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#119]
Where we have departed from Coq’s names (eg Unit, Empty, …), make our definitions *notations* for Coq’s own, for better compatibility.

A list of known clashes:
- `unit` (coq) vs `Unit` (HoTT)
- `Empty_set` (coq) vs `Empty` (HoTT)
- 'not A := A -> False` (coq) vs `not A := A -> Empty` (HoTT)

Questionable clashes:
- `identity` and `eq` (coq) vs `paths`

**Comment by andrejbauer** [comment]
I am closing this issue because it's old and nobody is going to do it.
