### ISSUE TITLE
More general issig?

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#1194]
@jdchristensen suggested that maybe a variety of the `issig` tactic could automatically prove more general equivalences between any pair of nested sigma-types and records that are essentially just iterated destructs and reshufflings.

**Comment by JasonGross** [comment]
Certainly this is doable, the question is whether or not it is efficiently doable, and how general you want to be.  (Do you want it to handle any association of sigma nesting?  Do you want it to handle the case when the most deeply nested component is itself a sigma that should not be destructed?)

**Comment by mikeshulman** [comment]
If I were trying to write it, I would probably start out trying to deal with any association but assume that all sigmas it encounters should be destructed.

**Comment by JasonGross** [comment]
You can write something like
```coq
Ltac apply_some_projection x :=
  exact x + apply_some_projection (pr1 x) + apply_some_projection (pr2 x).
```
to go from the sigma to the record (to be applied after econstructor or similar).  Then you can probably use just `apply x` to go the other way, maybe (or `destruct x; assumption`? At worst you'll need to destruct and then multimatch goal to write a multisuccess version of assumption)

**Comment by Alizter** [comment]
Do we essentially want it behaving like we put a record type in the middle of an equivalence between sigmas and issig can solve both sides by transitivity? There are probably more efficient ways of doing this.

**Comment by jdchristensen** [comment]
I don't think that would work.  My understanding is that `issig` expects the sigma type to be nested in a certain way with the fields in a certain order, and the idea here is to allow irregular nesting and order.  E.g. `{ y : { x : A & P x } & Q y.1 }` vs `{ x : A & { z : Q x & P x } }`.

**Comment by mikeshulman** [comment]
Here's a first try that seems to work reasonably well, at least on abstract type families.

```coq
(* Perform [intros] repeatedly, recursively destructing all
possibly-nested record types. *)
Ltac decomposing_intros :=
  let x := fresh in
  intros x; cbn in x;
  try (elim x; clear x);
  try decomposing_intros.

(* A multi-success version of [assumption].  That is, like
[assumption], but if there are multiple hypotheses that match the type
of the goal, then after choosing the first one, if a later tactic
fails we can backtrack and choose another one. *)
Ltac multi_assumption :=
  multimatch goal with
    [ H : ?A |- _ ] => exact H
  end.

(* Build an element of a possibly-nested record type out of hypotheses
in the context. *)
Ltac build_record :=
  first [ cbn; multi_assumption
        | unshelve econstructor; build_record ].

(* Construct an equivalence between two possibly-nested record/sigma
types that differ only by associativity and permutation of their
components. *)
Ltac make_equiv :=
  snrapply equiv_adjointify;
  decomposing_intros;
  [ build_record | build_record
  | reflexivity | reflexivity ].

Axiom A : Type.
Axiom B : A -> Type.
Axiom C : forall a:A, B a -> Type.
Axiom D : forall (a:A) (b:B a), C a b -> Type.

Axiom P : A -> Type.
Axiom Q : A -> Type.

Axiom R : A -> A -> Type.

Record Foo := { foo_a : A ; foo_b : B foo_a }.
Record Bar (f : Foo) :=
  { bar_c : C (foo_a f) (foo_b f) ;
    bar_d : D (foo_a f) (foo_b f) bar_c
  }.

Goal { ab : {a : A & B a } & { c : C ab.1 ab.2 & D ab.1 ab.2 c } }
     <~> { a : A & { bc : { b : B a & C a b } & D a bc.1 bc.2 } }.
  make_equiv.
Defined.

Goal { y : { x : A & P x } & Q y.1 }
     <~> { x : A & { z : Q x & P x } }.
  make_equiv.
Defined.

Goal { ab : {a : A & B a } & { c : C ab.1 ab.2 & D ab.1 ab.2 c } }
     <~> { f : Foo & Bar f }.
  make_equiv.
Defined.

Goal { fc : { f : Foo & C (foo_a f) (foo_b f) }
            & D (foo_a fc.1) (foo_b fc.1) fc.2 }
     <~> { a : A & { b : B a & Bar (Build_Foo a b) } }.
  make_equiv.
Defined.

Goal { y : { x : A & P x } & Q y.1 } <~> { x : A & (Q x * P x) }.
  make_equiv.
Defined.

Goal { x : A & { y : A & R x y } } <~> { y : A & { x : A & R x y } }.
  make_equiv.
Defined.

Goal { x : A & { y : A & R x y } } <~> { xy : A * A & R (fst xy) (snd xy) }.
  make_equiv.
Defined.
```

**Comment by jdchristensen** [comment]
Cool.  That also works on the example of Magma equivalences that motivated me to suggest it!  It runs in 0.025s on that simple example, which seems fine.

**Comment by mikeshulman** [comment]
Note that this doesn't completely replace `issig`.  I think it should work to prove `issig` lemmas if given their statements, but unlike `issig` it can't automatically deduce the sigma-type from the record type, which is a nice feature.  Probably if we put this tactic in the library then `issig` lemmas will become less important, but I expect they will still be useful e.g. when characterizing path-types of record types.

We should experiment with this tactic in the library and see how many places there are where it would be useful.  I wonder whether it could be enhanced to include contracting of based path-spaces, which is something that also often happens in chained sigma-equivalences proofs.

**Comment by mikeshulman** [comment]
I figured there was no reason for this tactic to adjointify, so I tried instead 

```coq
Ltac make_equiv :=
  snrapply Build_Equiv; [ | snrapply Build_IsEquiv ];
  decomposing_intros;
  [ build_record | build_record
  | reflexivity | reflexivity | reflexivity ].
```

But this makes the third `reflexivity` fail with `No applicable tactic`.  Applying the same tactics to all the same goals one by one works, so I don't know what's going wrong.  I messed around and found that the equivalent-looking definition

```coq
Ltac make_equiv :=
  snrapply Build_Equiv;
    [ decomposing_intros; build_record |
      snrapply Build_IsEquiv ];
    decomposing_intros;
    [ build_record | reflexivity | reflexivity | reflexivity ].
```

works on all the above examples, but in

```coq
Definition equiv_sigma_prod0 (A B : Type)
  : {a : A & B} <~> A * B.
```

the second `build_record` fails with `The term "A" has type "Type" while it is expected to have type "A".`  But the also apparently-equivalent

```coq
Ltac make_equiv :=
  snrapply Build_Equiv;
    [ decomposing_intros; build_record |
      snrapply Build_IsEquiv;
      [ decomposing_intros; build_record
      | decomposing_intros; reflexivity
      | decomposing_intros; reflexivity
      | decomposing_intros; reflexivity ] ].
```

works in all cases I've tried.  Anyone have any ideas what's going wrong and what the difference is?

**Comment by JasonGross** [comment]
I suspect the issue is that some of these tactics are single success, and the order matters when instantiating evars.

**Comment by mikeshulman** [comment]
How can i test that?

**Comment by JasonGross** [comment]
To understand: In particular, `a; b; [ c | d | e ]; f; g` gets parenthesized as `((a; b); [ c | d | e ]); f; g`, and first runs `a` on each goal in sequence (that's not actually accurate, it actually runs `a` on all the goals as a multigoal tactic, and the action of each primitive tactic as a multigoal tactic is to run on each goal in sequence), then ≈ runs `b` in each goal.  Then it runs `c` on the first remaining goal, then `d` on the next one, then `e` on the last run.  Then it ≈ runs `f` on each goal in sequence, and then ≈ runs `g` on each goal in sequence.

**Comment by JasonGross** [comment]
If you want to test goal ordering with printf-debugging, you can stick in a bunch of `match goal with |- ?G => idtac "now running this tactic on goal" G end` in various places

**Comment by mikeshulman** [comment]
In `[a | b]`, if `a` is multi-success, do failures in `b` backtrack into other successes of `a`?  And similarly, if `a` is run on all the goals as a multigoal tactic, do failures in its application to some goals cause backtracking into the results of its run on other goals?

**Comment by mikeshulman** [comment]
Is there a multi-success version of `try`?  I mean, such that if `try tac` succeeds but some later tactic fails, Coq will backtrack into not running `tac`?  (I'm guessing from the documentation that `try` itself does not behave that way, but that could be wrong.)  Would/could such a thing have to be written as something like

```coq
multimatch goal with _ => tac | _ => idtac end
```

?

**Comment by mikeshulman** [comment]
Oh, is that just `tac + idtac`?

**Comment by JasonGross** [comment]
> In [a | b], if a is multi-success, do failures in b backtrack into other successes of a?

Yes, but note that `[ a | b ]` without the `;` isn't a thing (the construction is `[ > a | b ]`)

> And similarly, if a is run on all the goals as a multigoal tactic, do failures in its application to some goals cause backtracking into the results of its run on other goals?

Yes, though there are subtle interactions, such as the fact that even if `a` has multiple successes, I believe `solve [ a ]` will have only one success (but `a; fail` can have multiple successes)

**Comment by JasonGross** [comment]
> Yes, though there are subtle interactions, such as the fact that even if a has multiple successes, I believe solve [ a ] will have only one success (but a; fail can have multiple successes)

The easiest tactic to see this with is `constructor`, btw.

> Oh, is that just tac + idtac?

Yes

**Comment by mikeshulman** [comment]
Grr... it's hard to debug tactics involving multisuccesses, since I can't step through `a; b.` by changing it to `a. b.` since then the backtracking is broken.

**Comment by JasonGross** [comment]
You might get some mileage from `Set Ltac Debug. Set Ltac Batch Debug.`

**Comment by mikeshulman** [comment]
Thanks.  Is there a way to get a nice readable output from those in PG?  The debug output is displayed quickly in the `*response*` buffer, but then replaced by the overall message once the ltac command completes, and then the only place I can find the debug output is in raw form in the `*coq*` buffer.

**Comment by mikeshulman** [comment]
Oh!  I can just leave off the "batch" and step through the execution exactly step by step.

**Comment by JasonGross** [comment]
Yep, that too.  You can also pipe it to a file running coqc on the command line, and then you can scroll through it
