### ISSUE TITLE
Capitalisation conventions

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#120]
Adhere better to our declared capitalisation etc. conventions: names of types should typically be capitalised, names of other objects should not be (including when they include names of types).

Also: DOCUMENT this (and other conventions) in the wiki!

**Comment by Alizter** [comment]
@mikeshulman Would you consider this done now? We haven't strictly completely moved over to the new quotient everywhere.

**Comment by mikeshulman** [comment]
Yeah.
