### ISSUE TITLE
Naming of trunc_sigma, trunc_forall etc.

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1226]
We have some old names for these lemmas. Wouldn't it make more sense for them to be called istrunc_sigma, istrunc_forall. Are there any others?

**Comment by mikeshulman** [comment]
Yes, it would.

A related question is what to do about lemmas like `(is)trunc_equiv`, which look like they are saying that `Equiv A B` is truncated but in fact say that truncatedness passes _across_ an equivalence.  This is an issue in RSU/modalities where we have `inO_equiv` saying the latter, and `inO_equiv_inO` for the former.
