### ISSUE TITLE
Rename Contr to IsContr

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1229]
This was discussed back in #1135. Also do we still need a separate Contr_internal?

**Comment by mikeshulman** [comment]
I'm no longer sure that this is right.  Why make ourselves type two extra letters?  With things like `IsEquiv` and `IsGroupHomomorphism` we need the `Is` to distinguish it from the type of such things, `Equiv` and `GroupHomomorphism`, but that's not the case here.

**Comment by Alizter** [comment]
I agree that for contractible types that there is little need for distinction. I suppose we can hear other peoples opinions on this as well.

One argument for would be to be more in line with the HoTT book.
