### ISSUE TITLE
Use SProp for Funext/Univalence dummies?

### ISSUE THREAD

**Issue by SkySkimmer** [HoTT/HoTT#1253]
ie instead of https://github.com/HoTT/HoTT/blob/fd6bb279b1fdb59b7d1994368f51929ee3049ee9/theories/Basics/Overture.v#L628
we could have `Funext : SProp`

This would mean that if we get multiple instances of Funext they will be convertible.

Not sure how useful that is though.

**Comment by spitters** [comment]
Before using SProp in HoTT, I'd like to see a proof that it can be interpreted in higher toposes.
I believe that's true, but it should be checked.

**Comment by SkySkimmer** [comment]
Does that matter for these dummy types?

**Comment by spitters** [comment]
No.
But the question is interesting to me :-)

**Comment by mikeshulman** [comment]
I can't think of a situation in which we would intentionally get multiple instances of Funext.  Do you have any in mind?

**Comment by SkySkimmer** [comment]
No

**Comment by mikeshulman** [comment]
Ok, well, I'm kind of inclined to wait until it's broke before trying to fix it.  But I'm certainly willing to listen if there's any actual advantage that would accrue from such a change.

**Comment by SkySkimmer** [comment]
OK, I guess someone will remember the idea if it becomes useful so let's close.
