### ISSUE TITLE
Move useful lemmas out of EquivalenceVarieties to Types and discourage its use

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1272]
All three `Varieties` files are a tricky problem, as on the one hand they contain a few useful lemmas -- e.g. just as `FunextVarieties` contains `contr_basedhomotopy`, `EquivalenceVarieties` contains `fcontr_isequiv` and `isequiv_fcontr`.   But on the other hand, a lot of their time is spent on "dead-end" results that are mainly interesting theoretically and aren't ever going to get used for anything in the rest of the library.  I guess one solution would be to move the useful lemmas into other files so that the Varieties files themselves never need to be imported elsewhere.

_Originally posted by @mikeshulman in https://github.com/HoTT/HoTT/pull/1271_

**Comment by Alizter** [comment]
We shouldn't have any `Require Import EquivalenceVarieties` in the library. If we do, that means the lemma's used are note so "dead-end" and thus should be moved into Types/Equivalences.v or somewhere similar.

**Comment by mikeshulman** [comment]
Maybe once we do this, we can move the Varieties files into a "dead-end subdirectory" to make it clear they shouldn't be imported.

**Comment by Alizter** [comment]
Are you thinking somewhere like Contrib?

**Comment by mikeshulman** [comment]
No, just maybe something like `theories/Metatheory`.
