### ISSUE TITLE
EquivGroupoids

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#1287]
What is this file for?  It doesn't seem to be used anywhere else.

**Comment by Alizter** [comment]
It was created in #703

**Comment by mikeshulman** [comment]
Thanks.  It sounds like it was originally intended for `Tactics/EquivalenceInduction`, but isn't actually used there now (nor is `EquivalenceInduction` used anywhere either).  Since we've found that it's generally better to avoid using funext, is there a reason to retain these funext-dependent lemmas?

**Comment by Alizter** [comment]
@JasonGross would probably know if he found them useful or not. I don't recall ever having used any of these lemmas.

**Comment by JasonGross** [comment]
I'd like to keep Tactics/EquivalenceInduction, but have no preference about EquivGroupoids.  If I ever found the lemmas useful, I've since forgotten the circumstances

**Comment by Alizter** [comment]
In that case let's move them into Contrib/Old. Since it is a contribution and it is old. If anyone really needs them in the future we can resurrect them.
