### ISSUE TITLE
Name equivalence lemmas consistently

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#1290]
@jdchristensen requested that we continue the practice of naming equivalence lemmas with `equiv_` prefix.  This seems reasonable to me; it would mean going back and changing the names again in the cubical library.  Or we could try a shorter prefix like `eq_`.

**Comment by Alizter** [comment]
Would it be acceptable to have a parsing only notation like `sq_tr` for when we mean `equiv_sq_tr`.

**Comment by mikeshulman** [comment]
Probably.  It might not even have to be parsing only -- I think Dan's main concern was to be able to find lemmas by grepping through the source code.

**Comment by Alizter** [comment]
In which case I agree. I think naming them properly would be a good idea. On top of that we will need to create a set of notations for lazy people like me.
