### ISSUE TITLE
V8.11

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1291]
@JasonGross What do we need to do to do a release for coq 8.11?

**Comment by JasonGross** [comment]
We need to:
1. Update the submodule to the latest released version of Coq 8.11 (probably the tag V8.11.0 or V8.11.1)
2. Update the readme / install docs to mention the correct version
3. Push a tag on the HoTT repo for V8.11
4. Update opam-coq-archive

**Comment by Alizter** [comment]
@JasonGross How do we do steps 3 and 4? Now that #1294 has been merged?

**Comment by JasonGross** [comment]
You can make a new tag at https://github.com/HoTT/HoTT/releases

**Comment by Alizter** [comment]
It wants binaries. Is there a way to do this through github? I have created a draft release.

**Comment by JasonGross** [comment]
To do step 4, make a PR to https://github.com/coq/opam-coq-archive which adds a folder to https://github.com/coq/opam-coq-archive/tree/master/extra-dev/packages/coq-hott ; you can use the 8.10 folder as a template for the 8.11 one

**Comment by JasonGross** [comment]
> It wants binaries. Is there a way to do this through github? I have created a draft release

Uploading binaries should be optional

**Comment by JasonGross** [comment]
I've updated the tag description to be "Tag for Coq version 8.11", to keep with the pattern of past tags

**Comment by Alizter** [comment]
@JasonGross Shall I keep you as the maintainer?

**Comment by JasonGross** [comment]
Sure, that's fine.  You can also switch it to yourself if you'd prefer, and you expect to be the one doing this again in 6--12 months or whenever.

**Comment by Alizter** [comment]
Here is the PR:
coq/opam-coq-archive#1193
