### ISSUE TITLE
Fix dependency graph generation

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1299]
Because there's [a separate dependency graph for every constant in the library](http://hott.github.io/HoTT/file-dep-graphs/).  It's currently broken, though, and we should fix that.

_Originally posted by @JasonGross in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjM2MTE1NDAyOnYy/pull_request_review_threads/discussion_

**Comment by Alizter** [comment]
@JasonGross What exactly needs to be fixed here?

**Comment by JasonGross** [comment]
Every page that http://hott.github.io/HoTT/file-dep-graphs/ links to is an error.  http://hott.github.io/HoTT/file-dep-graphs/hott-lib.svg is a 404, and every other file seems to be a red box with the text:
This page contains the following errors:
error on line 1 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.

**Comment by JasonGross** [comment]
I haven't dug into the cause of this at all
