### ISSUE TITLE
Update CI to check older versions of coq

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1301]
Two options:
1. Take the line that says something like FORCE_COQ_VERSION=master, and make a couple copies of that line in the matrix, replacing master with things like V8.11.0, V8.10.2, etc
2. Take the line that talks about the master-daily package, make a few copies of that line, and replace the package variables by the ones corresponding to other versions of Coq as in https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/coq.yml

_Originally posted by @JasonGross in https://github.com/HoTT/HoTT/pull/1294#issuecomment-598258463_

**Comment by peterlefanulumsdaine** [comment]
This seems very nice in principle, if it doesn’t cause too much increase in either the CI load, or friction for future contributions/maintenance.

Regarding the second of these: I guess we should have at least a rough policy on how hard we will try to maintain compatibility with previous versions.  E.g. something like:  As long as contributions can be easily kept compatible with older Coq versions, it’s good to do so; but if this would block or degrade a good contribution, then we are happy to let go of the backward-compatibility?
