### ISSUE TITLE
`make -k` fails when `make` succeeds

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#131]
I run `make` and it succeeds.  Then I run `make` again, and get no output.  Then I run `make -k`, and get `make: Target 'all' not remade because of errors.`.  I think `make` is confused, but I'm not sure why.

**Comment by ejgallego** [comment]
Is this still relevant @JasonGross . I think you should close.

**Comment by JasonGross** [comment]
I am not sure if this still happens, but I will close it as stale and reopen it later if someone runs into it.
