### ISSUE TITLE
Rename S1 to Circle

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1348]
I think it would be a good idea to distinguish between the names `S1` and `Circle`.

* We don't define S1 to be `S 1`. This *could* be confusing to users.
* HoTT vernacular typically denotes this type as the circle, so for new users of the library, searching circle might be more logical than S1.
* The name S1 gets cluttered. We might want to use it to denote the 1st sphere.

**Comment by peterlefanulumsdaine** [comment]
I don’t have strong feelings on this.  I wouldn’t quite see it as needing changing for my part, but if you want to change it then I don’t oppose that.

**Comment by mikeshulman** [comment]
Could we make a notation or definition alias so that both names could be found by search?
