### ISSUE TITLE
Rename QuotientGroup to grp_quotient

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1363]

**Comment by jarlg** [comment]
I'd just like to bring up what I asked [over at `GrpPullback`](https://github.com/HoTT/HoTT/pull/1361#discussion_r453347970), that it seems more common outside Algebra/ to capitalize type constructors (such as `Pullback`, `Coeq`, and so on). My reading of [STYLE.md on capitalization](https://github.com/HoTT/HoTT/blob/master/STYLE.md#capitalization-and-spacing) supports this. Or am I misreading?

**Comment by Alizter** [comment]
In general it would be sensible to name *types* this way, but since terms of Group aren't exactly types, I think the lowercase convention should be used. Also, the Algebra library is pretty new, so I haven't bothered to update the STYLE.md on this.

**Comment by mikeshulman** [comment]
This is an interesting gray area.  I initially incline more towards @jarlg's point of view: terms of `Group` aren't *exactly* types, but since they are coerced to types I would be inclined to name them similarly.  But I'm open to counterarguments.

**Comment by jarlg** [comment]
When you say "terms of `Group` aren't exactly types", do I understand correctly that you mean they're technically elements of a Record type in Coq? Because to me they _are_ types; Sigma-types specifically. My preference would be that the syntax reflects the theory, and gets the implementation out of my way. :)

The above falls apart if one really cannot forget about the implementation. If that's the case, I'd like to see an example!

Lastly, `Contr` is (notation for) a Class and `Equiv` is a Record-type. Not "exactly types" if I understood correctly, but still capitalized.

**Comment by Alizter** [comment]
No, I mean they do not become terms of the type `Type`. We have `Contr : Type -> Type` and `Equiv : Type -> Type -> Type`, so clearly these "are types". But given a group `G` we have `G : Group` even though it can be coerced to `G : Type` (where it is really the projection of G that is in Type). The point that I am trying to make is that `G` is not a type, so it shouldn't follow the naming conventions for types.

I'm not super zealous about choosing the lowercase convention. Whichever one we choose, the important thing is to be consistent. For example, would we write `GrpQuotient` or `QuotientGroup`?

**Comment by mikeshulman** [comment]
Right, `Group` is a type (specifically a sigma-type), as are `Contr` and `Equiv`; the question is whether we should regard *terms of `Group`* as close enough to "being types" for the capitalization convention to apply.  I tend to regard a term of `Group` (or a similar type) as "a type with extra structure".  But I'd be interested to hear if others have opinions.

**Comment by jarlg** [comment]
Thanks for explaining! I see bringing in `Contr` and `Equiv` wasn't pertinent. And thanks for the correction; I should have said groups have an underlying type (a set) above.

**Comment by jdchristensen** [comment]
I'd lean towards also capitalizing things that naturally coerce to type.  But I'm also fine with going with whatever is most prevalent currently in the library.

**Comment by Alizter** [comment]
Alright, then it seems everybody likes capitals for group names. What convention do we follow for naming groups?

**Comment by jdchristensen** [comment]
As an example, terms of type `hProp` are not literally types, but are types with a proof of `IsHProp`, and we capitalize those (e.g. `Unit`).

**Comment by mikeshulman** [comment]
I think you mean `Unit_hp`.

**Comment by jdchristensen** [comment]
Right!

**Comment by mikeshulman** [comment]
I guess `GrpPullback` would be more like `grp_pullback`, but `PullbackGrp` or `Pullback_Group` or something would be more like `Unit_hp`.  Do we want to put more emphasis on the fact that this is a group, or on the type that it "is" with a note afterwards that it happens to be a group?  Initially at least the latter seems more in line with the philosophy that leads to capitalizing groups...

**Comment by Alizter** [comment]
I think the following naming convention is sensible: `GroupWhatever`. I think only quotient groups look weird written like this `GroupQuotient` but it isn't that bad.

**Comment by Alizter** [comment]
I'm closing this issue since it doesn't seem it's worth pursuing.
