### ISSUE TITLE
Cleanup nat

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1367]
There are various places scattered throughout the library having to do with `nat`. I propose that we start collecting these in Spaces.Nat similar to how Spaces.Int is organized.

I recently had a look if it is possible to completely remove the coq stdlib, it seems to be the case but one of the stumbling blocks is nat. Currently various files (mostly in mathclasses) rely on Coq.Init.Peano and these lemmas need to be collected elsewhere in the main library and merged with existing results. For example, there are two different definitions of less than or equal to for naturals, and lemmas about those etc. Once this has been done, it will allow the transition from stdlib to no stdlib be much smoother.

One other thing that we can do is move the definition of `nat` into the main library and perhaps rename it `Nat` to fit with the library naming conventions.

**Comment by spitters** [comment]
https://github.com/HoTT/HoTT/issues/1424
