### ISSUE TITLE
Missing instance classifying the truncation of paths

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#137]
This instance should be inserted somewhere, though I'm not sure where, nor what to name it:

``` coq
Global Instance IsTrunc_path (A : Type) n `{H : IsTrunc (S n) A} (x y : A)
 : IsTrunc n (x = y)
  := H x y.
```

The key point is that Coq needs to know that it's an _instance_, rather than just knowing that it's true.  Here's a goal which can be automatically solved only with this instance, which came up in porting my category theory library:

``` coq
Goal forall (Object : Type) (Morphism : Object -> Object -> Type),
       (forall s d : Object, IsTrunc 0 (Morphism s d)) ->
       forall (x0 x1 : Object) (m m0 : Morphism x1 x0), IsTrunc 0 (m = m0).
  intros.
  eauto with typeclass_instances.
```

Tangentially, should HoTT/HoTT grow a `make check` and a test-suite, where we can put things like this, so we don't regress on the power of auto-inferring contractibility?  (I think that one of the essential features of a homotopy type theory library for Coq is the infrastructure to make proving truncation results painless.)

**Comment by Alizter** [comment]
@JasonGross @mikeshulman Has this been done? Your test case now runs.

**Comment by Alizter** [comment]
Should we close this issue now?

**Comment by mikeshulman** [comment]
Which test case(s) now run?

**Comment by Alizter** [comment]
@mikeshulman All except for the last one.

**Comment by Alizter** [comment]
And that is because the isset condition on morphism is unfolded. The following however works:

```coq
Require Import Basics Types.

Goal forall `{Funext} (Object : Type) (Morphism : Object -> Object -> Type)
     (Identity : forall x : Object, Morphism x x),
   (forall (s d : Object), IsHSet (Morphism s d)) -> IsHProp (Identity == Identity).
  typeclasses eauto.
```

**Comment by mikeshulman** [comment]
So what changed in the past 6 years to make the others work?

**Comment by Alizter** [comment]
Well the first and second work since we have an instance `istrunc_paths` in Overture. I the third one works because we also have an instance `trunc_forall`.

`istrunc_paths` has been an instance for the history of Overture.v which was created in Sep 2014.

**Comment by mikeshulman** [comment]
Ah, I bet it's `Hint Unfold pointwise_paths : typeclass_instances.` that made `trunc_forall` work for the third one.

Yes, let's close this.
