### ISSUE TITLE
`intuition` tactic is broken

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#138]
This is likely a known issue, but I figured I'd report it, because I didn't see anything.  The code

``` coq
Goal True.
intuition.
```

gives

```
Toplevel input, characters 0-10:
Anomaly: in tacticIn:
Incorrect tactic expression. Received exception is:
Anomaly: Uncaught exception Nametab.GlobalizationError(_, _). Please report.
```

**Comment by Alizter** [comment]
Since we are mostly avoiding coq in the main library now, I don't see how we can expect this to work. Is it really an issue anymore?

**Comment by spitters** [comment]
@andreaslyn and @mattam82 made a lot of progress on improving the relation with the ml code.
It might be easy to resolve now.

**Comment by Alizter** [comment]
Reading the coq tactic documentation, it says intuition has been completely engineered to use coq tactics rather than ml now...

**Comment by spitters** [comment]
That seems hopeful, as a lot of tactics have been made to work with HoTT.
