### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#1390]
I restarted it, but it's still failing, and I can't figure out why.  It looks like some package is missing when building Coq?

**Comment by SkySkimmer** [comment]
Coq now depends on zarith (opam package) so you need to install it in your CI script

**Comment by Alizter** [comment]
In short, coq switched from using an old bigint library to a new one which depends on zarith #11742. I will submit a fix to the CI today.

**Comment by Alizter** [comment]
In general, I am not too bothered with CI failings such as these as they depend on upstream changes. It is a given that coq/master will be unstable due to the nature of development.

I suggest that we allow the master job to fail since we only support the current release (which is now 8.12). We can configure the CI not to throw a red cross when it fails that job.

**Comment by JasonGross** [comment]
> I suggest that we allow the master job to fail since we only support the current release (which is now 8.12)

No, the contract of being on Coq's CI is that we maintain compatibility with the master branch of Coq.

We need to also install libzarith-ocaml on the CI, and it's possible that I need to update my packages to backport this package.

However, I believe it is also a bug in Coq's configure script that it does not detect

**Comment by JasonGross** [comment]
However, I believe it is also a bug in Coq's configure script that it does not detect a missing zarith package.

**Comment by Alizter** [comment]
I wasn't aware that we were on Coq's CI. When did this happen?

**Comment by JasonGross** [comment]
Before March 2017, according to https://github.com/coq/coq/commits/master/dev/ci/ci-hott.sh .  I could believe we've been there from the beginning of Coq's CI.

**Comment by Alizter** [comment]
Closed by #1392
