### ISSUE TITLE
Universal algebra

### ISSUE THREAD

**Issue by andreaslyn** [HoTT/HoTT#1415]
I have recently picked up universal algebra in HoTT again. I have rewritten most of the existing universal algebra stuff to support infinitary operations, and organized it in a folder theories/Algebra/Universal. Are there any objections to this rather drastic change of the universal algebra part of the library?

This time I am planning on adding some example instances of algebras, which will hopefully make it more accessible.

I have constructed the free algebra as a HIT, but the quotient algebra requires axiom of choice. I show [if the quotient always exists then the axiom of choice holds](https://github.com/andreaslyn/HoTT/blob/58aa9665dd98e9b63089b817b1f29226ebb305ae/theories/Algebra/Universal/quotient_implies_choice.v#L611), provided that the quotient `A/R` of algebra `A` by congruence `R` satisfies the universal property:

There is a surjective homomorphism `q : A -> A/R`, and for any homomorphism `h : A -> B` compatible with the congruence `R`, i.e. `R x y -> h x = h y`, there exists a unique homomorphism `f : A/R -> B` such that `h = f o q`:
```
     q
 A ----> A/R
  \     /
h  \   / !f
    \ /
     B
```
I have not been able to find this result elsewhere, and I am unsure whether it is reasonable to require the quotient map `q` surjective in universal algebra?

**Comment by mikeshulman** [comment]
I don't object to adding new material!  And reorganizing is usually a good thing; when you submit the PR everyone can give feedback on it.

Regarding quotients of infinitary algebras, have you read Blass's paper "Words, free algebras, and coequalizers"?

**Comment by andreaslyn** [comment]
I will be submitting PRs soon.

Thanks. Blass's paper is spot on what I was looking for!

**Comment by mikeshulman** [comment]
I would expect that with HITs (and without AC) one could construct quotients for which `q` is not necessarily surjective.  Does that seem right?

**Comment by andreaslyn** [comment]
I am not sure about when the quotient map is not necessarily surjective. Suggestions are very welcome! My attempt to construct the quotient A/R as a HIT is

1. the quotient map `q : A -> A/R`
2. identifications `R x y -> q x = q y`
3. an operation `op (A/R) : (Arity u -> A/R) -> A/R` for each operation symbol `u`
4. operation rule `op (A/R) (fun i => q (a i)) = q (op A a)` for `a : Arity u -> A`, where `op A` is the corresponding operation in `A`
5. Set truncation

I do not know how to construct the map out `f : A/R -> B`, given `h : A -> B` compatible with `R`.

First I tried with recursion:
Case 1 maps `x : A` to `h x`.
Case 2 holds because `h` is compatible with `R`.
Case 3 maps `b : Arity u -> B` to `op B b`, where `b` is given by recursion.
Case 4 I need `op B b = h (op A a)` without any relation between `a` and `b`, so I am stuck.

Then I tried with induction to construct
```
forall a : A/R, {b : B | merely (exists x : A, (a = q x) * (b = h x))}
```
which gives a chance to prove case 4, but now axiom of choice is needed for case 3!

So instead I attempted to show that axiom of choice is required for the quotient algebra. This is the case, if by quotient algebra we mean a coequalizer with surjective quotient map.

**Comment by mikeshulman** [comment]
> Case 4 I need `op B b = h (op A a)` without any relation between a and b, so I am stuck.

Shouldn't you need instead `op B (fun i => h (a i)) = h (op A a)`, which holds because `h` is an algebra map?

**Comment by andreaslyn** [comment]
Maybe I got the recursion principle wrong:
```
forall B : Type,
forall c : A -> B,
(forall x y, R x y -> c x = c y) ->
forall d : forall (u : Symbol), (Arity u -> A/R) -> (Arity u -> B) -> B,
(forall (u : Symbol) (a : Arity u -> A) (r : Arity u -> B), d u (fun i => q (a i)) r = c (op A a)) ->
IsHSet B ->
A/R ->
B
```

**Comment by mikeshulman** [comment]
Constructor (4) is non-recursive, so its corresponding clause of the recursor shouldn't involve any inputs in B.

**Comment by andreaslyn** [comment]
Right, I got it now! Thank you @mikeshulman
