### ISSUE TITLE
Makefile uses nonexisting coqdep option -nois

### ISSUE THREAD

**Issue by hendriktews** [HoTT/HoTT#1430]
In https://github.com/HoTT/HoTT/blob/8e83dd76fdb1a75036f99072bb648d5301e22ddc/Makefile.am#L231 and 3 other locations, the makefile invokes `coqdep` with `-nois`. AFAIK no coqdep version since 8.4.6 supported this option. You may want to limit coqdep invocations to existing options.

**Comment by Alizter** [comment]
Thanks for creating an issue. I was experimenting with changing some things in the makefile set up last year, where I noticed this also.
