### ISSUE TITLE
Fancier documentation

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#1435]
The [proviola docs](http://hott.github.io/HoTT/proviola-html/toc.html) are nice, but I wonder if we want more modern documentation.  For example, with [Alectryon](https://plv.csail.mit.edu/blog/alectryon.html), we could get pretty-printed MathJax displays:
![image](https://user-images.githubusercontent.com/396076/113332142-c92d6800-92ee-11eb-908e-ee02582d2880.png)

**Comment by spitters** [comment]
I think that would be nice. Proviola is showing it's age...
