### ISSUE TITLE
Notations conflicts

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#1437]
Since 23e7e0bec74f09faba384c8c825390e18d014f62, we can no longer write things like `@DHom`, because
https://github.com/HoTT/HoTT/blob/1a16cbb85d5781325c08881a9c78bae89297101d/theories/Basics/Notations.v#L175

Found while rebasing #1302 on master.  The workaround is to write `@ DHom`, but perhaps we want to reconsider the notation.

cc @Alizter , author of 23e7e0bec74f09faba384c8c825390e18d014f62

**Comment by Alizter** [comment]
Ah that's a shame, we can probably get rid of this notation.
