### ISSUE TITLE
Use coq_makefile in makefile

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1457]
We should switch to using the standard coq_makefile tool for building the library. This will make it easier to switch to a modern build system like dune in the future. And makes our library more homogeneous amongst other coq projects.

This already can be done, and is how the coq-platform release for HoTT is built.

**Comment by Alizter** [comment]
@JasonGross How might we go about doing this?

**Comment by JasonGross** [comment]
I think the first step is to set up a Makefile as in https://coq.github.io/doc/master/refman/practical-tools/utilities.html#building-a-coq-project-with-coq-makefile.  Then any targets that don't depend on variables defined in Coq's makefile can be defined in this Makefile, and any targets that do depend on the variables can be defined in the `.local` Makefile that gets included.  If you want help transferring over some targets to one of these Makefiles, let me know, and I can help out.

**Comment by Alizter** [comment]
OK so this seems to work:
```makefile
%: Makefile.coq

Makefile.coq: _CoqProject
	$(COQBIN)coq_makefile -f _CoqProject -o Makefile.coq


-include Makefile.coq
```

I think I will need some help untangling the targets from the `.am` script. @JasonGross do you have time for a meeting today?

**Comment by JasonGross** [comment]
You should not be including Makefile.coq, this is discouraged by the manual and also results in some of the rules being duplicated.  What's wrong with the template given in the reference manual?

**Comment by Alizter** [comment]
@JasonGross I wasn't sure what to do with `$(cqobin)` I now see where they come from. I took this template from coqprime as they also use the makefile.
