### ISSUE TITLE
Make nrefine and friends handle Funext and Univalence?

### ISSUE THREAD

**Issue by jdchristensen** [HoTT/HoTT#1483]
We should be using nrefine, nrapply and snrapply when they suffice, as they are faster and more predictable since they don't do typeclass search.  But a frequent annoyance when using them is having to manually handle trivial Funext or Univalence goals.  What if we change nrefine to:
```coq
Tactic Notation "nrefine" uconstr(term) := notypeclasses refine term; try match goal with
    | |- Funext  => exact _
    | |- Univalence => assumption
  end.
```
Then those trivial goals that are quick to handle would be solved for us.  (The reason to use `exact _` for Funext is that we may have Univalence in the context.)

With the above done, it becomes more pleasant to try to speed up existing code by adding the letter `n` in various places.  Of course, a bunch of existing code would need to have some `exact _` lines removed if the above is done, but I'm willing to do that.

**Comment by SkySkimmer** [comment]
Just use `exact _` for both, in case univalence comes from univalenceaxiom.

**Comment by mikeshulman** [comment]
That sounds good to me!

**Comment by jdchristensen** [comment]
Hmm, these tactics are defined in Basics/Tactics.v, where Univalence is not imported.  How to work around that?  With
```coq
(** Handle trivial goals generated by [notypeclasses refine]. *)
Ltac funext_univalence := try match goal with
    | |- Funext  => exact _
    | |- Univalence => exact _
  end.
```
I get `Error: The reference Univalence was not found in the current environment.`

**Comment by mikeshulman** [comment]
I believe the standard way to make a tactic "extensible" is to use a hint database.

**Comment by SkySkimmer** [comment]
Ltac has a tactic redefinition feature, so this might work (untested):

In Basics/Tactics.v:
~~~coq
Ltac nrefine_implem c := notypeclasses refine c.
Tactic Notation "nrefine" uconstr(c) := nrefine_implem c.
~~~
in Univalence.v:
~~~coq
Ltac nrefine_implem c ::= notypeclasses refine c; try match goal with
    | |- Funext  => exact _
    | |- Univalence => exact _
  end.
~~~
note the double colon.

**Comment by mikeshulman** [comment]
I kind of like the idea of a hint database, though, because it would then be easy to also add other "global axioms" in the files that declare them, like `PropResizing` and `ExcludedMiddle`.

**Comment by jdchristensen** [comment]
Any idea how the hint database idea would work?  Would I use `auto with databasename` instead of the above?

**Comment by jdchristensen** [comment]
Or is there a way to match these "global axioms" syntactically?  E.g. using the fact that they have no arguments, implicit or explicit?

**Comment by SkySkimmer** [comment]
auto seems too strong, it will look at arbitrary hypotheses.
eg suppose you're defining a `merely A -> merely A -> merely A` for some A, you do `nrefine (merely_ind ...)` and auto decides "well you've got a `merely A` right here"

**Comment by SkySkimmer** [comment]
You could have (untested)
~~~coq
Class IsGlobalAxiom (A:Type) := {}.

Ltac is_global_axiom A := let _ := constr:(_ : IsGlobalAxiom A) in idtac.
Ltac Tactic Notation "nrefine" uconstr(term) := notypeclasses refine term; try match goal with
    | |- G  => is_global_axiom G; exact _
end.

Instance funext_is_global_ax : IsGlobalAxiom Funext := {}.

**Comment by jdchristensen** [comment]
The approach using IsGlobalAxiom seems to be working.  Only three lines in the rest of library needed to be changed, which is either evidence that this isn't worth it, or that we are not using the `n` versions as much as we should.

On this line of Locator.v:
```coq
    Local Definition locsig : _ <~> locator' x := ltac:(issig).
```
there was a long error (I'll put it in a separate comment) that I fixed by changing `issig` to use `simple notypeclasses refine` instead of (the new) `snrefine`.

I added some things to silence warnings, but there's one left I don't know how to handle:
```
File "./theories/Basics/Tactics.v", line 382, characters 0-35:
Warning: The record IsGlobalAxiom could not be defined as a primitive record
[non-primitive-record,record]
```
Suggestions?  Here's what the code looks like now:
```coq
(** We keep a list of global axioms that we will solve automatically, even when not using typeclass search. *)
Class IsGlobalAxiom (A : Type) := {}.
Create HintDb global_axioms discriminated.
#[export] Hint Mode IsGlobalAxiom + : global_axioms.

(** We add [Funext] to the list here, and will later add [Univalence]. *)
Instance is_global_axiom_funext : IsGlobalAxiom Funext := {}.

Ltac is_global_axiom A := let _ := constr:(_ : IsGlobalAxiom A) in idtac.

Ltac global_axiom := try match goal with
    | |- ?G  => is_global_axiom G; exact _
end.

(** A shorter name for [simple refine]. *)
Tactic Notation "srefine" uconstr(term) := simple refine term.
(** A shorter name for [notypeclasses refine]; also handles global axioms. *)
Tactic Notation "nrefine" uconstr(term) := notypeclasses refine term; global_axiom.
```

**Comment by jdchristensen** [comment]
The error message generated by `issig`:
```
HOQC theories/Analysis/Locator
File "./theories/Analysis/Locator.v", line 162, characters 56-61:
Error:
In environment
Q : Type
Aap : Apart Q
Aplus : Plus Q
Amult : Mult Q
Azero : Zero Q
Aone : One Q
Aneg : Negate Q
Arecip : DecRecip Q
Ale : Le Q
Alt : Lt Q
U : RationalsToField Q
Qrats : Rationals Q
Qdec_paths : DecidablePaths Q
Qtriv : TrivialApart Q
Trichotomy0 : Trichotomy lt
F : Type
Alt0 : Lt F
Ale0 : Le F
Aap0 : Apart F
Azero0 : Zero F
Aone0 : One F
Aplus0 : Plus F
Anegate : Negate F
Amult0 : Mult F
Arecip0 : Recip F
Ajoin : Join F
Ameet : Meet F
Forderedfield : OrderedField F
Fabs : Abs F
Farchimedean : ArchimedeanProperty Q F
Fcomplete : IsComplete Q F
Qroundup : RoundUpStrict Q
H : Funext
H0 : Univalence
Q_eq : nat <~> Q
QQpos_eq : nat <~> Q * Qpos Q
cast_pres_ordering : StrictlyOrderPreserving qinc
qinc_strong_presving : IsSemiRingStrongPreserving qinc
x : F
u : Univalence
Unable to unify "Univalence" with
 "{H1 : forall q r : Q, q < r -> DHProp &
  {_ : forall (q r : Q) (nu : q < r), H1 q r nu -> ' q < x &
  forall (q r : Q) (nu : q < r), ~ H1 q r nu -> x < ' r}}".
```

**Comment by SkySkimmer** [comment]
>`#[export] Hint Mode IsGlobalAxiom + : global_axioms.`

Should be global not export.

**Comment by SkySkimmer** [comment]
Also remove all the hint db stuff.

**Comment by SkySkimmer** [comment]
Also should the hint mode should be in the typeclass_instances db, not some random db.

**Comment by jdchristensen** [comment]
Thanks, done.  I'm still getting the warning about a primitive record.

**Comment by SkySkimmer** [comment]
Just unset primitive projections around it.
