### ISSUE TITLE
Improve install instructions

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1485]
With #1476 we now have a much simpler install process. The documentation was updated but I think it can be made much more concise. In particular we should deprecate use of the coq submodule in favour of using opam. Eventually this will let us remove the coq submodule completely #1456.

Installing opam and coq have standard processes for each operating system, and we should point to those instructions. For compiling the HoTT library there isn't much left to do apart from running make.

We can also mention that we have opam releases and that users of the library may prefer to install those rather than building from github.

**Comment by mikeshulman** [comment]
I think you mean "deprecate".  (-:

**Comment by Alizter** [comment]
@mikeshulman Thanks! I apprecate it! 0:-)

**Comment by jdchristensen** [comment]
The install instructions say:
```
You can load the library from your Coq files with

Require Import HoTT.HoTT.
```
But with hoqtop gone, the above no longer works without some additional set-up when trying to edit a file outside of the library.  What's the recommended way to proceed?  Do I need to create a _CoqProject file each time I experiment with /tmp/foo.v? Or maybe the hoqtop wrapper would still be useful?  Then I just set `coq-prog-name` and am done.

**Comment by Alizter** [comment]
You need to write:

`From HoTT Require Import HoTT.HoTT`.

**Comment by JasonGross** [comment]
> You need to write:
> 
> `From HoTT Require Import HoTT.HoTT`.
> 
> this is of course if HoTT is installed somewhere, i.e. with opam.

No, you don't need this.  You can choose between `Require Import HoTT.HoTT` and `From HoTT Require Import HoTT`.

> What's the recommended way to proceed? Do I need to create a _CoqProject file each time I experiment with /tmp/foo.v?

If you're building on top of the HoTT library, you should install it into user-contrib with `make install` or via opam.  If you are building your project on top of a development version of the library that you are working on at the same time, you should use dune or else make a symlink with `ln -s /path/to/HoTT/theories /some/directory/HoTT` and then do `export COQPATH="/some/directory/${COQPATH:+:}${COQPATH}"` to add that directory to COQPATH.

**Comment by JasonGross** [comment]
If you are just experimenting, you should just create your temporary file in the HoTT repo.

But I think the larger point here is that there's no difference between HoTT and any other Coq library in this area.

**Comment by jdchristensen** [comment]
Ok.  Still, the install instructions could use some clarification on this point...  I'll probably either set the appropriate emacs variables in my .v files, or keep a version of hoqtop around for my own use.

**Comment by jdchristensen** [comment]
One also needs to pass `-noinit` (and maybe more) to `coqtop`, which is different from when using other Coq libraries.  One thing that works in Proof General is to set `coq-project-filename` to path for the `_CoqProject` file from the HoTT library.

**Comment by Alizter** [comment]
@jdchristensen You can also have your own _CoqProject file with the correct arguments in the directory you are working in.

**Comment by Alizter** [comment]
I completely forgot that I opened #1459 last week...
