### ISSUE TITLE
Build noisier after Makefile changes?

### ISSUE THREAD

**Issue by jdchristensen** [HoTT/HoTT#1487]
There's lots of stuff in console now while building.  Maybe these are things that we should fix anyways?  If not, then I'd prefer to silence them somehow, as they make me think I've introduced a problem...

I filtered out the COQC lines, and this is the extra stuff:

```
NaiveFunext
     : Type
NaiveNondepFunext
     : Type
WeakFunext
     : Type
@Univalence_implies_FunextNondep : Univalence_type -> NaiveNondepFunext
     : Univalence_type -> NaiveNondepFunext
ExtendableAlong_Over
     : forall (n : nat) (A B : Type) (f : A -> B) 
       (C : B -> Type),
       (forall b : B, C b -> Type) -> ExtendableAlong n f C -> Type
ooExtendableAlong_Over
     : forall (f : ?A -> ?B) (C : ?B -> Type),
       (forall b : ?B, C b -> Type) -> ooExtendableAlong f C -> Type
where
?A : [ |- Type]
?B : [ |- Type]
fun X : Type => idem_idmap X : Idempotent X : Type
     : forall X : Type, Idempotent X
Susp nat : Type0
     : Type0
1 : Lift nat
     : Lift nat
lift'
     : ?A -> Lift' ?A
where
?A : [ |- Type]
lower'
     : Lift' ?A -> ?A
where
?A : [ |- Type]
isequiv_lift'
     : forall T : Type, IsEquiv lift'
fun A : Type => ispointed_susp : IsPointed (Susp A)
     : forall A : Type, IsPointed (Susp A)
ispointed_susp
     : IsPointed (Susp Type)
ispointed_susp
     : IsPointed (Susp Type0)
{_ : Unit & {_ : Unit & Unit}}
     : Type
prod_rect
     : forall (A B : Type) (P : A * B -> Type),
       (forall (fst : A) (snd : B), P (fst, snd)) -> forall p : A * B, P p
```

**Comment by JasonGross** [comment]
If you pass `TIMING=1` this (along with timing information) gets redirected to timing files.  We were previously hardcoding this setting to on.  We can turn it back on by default by adding `TIMING ?= 1` to the local makefile, or we can silence the output but adding something like `Redirect "log"` before the offending commands

**Comment by jdchristensen** [comment]
Maybe it's best to hide this kind of output only when we expect it, so that we see when other changes cause unexpected output?

**Comment by Alizter** [comment]
I'll submit a change soon that `TIMING=1` becomes the default again, just like before.

I am however getting warnings from coq about the native-compilation options.

```
Warning: Native compiler is disabled, -native-compiler ondemand option
ignored. [native-compiler-disabled,native-compiler]
```

Shall we disable this warning @JasonGross?

**Comment by jdchristensen** [comment]
For at least some of these checks, which are designed to ensure we get the expected number of universe variables, we can instead do something like: `Local Definition CheckNaiveFunext := NaiveFunext@{i j max}.`  This is silent, but still gives an error with the wrong number of universe variables.

Maybe we can try the `Redirect "log"` method for anything that can't be silenced in this way?  But how do we avoid cluttering up the filesystem with these "log.out" files?  We could use `Redirect ".log"` to at least make them hidden by default.

IMO, it would be better to have the output not show up anywhere, but `Redirect "/dev/null"` doesn't work, because Coq adds ".out".  Maybe a wishlist item for Coq would be to accept something like `Redirect None ...`?

I forgot that I also filtered out timing lines, like `Finished transaction in 1.35 secs (1.337u,0.011s) (successful)`.  For some reason, there were only 10 of them in my test.  Can this or some other method also get rid of the timing lines?

**Comment by Alizter** [comment]
I dislike having to write `Local` definitions for checks as we still end up polluting the namespace.

The change proposed in #1491 should revert the output back to before the makefile changes.

This is really an issue in coq where we don't have enough control on the message passing of `coqc`. This is something I brought up with @ejgallego a while back.

**Comment by jdchristensen** [comment]
It can also be done as a `Goal` which avoids polluting the namespace:
```coq
Goal Type. exact NaiveFunext@{i j max}. Qed.
```

BTW, there are also these lines in the output:
```
*** Warning: in file theories/Basics/Notations.v, declared ML module ltac_plugin has not been found!
*** Warning: in file theories/Basics/Overture.v, declared ML module number_string_notation_plugin has not been found!
```

**Comment by Alizter** [comment]
>BTW, there are also these lines in the output:

That is a bug with coqdep coq/coq#11026

**Comment by SkySkimmer** [comment]
Goal is the same as `Lemma Unnamed_thmXXX` where XXX is nothing or some number to make it a fresh name.
If you don't want to define something you can do the somewhat ugly `Fail Fail Definition test := ...`

**Comment by jdchristensen** [comment]
I'm happy with any of `Local Definition ...`, `Fail Fail Definition ...` or `Redirect ".log" Check ...`.  The latter is maybe the cleanest.

Does `Let` also pollute the namespace?

**Comment by JasonGross** [comment]
> Does `Let` also pollute the namespace?

If you wrap it in a `Section` then it does not.

**Comment by ejgallego** [comment]
> This is really an issue in coq where we don't have enough control on the message passing of `coqc`. This is something I brought up with @ejgallego a while back. Here is the relevant issue: [coq/coq#12923](https://github.com/coq/coq/issues/12923)

Actually I did quite a bit of progress, including submitting the first PR; there are a few things to discuss with the other devs before fully implementing what we discussed, I've added the topic to the next Coq Call https://github.com/coq/coq/wiki/Coq-Call-2021-04-28 , so @Alizter if you can be around that'd be great.

**Comment by ejgallego** [comment]
> That is a bug with coqdep [coq/coq#11026](https://github.com/coq/coq/issues/11026). Not much we can do about those. The issue is that the `-noinit` file which is relatively new confuses coqdep somewhat. AFAIK these are harmless.

Note that `-noinit` is a noop for `coqdep`; what it is happening here is that likely Coq is not installing the `.mlpack` file, so that is a separate bug from the one you pointed out IMHO. So there are two things to do, one immediate, and one in the medium term:

- `.mlpack` files for coq plugins should be installed so coqdep doesn't complain when referencing a plugin
- `coqdep` should stop relying on `.mlpack` files to be present in plugin dirs, once we have a bit better setup of Coq Plugins as standard OCaml libraries.

**Comment by jdchristensen** [comment]
I plan to go ahead and make a PR that uses `Redirect ".log"`.  But why is that timing information produced for some files, and can it be suppressed?

**Comment by ejgallego** [comment]
I don't recommend using `Redirect` in Coq's source files, it is very likely we remove that command as it has several security problems, and doesn't play very well with some kind of sandboxed builds [not to say IDE envs that definitively won't allow Coq to touch the fs in uncontrolled ways]; instead, redirection of output from the build system is recommended, until the better output control is implemented upstream.

**Comment by Alizter** [comment]
@jdchristensen The timing information in some files comes from the `Time` command which produces output just like `Check.

**Comment by jdchristensen** [comment]
Oh, why are those `Time` commands there?  I suggest that we remove them.  And based on @ejgallego 's comment, my next proposal is to use a `Local Definition` instead of the `Check`.

**Comment by jdchristensen** [comment]
I see that `Goal ... Abort.` is used elsewhere in the library.  This might achieve all requirements.
```
Goal Type. exact NaiveFunext@{i j max}. Abort.
```

**Comment by Alizter** [comment]
@jdchristensen I don't understand why you want to get rid of `Time` and `Check`. I don't see using `Check` as bad practice. And now that #1491 has been merged, you shouldn't be able to see any of these, just like before the `coq_makefile` change.

**Comment by jdchristensen** [comment]
In principle, I don't like redirecting build output, as it could hide something that we should see, and I like builds to be intrinsically clean.  Since it only takes minor changes to avoid the output, I don't see why we shouldn't make those changes.  But if others disagree, it's not a big deal to me.

**Comment by Alizter** [comment]
Actual warnings and errors are always outputted however. In the future we will have better control over all the output, but for now I think this is the best option.

**Comment by jdchristensen** [comment]
I'll just close this, as it doesn't matter much and there wasn't much support for the idea.
