### ISSUE TITLE
make_equiv getting confused

### ISSUE THREAD

**Issue by jdchristensen** [HoTT/HoTT#1506]
The following works fine:
```coq
Definition good : pType <~> { X : Type & X}.
make_equiv.
```
But the following fails:
```coq
Definition bad (Y : pType): pType <~> { X : Type & X}.
Fail make_equiv.  (* No applicable tactic. *)
```
Somehow, the extra `pType` in the context causes a problem, and the backtracking search doesn't find a valid proof.  And while this example is contrived, this came up in practice in a deeply nested equivalence that should be easy for `make_equiv` but  is tedious to do manually.  Is there an easy workaround?

**Comment by jdchristensen** [comment]
I should say that in my real example, the `Y` appears on both sides of the goal, so I can't just clear it from the context.  It would be nice if I could "hide" something in the context, so that tactics that search through the context don't find it...

**Comment by mikeshulman** [comment]
Huh.  If you debug it, can you see what's going wrong?  I would have expected the backtracking to deal with this.

**Comment by jdchristensen** [comment]
The tactic comes up with the correct map from left to right, but for the map from right to left it chooses the constant map at `Y`.  Then it moves on to trying to prove that one composite is the identity, which of course fails, and then the tactic gives up.  Could it be that it doesn't backtrack through the different goals generated by the `simple notypeclasses refine (equiv_adjointify _ _ _ _)`?

Or maybe it's because of the `first` here:
```coq
Ltac build_record :=
  first [ cbn; multi_assumption
        | cbn; unshelve econstructor; build_record ].
```
since first doesn't do backtracking.  That definitely seems like a problem, and I'm surprised that it works as often as it does!

**Comment by jdchristensen** [comment]
Yes, using `+` instead of `first` makes this and other goals provable.  Another example that fails with the current approach:
```coq
Definition test2 (X : Type) (xy : X * X): X * X <~> X * X.
```
I'll check whether adding that backtracking slows anything down in the library build.  If not, I'll submit a PR.  If anyone has suggestions for places where the new `make_equiv` or one of its variants might now solve something in the library, let me know and I'll try it out.
