### ISSUE TITLE
Mechanisation of GCH -> AC

### ISSUE THREAD

**Issue by dominik-kirst** [HoTT/HoTT#1520]
Mostly during the HoTT Spring School, Felix Rech and I have ported our Coq mechanisation (cf. [CPP'21 paper](https://popl21.sigplan.org/details/CPP-2021/23/The-Generalised-Continuum-Hypothesis-Implies-the-Axiom-of-Choice-in-Coq)) of the result that the generalised continuum hypothesis (GCH) implies the axiom of choice (AC) to the HoTT library. The code is available [here](https://github.com/dominik-kirst/sierpinski-hott) and @spitters suggested to open an issue to discuss whether this development is of interest for the HoTT library. 

To provide some background, the result was first proven by Sierpinski for classical set theory, which we compared to the natural translation to Coq's type theory in our paper. This translation of set theory into type theory requires extensionality and unique choice, so it appeared worthwhile to compare the existing mechanisation to a version in HoTT.

We assume GCH as `forall X Y : hSet, infinite X -> hinject X Y -> hinject Y (X -> hProp) -> hinject Y X + hinject (X -> hProp) Y`, where `infinite X` denotes the existence of an injective function `nat -> X` and `hinject X Y` denotes the mere existence of an injective function `X -> Y`, and show the formulation of AC as `forall (X Y : hSet) (R : X -> Y -> hProp), (forall x, hexists (R x)) -> hexists (fun f => forall x, R x (f x))`. Already a weaker formulation of GCH (not yielding a case distinction) implies LEM and therefore also propositional resizing, so we freely assume both where necessary.

The development consists of three files:
- `Ordinals.v` contains a basic theory of (constructive) ordinals as developed in the HoTT book. It closes with a construction of the Hartogs number for a given hSet, which is an ordinal of not smaller but still controlled cardinality.
- `Sierpinski.v` contains a proof that any hSet embeds into its Hartogs number using GCH.
- `Results.v` contains the main result GCH -> AC, as well as the implications WO -> AC, GCH -> LEM, and LEM -> propositional resizing.

I'm looking forward to your thoughts and would also be curious to discuss a few more questions I gathered during this project :)

**Comment by mikeshulman** [comment]
I would love to see this incorporated into the library, not just for the result but for the general theory of ordinals that might be useful for other work.  And I'd be interested to hear and discuss your questions too.

**Comment by dominik-kirst** [comment]
> I would love to see this incorporated into the library, not just for the result but for the general theory of ordinals that might be useful for other work.

Okay, then I will have a look at the style guideline and file a PR soon :)

> And I'd be interested to hear and discuss your questions too.

Regarding the formulation of GCH, what would be the interpretation of the statement without truncated existentials, rendering it not as a proposition? Would this still be consistent? If one further drops the restriction to sets, I guess the statement will surely become inconsistent (as it should imply the inconsistent generalisation of AC to arbitrary types)? Also, is it known if a more constructive version of GCH implies a more constructive version of AC/WO, for instance in the form that every set admits an extensional and well-founded order (which I assume does not yet imply LEM)?

And on the technical side, it was a bit cumbersome to work with the impredicative power set operation relying on resizing by hand. Is it a known issue that evaluation (at least with `cbn`) is very slow for terms using resizing? Related to this, would it be possible to use Coq's impredicative Prop universe as logic layer and as a target for propositional resizing with elimination allowed for all hprops? Then mechanising impredicative constructions would be much easier.

**Comment by mikeshulman** [comment]
Unfortunately, I don't know the answers to any of those questions.  (-:

**Comment by dominik-kirst** [comment]
I've now filed #1533 as suggested.

**Comment by dominik-kirst** [comment]
> Unfortunately, I don't know the answers to any of those questions. (-:

We've now recorded these questions in a [short abstract](https://github.com/dominik-kirst/sierpinski-hott/blob/master/tex/abstract.pdf) that also contains a proof outline and a comparison to the previous Coq mechanisation.

**Comment by Alizter** [comment]
Since we have merged #1533 I am closing this issue. Feel free to reopen if you feel otherwise.
