### ISSUE TITLE
Further stratify cells and coherence in wildcat library

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1545]
I have a few arguments on paper using wildcats that I would like to formalise. Some of these require 3-cells for example, but not much coherence at all. Currently we only have Is21Cat providing these cells, which has a lot more coherence than what I need it for. There is also the question of how to organise the coherence data, but I think for Is21Cat, all or nothing is sufficient.

I am therefore proposing we stratify (at least) the cells of a wildcat as `IsGlob`, `Is1Glob`, `Is2Glob` etc. I know it is possible to do this for a general `n` but I don't really see it as a useful thing to do right now. I know Mike is experimenting with having all cells up to oo with coinductive types, but there are a few more things to be worked out there.

What I am proposing is intending to make the wildcat library a bit more immediately useful.

**Comment by mikeshulman** [comment]
Sure.
