### ISSUE TITLE
Update Algebra/Groups/FreeGroup/LoopSusp.v and add it to Groups.v

### ISSUE THREAD

**Issue by jdchristensen** [HoTT/HoTT#1549]
As discussed in #1548, the LoopSusp.v file should be exported by Groups.v (or maybe FreeGroup.v), so it is (indirectly) exported by HoTT.v and built when HoTT.vo is built.  But before doing this, it would be good to get rid of the name clash between FreeGroup here and in the ListQuotient.v file.  There may also be other name conflicts that should be handled.

(Note that ListQuotient.v is exported by FreeGroup.v, so it is indirectly exported by HoTT.v.)

**Comment by Alizter** [comment]
If we Export LoopSusp.v inside FreeGroup.v before ListQuotient.v then the conflicting names in LoopSusp.v should be qualified with `LoopSusp.`.

**Comment by jdchristensen** [comment]
That's one option, but I'd prefer to have distinct names.  With the current setup, if some file Imports LoopSusp at the top, I won't be able to tell while reading parts further into the file that FreeGroup refers to the non-standard choice.  This is a very theoretical concern in this instance, but I think it's just good practice to avoid conflicting names.

**Comment by Alizter** [comment]
One advantage of doing things this way is that we can swap the implementation easily in the future. Since the names exported by the module would be standard, by simply changing the order, we can change which implementation of free groups is being used.

However I am fine with changing the names for now, since I don't have any plans to actually finish LoopSusp.v anytime soon.

**Comment by mikeshulman** [comment]
As I said in the discussion of integers, I think swappability of definitions is a cute theoretical thing but not really worth it in practice.  We already have the predicate `IsFreeGroup`, so any development that's insensitive to definitions can just use that instead of a defined `FreeGroup`.
