### ISSUE TITLE
Huge slowdown in Classes/implementations/pointwise.v

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1555]
There is a huge slowdown in `Classes/implementations/pointwise.v`. Using `git bisect` I managed to track down the offending commit: 3a2973ea

The compile time for `Classes/implementations/pointwise.v` at 3a2973ea is `(real: 63.66, user: 63.40, sys: 0.19, mem: 395212 ko)`.

The compile time for `Classes/implementations/pointwise.v` at e819147e (the commit before) is `(real: 4.94, user: 4.75, sys: 0.18, mem: 378256 ko)`.

Something has gone really wrong!

**Comment by jdchristensen** [comment]
I guess it's this:
```coq
Global Hint Unfold Commutative : typeclass_instances.
```
I'm pinging Jarl: @jarlg

**Comment by jdchristensen** [comment]
Really the problem is the automation used in the `try_solve_fun` tactic in pointwise.v.  I have a simple change that greatly speeds up the file (1.5s).  I'll make a PR in a bit.

**Comment by Alizter** [comment]
Yeah, I agree that the automation in Classes can be a bit crude sometimes. This is understandable, since it wasn't written for HoTT but only ported later on.

**Comment by jarlg** [comment]
Thanks, good catch! Changing the `Hint Unfold Commutative` to `Typeclasses Transparent Commutative` gets the build time of `pointwise.v` down to normal, and also shaves off almost 20s over the rest of the library. Unless there are arguments otherwise, maybe we should make that change as well? Of course, fixing/removing the tactic used is good too.

**Comment by Alizter** [comment]
@jarlg That sounds like a good idea! Do you want to do a PR?

**Comment by jarlg** [comment]
The speedup didn't survive #1557, I'm now getting only ~3s improvement with the change, so I'll leave things as they are.

**Comment by jdchristensen** [comment]
If the proposed change has the same benefits as the existing `Hint`, and might prevent slow type checking in the future, maybe it is still a good idea?
