### ISSUE TITLE
Hej

### ISSUE THREAD

**Issue by AndyHere4U** [HoTT/HoTT#1569]
So are you looking for something special?

**Comment by AndyHere4U** [comment]
Yes I need a girl that loves to suck Dick and ride my dick.

**Comment by mikeshulman** [comment]
Reported content to github admin.  Is there a way to completely delete this?

**Comment by Alizter** [comment]
@mikeshulman When Github responds to your ticket they should be able to delete this.

Another alternative is that "owners" of a repository can delete issues and give "admins" permission to do so. This repo is owned by the "HoTT organization" which is the following list of people: https://github.com/orgs/HoTT/people.

There I can see that you are a considered an owner so you can probably find a "Delete this issue" button somewhere in the bottom right hand side next two the "lock", "pin", "transfer" etc. That should do what it says. https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue

You can also allow "admins" of this repo to have such permissions as described here: https://docs.github.com/en/organizations/managing-organization-settings/allowing-people-to-delete-issues-in-your-organization
For this repo we have the following list of people: https://github.com/HoTT/HoTT/settings/access with a "team" of admins: https://github.com/orgs/HoTT/teams/team-hott/members

That way the "delete this issue" button will appear to me also.
