### ISSUE TITLE
Informative: pick of tag for upcoming release of Coq Platform for Coq 8.14

### ISSUE THREAD

**Issue by MSoegtropIMC** [HoTT/HoTT#1581]
The Coq team released Coq 8.14+rc1 on September 17, 2021
and plans to release Coq 8.14.0 before October 31, 2021.
A corresponding Coq Platform releases should be released before November 30, 2021.
It can be dealyed in case of difficulties until January 31, 2022, but this should be an exception.

This issue is to inform you that your latest tag does work fine with Coq 8.14+rc1.

Coq Platform currently uses the opam package 'coq-hott.8.13~flex'
from platform patch repository https://github.com/coq/platform/tree/main/opam/opam-coq-archive/released.

__Note:__ We had to patch the opam package and possibly the make file to accept the new version of Coq, but no other changes were required.

In case this is the version you want to see in Coq Platform, there is nothing to do for you - just close this issue.

In case you would prefer to see an updated version in the upcoming Coq Platform, please inform as as soon as possible!

Thanks!

P.S.: this issue has been created semi-automatically.

CC: https://github.com/coq/platform/issues/139

**Comment by Alizter** [comment]
@MSoegtropIMC I intend to make a coq 8.14 HoTT library release soon, we are just waiting for coq to release properly in the mean time.

You mentioned that you had to patch the opam file and the makefile, would you be able to elaborate what was needed?

**Comment by MSoegtropIMC** [comment]
I just had to tell in opam "yes this package works with Coq 8.14" - nothing else.

You can find the patched opam file here: (https://github.com/coq/platform/tree/main/opam/opam-coq-archive/released/packages/coq-hott/coq-hott.8.13%7Eflex)

I guess I should change my script to put in a direct link to the opam file rather than a repo link ...

Please let me close the issue - I will do so after I updated to HoTT to the 8.14 release. This is just a measure of "double book keeping" to avoid I ship the wrong package.

**Comment by MSoegtropIMC** [comment]
I don't see an opam package as yet. Do you want me to create one?

**Comment by MSoegtropIMC** [comment]
I updated to "coq-hott.8.14".
