### ISSUE TITLE
Disable dependabot on forks

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#1609]
@JasonGross dependabot is sending my PRs on my fork. How can we disable this?

**Comment by JasonGross** [comment]
https://github.com/dependabot/dependabot-core/issues/2804#issuecomment-737781797 suggests deleting your fork and recreating it?  Seems like a pretty terrible fix

**Comment by Alizter** [comment]
Another workaround I found is to delete the dependabot file in the master branch of the fork. Or at least have another branch and set that as a default without dependabot. In any case, this looks like it might get annoying...
