### ISSUE TITLE
Please create a tag for Coq 8.16 in Coq Platform 2022.09

### ISSUE THREAD

**Issue by MSoegtropIMC** [HoTT/HoTT#1656]
The Coq team released Coq `8.16+rc1` on June 01, 2022.
The corresponding Coq Platform release `2022.09` should be released before **September 15, 2022**.
It can be delayed in case of difficulties until October 15, 2022, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (preview) **does not work** with Coq `8.16+rc1`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit bca7ccfa0ca359feb11c17a09f45042b46b23b68 on repository https://github.com/HoTT/HoTT - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.16, **preferably before August 31, 2022**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before August 17, 2022, it will be included in an early Coq Platform beta release of the for Coq 8.16+rc1.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.16+rc1~2022.09~preview1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.16~2022.09~preview1.sh) which already supports Coq version `8.16+rc1` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/274

**Comment by Alizter** [comment]
Here is a tag for a more recent version which works for 8.16. https://github.com/HoTT/HoTT/releases/tag/V8.16

**Comment by MSoegtropIMC** [comment]
@Alitzer: can you please publish an opam package for this version (if you want I can also do this).

**Comment by Alizter** [comment]
@MSoegtropIMC Done https://github.com/coq/opam-coq-archive/pull/2291

**Comment by MSoegtropIMC** [comment]
Thanks! All is well and I close this issue.
