### ISSUE TITLE
update reference to first path induction

### ISSUE THREAD

**Issue by louisGarde** [HoTT/HoTT#1676]
The last paragraph in the Notes of chapter 1 states:
`The path induction principle for identity types was formulated by Martin-Löf [ML98]`
However it seems that the paper [ML98] does not mention identity types.
According to [Evan Cavallo](https://hott.zulipchat.com/#narrow/stream/333752-The-HoTT-Book/topic/History.20of.20path.20induction), the identity type first appears in Martin-Löf's [similarly-named 1975 paper](https://archive-pml.github.io/martin-lof/pdfs/An-Intuitionistic-Theory-of-Types-Predicative-Part-1975.pdf), section 1.7.

**Comment by Alizter** [comment]
Maybe it would be a good idea to rename the repo to say `coq-hott`? Given that is how we distribute the opam package and it is much clearer than `HoTT/HoTT`. GitHub let's you do this and also redirect links to `HoTT/HoTT` to the new name.

**Comment by Alizter** [comment]
AFAIK nobody would have to do anything in their local repos.
