### ISSUE TITLE
Can we get rid of this warning?

### ISSUE THREAD

**Issue by andrejbauer** [HoTT/HoTT#291]
During compilation I keep getting

```
<W> Grammar extension: in [tactic:simple_tactic] some rule has been masked
```

What does it mean, and can we get rid of it?

**Comment by DanGrayson** [comment]
The warning comes from defining a new notation that, instead of overriding a previous notation, prevents it from being triggered, because some branch of the parsing table is now hidden behind
another one.  Try this interactively:
```
Print Scope core_scope.
Parameter f : nat -> nat -> nat.
Notation "( x , y , .. , z )" := (f .. (f x y) .. z).
Notation "( x , y ; .. ; z )" := (f .. (f x y) .. z).
```

I think ....

**Comment by Alizter** [comment]
Is this now resolved?

**Comment by Alizter** [comment]
@andrejbauer @JasonGross Is this now resolved?

**Comment by Alizter** [comment]
I am going to close this issue since I don't think it exists anymore. Feel free to reopen if it still persists.
