### ISSUE TITLE
IsTrunc and related definitions are hard to understand

### ISSUE THREAD

**Issue by ezyang** [HoTT/HoTT#295]
While I understand and appreciate the desirability of a sophisticated type-class resolution mechanism for automatically inferring witnesses of truncation, the current machinery as it stands is very hard for beginners (especially ones coming from the HoTT book) to understand, especially if they are not used to type-class wizardry.  Here are some (simple) questions, which don't seem to have simple answers:
1. Given a goal 'IsHSet A' and in the context 'H : forall (x y : A) (p q : x = y), p = q', how do I discharge the goal? (Hint: 'apply H' does not work)
2. (A refinement of 1.) How do I build an 'IsHSet A'; 'constructor' doesn't work? (Answer: it's a notation, turn on 'Set Printing All'. Follow up question: Do I really have to 'unfold IsTrunc', simpl, intros, and then manually construct a 'Contr_internal', whatever that is, to construct an 'IsHSet A'?)
3. What is idiomatic use of the type-class machinery? (Partial answer: "it should just work", "when it doesn't, try 'typeclasses eauto'", or "go read a tutorial about Coq typeclasses, this is standard.)

It would be nice if I didn't have to be a typeclass wizard to use the truncation machinery!

**Comment by Alizter** [comment]
Is this still an issue?

**Comment by ezyang** [comment]
You can close this if you like!

**Comment by Alizter** [comment]
@mikeshulman Can you close this?
