### ISSUE TITLE
Reasoning about transport is very slow

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#296]
I have some proofs that I ported from catdb which slowed down immensely when moving from using heterogeneous equality to using transport and PathGroupoids, namely https://github.com/JasonGross/HoTT/compare/master...finished-but-slow-exponential-laws and https://github.com/JasonGross/HoTT/compare/master...finished-but-slow-adjoint-pointwise.  The proofs aren't doing much interesting, but are about an order of magnitude slower than most of the other files in HoTT (the exception being categories/Comma/ProjectionFunctors.v).  It would be nice to have a better way of reasoning about paths quickly (perhaps by reflective automation, or an extension, or a well-tuned tactic).

**Comment by Alizter** [comment]
@JasonGross What is left in this issue?

**Comment by Alizter** [comment]
It should be noted that we do in fact have heterogeneous equality in the library now. It is under the name DPath in the Cubical library.

**Comment by mikeshulman** [comment]
Sometimes "heterogeneous equality" refers to the univalence-incompatible version; I'm not sure what @JasonGross meant here 6 years ago.

**Comment by JasonGross** [comment]
I was in fact referring to `JMeq` and `JMeq_eq` from the standard library, which are inconsistent with univalence.

**Comment by Alizter** [comment]
What can JMeq do that DPath's can't? Or is it something to do with axiom K?

**Comment by mikeshulman** [comment]
The axiom `JMeq_eq` is equivalent to K.

**Comment by mikeshulman** [comment]
I suspect that this issue is stale and should be closed, but I'll let @JasonGross opine.

**Comment by Alizter** [comment]
Oh ok that explains it. Regarding this issue however, if transports are slow I am curious to see if DPaths do any better, since I would expect there to be less unfolding.
