### ISSUE TITLE
Missing definitions and axioms for LEM (law of excluded middle)

### ISSUE THREAD

**Issue by ezyang** [HoTT/HoTT#299]
As far as I can tell (grepping for 'excluded' and 'LEM' and doing SearchAbout 'IsHProp', searching about Axiom), the HoTT library does not have any definitions or axioms pertaining to the law of the excluded middle. This seems like a major omission.

**Comment by Alizter** [comment]
We now have: https://github.com/HoTT/HoTT/blob/master/theories/ExcludedMiddle.v
