### ISSUE TITLE
Prettier Dependency Graphs

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#330]
It would be nice if the [dependency graph of the library including categories](http://hott.github.io/HoTT/dependencies/HoTT.svg)* were more readable; in particular, I think that grouping files by directories would help.

It would be nice if we had prettier [inter-file theorem dependency graphs](http://hott.github.io/HoTT/file-dep-graphs/hott-lib.svg)**, and some way of combining that with the file dependency graph.  (Perhaps we should make a variant of the file dependency graph that links each file to the corresponding dependency graph of theorems in that file, to replace [the plain index we have now](http://hott.github.io/HoTT/file-dep-graphs/).

*[![http://hott.github.io/HoTT/dependencies/HoTT.svg](http://hott.github.io/HoTT/dependencies/HoTT.svg)](http://hott.github.io/HoTT/dependencies/HoTT.svg)

**[![http://hott.github.io/HoTT/file-dep-graphs/hott-lib.svg](http://hott.github.io/HoTT/file-dep-graphs/hott-lib.svg)](http://hott.github.io/HoTT/file-dep-graphs/hott-lib.svg)

**Comment by Karmaki** [comment]
dpdgraph is now available in GitHub: https://github.com/Karmaki/coq-dpdgraph
Hope it helps.

**Comment by spitters** [comment]
We now have beautiful graphs
