### ISSUE TITLE
Making HoTT a contrib

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#424]
We should submit HoTT as a contrib, now that it compiles with trunk.  The coqdevs have said they are interested in the coqdev mailing list.  To do this, we simply fill out http://coq.inria.fr/pylons/contribs/new.  I'm thinking the following values for the fields:
- Name: HoTT
- Title: Homotopy Type Theory
- Homepage: https://github.com/HoTT/HoTT/wiki
- Description: A formalization of various fundamentals of homotopy type theory (http://homotopytypetheory.org/) and category theory.
- Keywords: HoTT, homotopy type theory, homotopy, category theory, categories, type theory, foundations, fundamentals
- Category: Mathematics/Logic/Type theory
- Authors: I'm inclined to fill in details for everyone with over 100 commits according to https://github.com/HoTT/HoTT/graphs/contributors (@JasonGross, @andrejbauer, @peterlefanulumsdaine, @mikeshulman).  If we want everyone over 20 commits, we also need details (Name, Email, Homepage, Institution) for @amahboubi, and if we want everyone who's touched over 2000 lines, we should also add @kristinas and @awodey.  Or we could include [everyone](https://github.com/HoTT/HoTT/graphs/contributors), but that's a lot of details to fill in.
  For the first four, I'm planning on using (from your github profile or from google)
  - @JasonGross
    - Name: Jason Gross
    - Email: jgross@mit.edu
    - Homepage: https://people.csail.mit.edu/jgross/
    - Institution: Massachusetts Institute of Technology
  - @andrejbauer 
    - Name: Andrej Bauer
    - Email: Andrej.Bauer@andrej.com
    - Homepage: http://andrej.com/
    - Institution: University of Ljubljana
  - @peterlefanulumsdaine 
    - Name: Peter LeFanu Lumsdaine
    - Email: p.l.lumsdaine@gmail.com
    - Homepage: http://www.peterlefanulumsdaine.com/
    - Institution: Stockholm University
  - @mikeshulman
    - Name: Mike Shulman
    - Email: shulman@sandiego.edu
    - Homepage: http://www.sandiego.edu/~shulman
    - Institution: University of San Diego
  - @spitters 
    - Name: Bas Spitters
    - Email: b.a.w.spitters@gmail.com
    - Homepage: http://www.cs.ru.nl/~spitters/
    - Institution: Radboud University Nijmegen
  - @amahboubi 
    - Name: Assia Mahboubi
    - Email: Assia.Mahboubi [at] inria.fr 
    - Homepage: http://specfun.inria.fr/mahboubi/
    - Institution: INRIA
  - @DanGrayson 
    - Name: Daniel R. Grayson
    - Email: dan@math.uiuc.edu
    - Homepage: http://dangrayson.com/
    - Institution: University of Illinois at Urbana-Champaign
  - @mattam82
    - Name: Matthieu Sozeau
    - Email: mattam@mattam.org
    - Homepage: http://mattam.org/
    - Institution: INRIA
  - @Barbichu
    - Name: Cyril Cohen
    - Email: firstname.lastname@gu.se
    - Homepage: http://perso.crans.org/cohen/
    - Institution: University of Gothenburg
  - @kristinas 
    - Name: Kristina Sojakova
    - Email: kristinas AT cmu.edu
    - Homepage: http://www.cs.cmu.edu/~ksojakov/
    - Institution: Carnegie Mellon University
  - @ezyang
    - Name: Edward Z. Yang
    - Email: ezyang@mit.edu
    - Homepage: http://ezyang.com/
    - Institution: Stanford University
  - @marcbezem
    - Name: Marc Bezem
    - Email: bezem at ii.uib.no
    - Homepage: http://www.ii.uib.no/~bezem/
    - Institution: Institutt for informatikk, Universitetet i Bergen
  - @benediktahrens
    - Name: Benedikt Ahrens
    - Email: last_name@irit.fr
    - Homepage: http://benedikt-ahrens.org/
    - Institution: IRIT
  - @awodey 
    - Name: Steve Awodey
    - Email: sawodey@gmail.com
    - Homepage: http://www.andrew.cmu.edu/users/awodey
    - Institution: Carnegie Mellon University
  - @SkySkimmer
    - Name: Gaetan Gilbert
    - Email: gaetan.gilbert@ens-lyon.fr
    - Homepage: ???
    - Institution: ???
  - @0x01
    - Name: Jelle Herold 
    - Email: jherold@cs.ru.nl
    - Homepage: http://www.cs.ru.nl/~jherold/
    - Institution: Radboud University Nijmegen
  - @jcmckeown
    - Name: ???
    - Email: qnoodles@gmail.com
    - Homepage: ???
    - Institution: ???
  - @ynm
    - Name: Alexander Karpich
    - Email: avkarpich@gmail.com
    - Homepage: ???
    - Institution: ???
  - @stupidpeasant
    - Name: ???
    - Email: stupid.peasant@gmail.com
    - Homepage: ???
    - Institution: ???
  - ???
    - Name: Egbert
    - Email: egbert@rudin.(none) (???)
    - Homepage: ???
    - Institution: ???
  - ???
    - Name: Michael Nahas
    - Email: mike@nahas.com
    - Homepage: ???
    - Institution: ???
- Location: https://github.com/HoTT/HoTT/archive/master.tar.gz
- License: obsd

Questions:
- Who should we include as authors?
- Does anyone have a suggestion for a better description?
- Is the license right?  [LICENSE.txt](https://github.com/HoTT/HoTT/blob/master/LICENSE.txt) says 2-clause bsd

**Comment by ejgallego** [comment]
See this: https://github.com/coq-contribs/coq-contribs/issues/2

**Comment by DanGrayson** [comment]
There is no need to list me as an author.

**Comment by benediktahrens** [comment]
There is no need to list me as an author.

**Comment by andrejbauer** [comment]
Stupid peasant is my doppelgänger.

People who stated that they do now want to be authors should still be acknowledges somewhere, if conq-contrib allows that.

**Comment by ejgallego** [comment]
This is IMHO mostly solved by the CI integration and should be closed. More up to date discussion in #947
