### ISSUE TITLE
Port HLevel (from old HoTT)

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#47]

**Comment by spitters** [comment]
The old stuff is [here](https://github.com/HoTT/HoTT/tree/master/contrib). 
Where is the old Hlevel.v

**Comment by mikeshulman** [comment]
Go back in time to 2.5 years ago?

**Comment by andrejbauer** [comment]
This issue is obsolete. Even if there's something that we did not port, we're not going to do it after all this time.
