### ISSUE TITLE
Native HITs

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#478]
There is a [version of Coq](https://github.com/barras/coq/tree/hit) with native HITs, that @barras was working on at one point.  Once 8.5 is released, and we're not pinning the code to trunk anymore, do we want to see if we can get that version of Coq rebased on top of 8.5 trunk and tie ourselves to that?  Or do we want to stick with 8.5 and fake HITs, until we have a released version of Coq with native HITs?

**Comment by Alizter** [comment]
@JasonGross @spitters Any updates on this?

**Comment by spitters** [comment]
No, haven't heard more about this.
