### ISSUE TITLE
making submodules and make more friendly

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#510]
I've been thinking about how we could insulate newcomers better from git submodule hell.  What if running `make` would check whether the coq-HoTT submodule is out of sync, and if so either warn the user or ask "would you like me to recompile coq for you?"  I don't think we want `make` to automatically compile coq, but it would be nice if the user didn't have to notice on their own when it becomes necessary.

**Comment by spitters** [comment]
We no longer use the submodule
