### ISSUE TITLE
rewrite is dumber than "match goal with context"

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#553]
In [this file](https://github.com/mikeshulman/HoTT/blob/factorization/theories/Factorization.v) there are a number of places where `rewrite lem` fails, but doing a manual

```
match goal with |- context [ ... ] => rewrite (lem ...) end
```

to find the correct arguments of `lem` succeeds.  I am tempted to consider this a bug; is there some fundamental reason why `rewrite` can't match these applications on its own?

**Comment by Alizter** [comment]
Anything left to do here?

**Comment by mikeshulman** [comment]
No, I don't think so.
