### ISSUE TITLE
Rename `hit` and `categories` directories

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#612]
We seem to be trending to using capitals for directories (this should probably be recorded in the style file), so we should probably rename `hit` to `HIT` and `categories` to `Categories`.

**Comment by spitters** [comment]
I agree, maybe just send a pull-request?

**Comment by andrejbauer** [comment]
This creates a problem on OS X. OS X has a on-read-case-insensitive file system which makes it impossible to directly rename 'categories' to 'Categories'. Have we dealt with this already?

**Comment by mikeshulman** [comment]
I don't understand.  If the filesystem is case-insensitive, then it shouldn't matter what case we use, whereas if it is case-sensitive then we should be able to rename the directory.

**Comment by andrejbauer** [comment]
Hmm, then it must be `git` that is messing up. It's just that pulling in the latest version fails to rename the directories.

**Comment by andrejbauer** [comment]
http://stackoverflow.com/questions/3011625/git-mv-and-only-change-case-of-directory

**Comment by mattam82** [comment]
A fresh clone will work though right?

**Comment by andrejbauer** [comment]
Yes. I think that's the simplest solution, we just need to write it somewhere. The error is "I can't find the physical path" or some such, and it's not easy to guess what's happening. OTH, I was updating a very old version, so perhaps there aren't many people left who could hit this problem.

**Comment by andrejbauer** [comment]
Since I am no a mission to close issues, I'll close this one, but let me just alert future visitors that this issue is the solution to compilation on Mac OSX telling you that

    Error: Cannot find a physical path bound to logical path matching suffix

**Comment by mikeshulman** [comment]
Wow, that is an amazingly opaque error message.
