### ISSUE TITLE
Module applications not convertible

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#633]
Why doesn't the following work?

```coq
Module Type Foo.
End Foo.

Module myfoo : Foo.
End myfoo.

Module Type Bar (foo : Foo).
  Parameter A : Type.
End Bar.

Declare Module mybar : Bar.

Module mybar1 := mybar myfoo.
Module mybar2 := mybar myfoo.

Definition baz : mybar1.A -> mybar2.A
  := fun x => x.
(** Error: The term "x" has type "mybar1.A" while it is expected to have type "mybar2.A". *)
```

If `mybar` were an actual implementation of `Bar`, it would have to be the case that `mybar1.A` and `mybar2.A` are the same.  Right?

My best guess is that Coq just doesn't even know what it means for two modules to be "the same", so it isn't able to notice that `mybar1` and `mybar2` are defined identically.  Is there a fundamental reason for this, or is it just something that no one's ever coded?  Would it be impossibly difficult to code?  I'm not suggesting any sort of beta-reduction for modules, just the ability to notice that two applications of a parametrized module have exactly the same arguments and thus should produce the same module.

**Comment by mikeshulman** [comment]
@mattam82 , can you also say anything about _why_ module functors are "generative and not applicative"?  Are there any prospects for changing it?  This would be a really useful thing for me to have work.

**Comment by mikeshulman** [comment]
Here is another problem I've just encountered.  It seems like it might be related, but it also doesn't seem like quite the same thing.

```coq
Module Type TypeM.
  Parameter m : Type.
End TypeM.

Module Type Subuniverse (XM : TypeM).
  Parameter m : Type.
End Subuniverse.

Module Type InF (F : Subuniverse) (XM : TypeM).
  Module FXM := F XM.
  Parameter m : FXM.m.
End InF.

Module Type Modality.
  Parameter m : Type@{i} -> Type@{i}.
End Modality.

Module Modal_Subuniverse (O : Modality) (XM : TypeM) <: Subuniverse XM.
  Definition m := O.m XM.m.
End Modal_Subuniverse.

Module MSU (O : Modality).
  Module F := Modal_Subuniverse O.
  Module test (XM : TypeM) (xinf : InF F XM).
    Definition oops : O.m XM.m := xinf.m.
  End test.
End MSU.
```

This fails on `oops` with `The term "xinf.m" has type "xinf.FXM.m" while it is expected to have type "O.m XM.m".`.  But `xinf.FXM` is `F XM`, while `F` is `Modal_Subuniverse O`, so `F XM` ought to be `Modal_Subuniverse O XM` and thus its field `m` should be by definition `O.m XM.m`.  What am I missing?

**Comment by mikeshulman** [comment]
The second example is [bug 4003](https://coq.inria.fr/bugs/show_bug.cgi?id=4003).  The first one is, I guess, sufficiently answered by "module functors are generative".

**Comment by spitters** [comment]
Note that the coqdevs are currently closing "blocking bugs" before the next
beta release.
If we have anything, we should probably speak up now.
