### ISSUE TITLE
Anomaly when printing type induction scheme for record

### ISSUE THREAD

**Issue by hannobecker** [HoTT/HoTT#634]
Trying `Print DummyRecord_rect.` after 
```
Record DummyRecord : Type := Build_DummyRecord { 
      DummyField : nat
}.
```
I get the following message from hoqtop:
```
Toplevel input, characters 0-23:
Anomaly: File "pretyping/detyping.ml", line 239, characters 8-14: Assertion failed.
Please report.
```
I'm new to both HoTT (hello everyone!) and to GitHub so I hope that it's not a mistake of mine and that this is the right place and the correct form for the report. If not, I'd be happy to be redirected to where such issues are discussed instead.

**Comment by JasonGross** [comment]
This seems to be fixed in latest trunk.
