### ISSUE TITLE
Make a directory for theories of specific types

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#636]
I think we should have a directory to contain theories about _specific_ types (by contrast with `Types/` which is about the generic type formers).  For instance, in `Idempotent.v` there is some theory of cantor space, and also of the operation `BAut`.  Once we free the HITs #573, we could put `Circle` and `Spheres` etc. there too.  But I'm not sure how to name this directory, since `Types/` is taken.  One thought is `Spaces`, but possibly that's a bad idea.

**Comment by JasonGross** [comment]
We now have `Spaces`
