### ISSUE TITLE
Fixing `compose` and catching up with trunk

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#657]
As per [bug 3881](https://coq.inria.fr/bugs/show_bug.cgi?id=3881), we managed to catch Coq in a state where it used a different order of evar resolution than in 8.4.  With https://github.com/coq/coq/commit/96906c2a1ba9426271a4048bfa8b3991db51c192, Coq switched back to how it was doing things in 8.4, resulting in many cases of `isequiv_compose` being uninferrable.  If we β-expand `o` to make it
```coq
Notation compose := (fun g f x => g (f x)).
Notation "g 'o' f" := (compose g f) (at level 40, left associativity) : function_scope.
```
I suspect this will be enough to fix it.  I am open to other suggestions, though.  As an example alternative, simply fixing the proofs will involve many diffs that look something like
```diff
diff --git a/theories/Basics/Equivalences.v b/theories/Basics/Equivalences.v
index 5a15081..4fc64d8 100644
--- a/theories/Basics/Equivalences.v
+++ b/theories/Basics/Equivalences.v
@@ -148,9 +148,14 @@ Global Instance symmetric_equiv : Symmetric Equiv | 0 := @equiv_inverse.
 (** If [g \o f] and [f] are equivalences, so is [g].  This is not an Instance because it would require Coq to guess [f]. *)
 Definition cancelR_isequiv {A B C} (f : A -> B) {g : B -> C}
   `{IsEquiv A B f} `{IsEquiv A C (g o f)}
-  : IsEquiv g
+  : IsEquiv g.
-  := isequiv_homotopic (compose (compose g f) f^-1)
-       (fun b => ap g (eisretr f b)).
+Proof.
+  refine (isequiv_homotopic
+            ((g o f) o f^-1)
+            (fun b => ap g (eisretr f b))).
+  refine (@isequiv_compose _ _ f^-1 _ _ (g o f) _).
+  exact _.
+Defined.

 Definition cancelR_equiv {A B C} (f : A -> B) {g : B -> C}
   `{IsEquiv A B f} `{IsEquiv A C (g o f)}
```

**Comment by mikeshulman** [comment]
Note: see discussion at #663 for what still needs fixing.

**Comment by mikeshulman** [comment]
I have a question about the above modified proof of `cancelR_isequiv`:

```coq
refine (isequiv_homotopic
          ((g o f) o f^-1)
          (fun b => ap g (eisretr f b))).
refine (@isequiv_compose _ _ f^-1 _ _ (g o f) _).
exact _.
```

After the first `refine`, Coq tells me there are two subgoals, `IsEquiv (fun x : B => g (f (f^-1 x)))` and `IsEquiv f`.  After the second refine, it says only `IsEquiv f` is left, and then after `exact _` none.  So far so good, but if I try to add bullets to mark off the solutions of the two subgoals:

```coq
refine (isequiv_homotopic
          ((g o f) o f^-1)
          (fun b => ap g (eisretr f b))).
- refine (@isequiv_compose _ _ f^-1 _ _ (g o f) _).
- exact _.
```

then after the second `refine`, rather than saying "This subgoal is complete" Coq drops me right into the second subgoal, and the second bullet `-` then complains with "not finished".  Is this a bug?

Also: why can't Coq find the `IsEquiv f` instance that's sitting in the hypotheses without help?

**Comment by mikeshulman** [comment]
I tried `Set Typeclasses Debug` on this proof (with `compose` redefined as `compose g f := (fun x => g (f x)).`) and I'm confused about what Coq is doing.  The first `refine` yields

```
Debug: 1.1: unfold pointwise_paths on (IsEquiv (g o f o f^-1))
Debug: 1.1.1.1: apply @isequiv_compose on
(IsEquiv (fun x : B => g (f (f^-1 x))))
Debug: 1.1.1.1.1.1: apply @isequiv_compose on (IsEquiv (f o f^-1))
Debug: 1.1.1.1.1.1.1: no match for (IsEquiv (fun x : B => f^-1 x))
, 10 possibilities
Debug: Backtracking after apply @isequiv_compose
Debug: Backtracking after apply @isequiv_compose
Debug: Backtracking after unfold pointwise_paths
Debug: 1.2: apply @isequiv_compose on (IsEquiv (g o f o f^-1))
Debug: 1.2.1: no match for (IsEquiv (fun x : B => f^-1 x)) , 10 possibilities
Debug: Backtracking after apply @isequiv_compose
```

This looks to me like what is happening is:

1. Coq first tries applying `isequiv_compose` to `(g o f o f^-1)` by decomposing it as `(g o (f o f^-1))`, so it needs `IsEquiv g` and `IsEquiv (f o f^-1)`

2. Proceeding in right-to-left order, I guess, it then tries applying `isequiv_compose` to `(f o f^-1)`, fails because it can't find `IsEquiv (fun x : B => f^-1 x)`.  (Why not?  We have `isequiv_inverse` already declared as an instance.)

3. Next it tries decomposing `(g o f o f^-1)` as `((g o f) o f^-1)`, and fails again because it inexplicably can't find `IsEquiv (fun x : B => f^-1 x)`.

Now I thought we said above that the reason for failure is that typeclass search *isn't* willing to try reassociating a composite of more than two functions in more than one way, but it seems to be trying that here and failing for a different reason.  Or am I misreading the debug output?

**Comment by mikeshulman** [comment]
Also, as long as I'm asking questions about `IsEquiv`, I can't make heads or tails of this comment (I can't even parse it as English):

```coq
(** If the goal is [IsEquiv _^-1], then use [isequiv_inverse];
otherwise, don't pretend worry about if the goal is an evar
and we want to add a [^-1]. *)
Hint Extern 0 (IsEquiv _^-1) => apply @isequiv_inverse : typeclass_instances.
```

**Comment by JasonGross** [comment]
> Also, as long as I'm asking questions about `IsEquiv`, I can't make heads or tails of this comment (I can't even parse it as English):

What the comment should say is something like "If the goal is [IsEquiv _^-1], then use [isequiv_inverse]; otherwise, if the goal is an evar, say, [?1], don't instantiate the evar with the inverse of a fresh evar, e.g., with [?2^-1]."  I presume the original comment was trying to say "don't worry about the case where we want to add [^-1]"?

**Comment by JasonGross** [comment]
> Now I thought we said above that the reason for failure is that typeclass search *isn't* willing to try reassociating a composite of more than two functions in more than one way, but it seems to be trying that here and failing for a different reason.  Or am I misreading the debug output?

That was my guess without doing much debugging.  If the debug output contradicts that, trust the debug output, not my guess.

**Comment by JasonGross** [comment]
Here is a hint (I am still trying to fully untangle the behavior): If Coq cannot solve all typeclass problems, it seems to decide that it will solve none of them.  Notice that
```coq
  refine (let foo := _ : (@IsEquiv B A
                                   (fun x : B =>
                                      @equiv_inv _
                                                 _ f _ x))
          in _).
```
will leave you with two additional goals, but if you `assert True` first, you will get no additional goals.  (It seems that since it cannot solve the final underscore, it leaves all of the holes as goals.)  (Is this a bug, @mattam82?  Should this be settable behavior?)

**Comment by JasonGross** [comment]
Something even more confusing: If you first `assert (IsEquiv g) by admit`, you are *still* left with two goals after
```coq
  refine (isequiv_homotopic (compose (compose g f) f^-1)
                          (fun b => ap g (eisretr f b))).
```
Furthermore, you can solve the two (independent) goals with `all:try exact _; exact _.`, but not with `all:exact _`.  That is, you can solve them with `2:exact _. 1:exact _`, but not `exact _. exact _.`.  This seems like a bug.  (I wonder if it's been fixed in most recent trunk?)

**Comment by JasonGross** [comment]
Reported this last confusing bit as [bug 3909](https://coq.inria.fr/bugs/show_bug.cgi?id=3909) (see also [bug 3910](https://coq.inria.fr/bugs/show_bug.cgi?id=3910)).

**Comment by JasonGross** [comment]
Note: current trunk (b858f939f33dc4bc4c8e470ed62310ef15c59a99) is able to get *a lot* further than the last time I checked (it fails only on `Idempotents` and things depending on that), so we may want to bump the submodule again.

**Comment by mikeshulman** [comment]
> if the goal is an evar, say, [IsEquiv ?1], don't instantiate the evar with the inverse of a fresh evar, e.g., with [?2^-1]

Ok.  Would Coq do that anyway, now that `IsEquiv` is defined under `Typeclasses Strict Resolution`?

> current trunk (b858f939f33dc4bc4c8e470ed62310ef15c59a99) is able to get a lot further than the last time I checked (it fails only on Idempotents and things depending on that), so we may want to bump the submodule again.

Yes, definitely!

**Comment by JasonGross** [comment]
> Ok.  Would Coq do that anyway, now that `IsEquiv` is defined under `Typeclasses Strict Resolution`?

Hopefully?  "Test it and see"

**Comment by mikeshulman** [comment]
I'm not sure how to test it.

**Comment by mattam82** [comment]
The Hint Extern won't match an Equiv ?X goal ever, strict resolution or not, due to the way patterns are matched in typeclass resolution and auto/eauto. This was the only way to avoid loops on inverse/symmetry instances before, making an explicit hint with a pattern including the constant.

About the dependencies of typeclasses, this is a complicated issue. Typeclass resolution already works on disjoint subsets of the existentials w.r.t. dependencies, but the current semantics is that if a connected subset of instances can not entirely be solved at one time, then we don't record an (arbitrary) partial instantiation as a solution. Maybe under strict resolution mode or another flag this could be relaxed, but I know that some code does rely on the current semantics.

**Comment by JasonGross** [comment]
> The Hint Extern won't match an Equiv ?X goal ever, strict resolution or not, due to the way patterns are matched in typeclass resolution and auto/eauto. This was the only way to avoid loops on inverse/symmetry instances before, making an explicit hint with a pattern including the constant.

I think the question is, if we have strict resolution set, and have `Instance: IsEquiv (f^-1)`, will that resolve on `IsEquiv ?1`?
@mikeshulman, I suspect a way to test is to see if `_ : IsEquiv _` resolves to anything?

**Comment by mattam82** [comment]
That shouldn't match either as ?1 would need to be set.

**Comment by JasonGross** [comment]
@mikeshulman, what's supposed to happen here (proof of `contr_splitting_preidem_idmap`)?
```coq
    exact {p : s o r == idmap &
           forall x, ((ap idmap (p x)^ @ (p (s (r x)))^)
                        @ ap s (H (r x))) @ p x = isidem x }.
(* Toplevel input, characters 0-146:
Error:
Unable to satisfy the following constraints:
In environment:
ua : Univalence
X : Type
A : Type
r : X -> A
s : A -> X
H : (fun x : A => r (s x)) == idmap
p : s o r == idmap
x : X

?IsPreIdempotent : "IsPreIdempotent (fun _ : X => x)" *)
```

**Comment by JasonGross** [comment]
Oh, it's supposed to be `IsPreIdempotent idmap`?

**Comment by mikeshulman** [comment]
It is.  But I think relying on Coq to guess that is poor style anyway; I'm not sure why I did it.  Maybe because Coq made `f` an implicit argument to `isidem` and I didn't correct it.  See #682.

**Comment by mikeshulman** [comment]
Well, b858f939f33d may have been good (I haven't tried it myself), but the Coq we've got now is back to failing on `cancelR_isequiv`.

**Comment by JasonGross** [comment]
Can you reproduce this on travis?  Travis seems happy with current trunk, and I locally reproduced with 13a55aa2e8fd999a96cf1e4df5a0e34f26e3dcc8, and I don't think there have been any changes to the Coq running code since then.  (Only .vi -> .vio, and changing the --help text.)

**Comment by mikeshulman** [comment]
I mean, _after_ changing compose to be `compose g f := (fun x => g (f x))`...

**Comment by mikeshulman** [comment]
What does it mean for `_ : IsEquiv _` to "resolve to anything" and how do I test it?

**Comment by JasonGross** [comment]
Does `Check (_ : IsEquiv _).` give you something like `isequiv_idmap : IsEquiv idmap`, or does it give you something like `?1 : IsEquiv ?2`?

**Comment by JasonGross** [comment]
> I mean, _after_ changing compose to be `compose g f := (fun x => g (f x))`...

Oh.  Uh, [maybe it's higher order unification changing again](https://coq.inria.fr/bugs/show_bug.cgi?id=3914)?

**Comment by JasonGross** [comment]
What if we add a series of hints (I might have gotten the implicit names wrong):
```coq
Hint Extern 2 (IsEquiv (fun x => ?f (?g (?h x)))) => apply (isequiv_compose (f := f) (g := g o h)) : typeclass_instances.
Hint Extern 2 (IsEquiv (fun x => ?f (?g (?h x)))) => apply (isequiv_compose (f := f o g) (g := h)) : typeclass_instances.
Hint Extern 2 (IsEquiv (fun x => ?f (?g (?h (?i x))))) => apply (isequiv_compose (f := f) (g := g o h o i)) : typeclass_instances.
Hint Extern 2 (IsEquiv (fun x => ?f (?g (?h (?i x))))) => apply (isequiv_compose (f := f o g) (g := h o i)) : typeclass_instances.
Hint Extern 2 (IsEquiv (fun x => ?f (?g (?h (?i x))))) => apply (isequiv_compose (f := f o g o h) (g := i)) : typeclass_instances.
...
```
so that Coq doesn't have to do higher-order unification?

**Comment by mikeshulman** [comment]
I was thinking of something like that too.  But looking at the typeclass debug output dissuaded me from trying it, because it looked like Coq was actually doing the right unification but failing to find the instances that were right there in the context.

**Comment by mikeshulman** [comment]
`Check (_ : IsEquiv _).` says

```
?i:IsEquiv ?y
     : IsEquiv ?y
where
?A : [ |- Type] 
?B : [ |- Type] 
?y : [ |- ?A -> ?B] 
?i : [ |- IsEquiv ?y] 
```

(this is with `compose` redefined, if that matters).

**Comment by JasonGross** [comment]
It looks like strict resolution is doing its job.

**Comment by mikeshulman** [comment]
Good; does that mean we don't need the `Hint Extern` with the incomprehensible comment any more?

**Comment by mikeshulman** [comment]
Adding all your suggested `Hint Extern`s for `isequiv_compose` doesn't help Coq solve `cancelR_isequiv`.

**Comment by JasonGross** [comment]
Probably; it should be fine to change most of these back into `Instance`s.  Try it and see if it works?

**Comment by mikeshulman** [comment]
`isequiv_inverse` already *is* an instance, with priority 10000...

**Comment by JasonGross** [comment]
Strange.  It's probably fine to remove the `Hint Extern`, and bump the priority down (up?) to `1` (or just strip off the priority all-together.

**Comment by JasonGross** [comment]
It's possible that there's something strange going on in `cancelR_isequiv` related to [bug 3915](https://coq.inria.fr/bugs/show_bug.cgi?id=3915), given that `assert (IsEquiv g) by admit` isn't enough to make typeclass resolution solve everything.

**Comment by mikeshulman** [comment]
(It is annoying that Coq uses *higher* numbers to mean what one would ordinarily call "lower priority", isn't it?  Is that a translation issue?)

**Comment by JasonGross** [comment]
[It's a common issue in general](http://discuss.joelonsoftware.com/default.asp?design.4.94319.22).  Consider "first place" and "second place" (or "we're number one!") versus "10 out of 10".

**Comment by spitters** [comment]
Since we have caught up with trunk, can this now be closed?
