### ISSUE TITLE
Projecting truncatedness?

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#671]
I know that the following two theorems are true:
```coq
forall A P, Contr A -> Contr { x : A | P x } -> forall x, Contr (P x)
forall A P, IsHProp A -> IsHProp { x : A | P x } -> forall x, IsHProp (P x)
forall A P, IsHSet A -> IsHSet { x : A | P x } -> forall x, IsHSet (P x)
```
Does this generalize?  Is there a proof of this somewhere in the library already?

**Comment by mikeshulman** [comment]
It generalizes to any reflective subuniverse, but it wasn't in the library yet: #672
