### ISSUE TITLE
Anomaly from printing eliminators of certain record types

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#679]
[This gist](https://gist.github.com/peterlefanulumsdaine/c90cb256aa8dd33ce5af) exhibits a strange error that occurs trying to print eliminators of certain record types: `Print foo_rect.` produces
    
    Toplevel input, characters 21-42:
    Anomaly: Uncaught exception Invalid_argument("index out of bounds").
    Please report.

The same error occurs when printing objects defined using the `destruct` tactic over `foo`, since this uses `foo_rect`.  `foo_ind` and `foo_rec` are fine.

This seems to be HoTT-specific: in recent plain coq, `foo_rect` is not defined, and `destruct` is implemented directly as a match, so prints fine.

Other record eliminators I have tried are fine; the problem seems to be something in the specific dependency structure of the linked example.

It seems possible that [Coq bug 3903](https://coq.inria.fr/bugs/show_bug.cgi?id=3903) is related.

**Comment by mikeshulman** [comment]
I wonder if it's related to #634.  Have you experimented to see whether any of the option `Set`s in the HoTT stdlib is the culprit?

**Comment by peterlefanulumsdaine** [comment]
Ah, thanks for the tip to check that!  Yes, the combination of

    Set Nonrecursive Elimination Schemes.
    Set Primitive Projections.
    Set Universe Polymorphism.

elicits it from trunk coq.  Will report on Coq bugs.

**Comment by JasonGross** [comment]
@mattam82 has fixed this (thanks!).  Should we bump trunk yet again?  Or should we wait for a more interesting change?

**Comment by mikeshulman** [comment]
I'm inclined to wait, but if anyone (@peterlefanulumsdaine?) wants to bump I won't object.
