### ISSUE TITLE
HoTT advertised on Coq web site

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#684]
I noticed today that https://coq.inria.fr/ links to http://homotopytypetheory.org/coq/ in the same breath as the Feit-Thompson theorem.

**Comment by andrejbauer** [comment]
Cool, althugh I am not sure we deseve to be featured on the front page of Coq. Maybe all the bug reports flying in from our side of the field skew the Coq team impression.

**Comment by spitters** [comment]
The reference is to HoTT in general. Not to this library in particular.
It seems fair to consider HoTT as a project of comparable size as the
Feit-Thompson theorem.
Not in terms of LOC, but in terms impact/ man years invested in the
project, ...
