### ISSUE TITLE
A notation for equiv_compose

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#687]
`equiv_compose'` is used a lot and merits a notation, perhaps `oE`, or simply `o` if we aren't worried about ambiguity.

**Comment by JasonGross** [comment]
If no one else has a preference, I will express a very slight preference for ovoverloading `o` further.

**Comment by peterlefanulumsdaine** [comment]
How does the overloaded version work in practice — does Coq frequently need the scope disambiguated by hand, or not?  If not, then I also vote for overloading `o`, for human-readability.  If it does, though, I would see a consistent `oE` as slightly nicer than an unpredictable sprinkling of scope delimiters.

(Sorry by the way that I am mostly commenting without contributing directly at the moment!  I’m working on a couple of developments over the library, so am keeping roughly up-to-date on it, but haven’t felt fully enough on top of the current state to be confident of contributing myself.  Very much appreciating all the recent additions, though!)

**Comment by mikeshulman** [comment]
I think we'd have to try it and see.

(Do you think your developments-on-top might eventually be contributed back to the library?)

**Comment by peterlefanulumsdaine** [comment]
(Continuing the parenthetical: at least in part, yes, depending on how they shape up.)

**Comment by JasonGross** [comment]
To give a more systematic answer: overloaded notations tend to be
automatically resolvable when they appear as arguments to functions that
accept only the relevant type (so, equiv_compose could be inferred when it
shows up as an argument to a function that only accepts equivalences).
`function_scope` is an exception; Coq has no facility to bind it
automatically to arguments expecting lambdas.  So it's moderately likely
that if we want to mix function composition with equivalence composition in
the same file at top level, we'll need to manually play with scopes.
(Files not defining equivalences at top level probably won't need manual
scope munging.)

**Comment by mikeshulman** [comment]
I'd kind of rather not take on this change until my open PRs get merged (#631, #674, #686) -- otherwise they'll need to be rebased again.

**Comment by JasonGross** [comment]
I think we can consider this closed, though feel free to reopen if anyone thinks there should be more discussion over the notation.
