### ISSUE TITLE
Equivalence induction

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#691]
Given an equivalence `e : A <~> B`, we should be able to write a tactic `equiv_induction e` that behaves as well as `induction p` for `p : A = B`, and leaves a side-condition that the type of the goal respects equivalences.  This side condition should be automatically solvable in most cases, since most of the type-formers respect equivalence.

**Comment by mikeshulman** [comment]
Yes, I also had the thought once that we could define a typeclass for "respects equivalences" to automatically infer those conditions.

**Comment by andrejbauer** [comment]
This was one of the very early things I tried to do in this library. Peter Aczel suggested it do me. The tricky bit is when you get to dependent types. Is this supposed to cover those?

**Comment by JasonGross** [comment]
Yes.  It is hard but doable in 8.4 with typeclasses (but not as a tactic without typeclasses).  It is much more straightforward in 8.4 with dependent subgoals.

**Comment by mikeshulman** [comment]
I think when I tried, I got stuck at dependent types.

**Comment by spitters** [comment]
Andrej, do you still have your experiments available? I think it was a nice
start.

**Comment by andrejbauer** [comment]
> Andrej, do you still have your experiments available? I think it was a nice start.

They would be severly outdated by now, there wasn't all that much to them, but they ought to be in a prehistoric version of this repository, something under `experimantal`, called `DefinableEquivalence` or some such. It's not worth digging, I am sure.
