### ISSUE TITLE
Opam

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#694]
Coq will be switching to opam for contribs and the coqbench regression test-suite
(https://coq-bench.github.io/)
Hence the following is required before we can submit HoTT as a contrib #424 .

It should also be useful for users who want to _use_, as opposed to _develop_ the library.

Here's how to set it up. Still experimental.

Here's the full instruction for Coq opam
`
https://github.com/coq/www/blob/master/pages/31.html
`
In short:
Get opam:
`
http://opam.ocaml.org/doc/Install.html
`

```
opam init --comp 4.01.0
eval `opam config env`
```

Make a special switch so that it does not interact with other coq installations

```
opam switch coq-hott --alias-of 4.01.0
opam repo add coq-released https://coq.inria.fr/opam/released
opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
```

[ HoTT will be moved here once we decide it is "stable" 
opam repo add coq-stable https://github.com/coq/repo-stable.git]

```
opam switch install coq\:hott.0.9.0
```

**Comment by mikeshulman** [comment]
What version of Coq does this use?  Our pinned version or 8.5beta or what?

**Comment by spitters** [comment]
Yes, Travis automatically updates the coq version of our coq git submodule
in the url here.
https://github.com/coq/repo-coqs/tree/master/packages/coq.hott

opam and git submodules do not work together perfectly. The opam developers
believe that git submodules are broken.
They may be right.

**Comment by mikeshulman** [comment]
There are a lot of people on the Internet who complain about git submodules, and most of the complaints seem to be that git submodules are not designed to solve the problems that most people expect them to solve.  But it seems to me that we're actually using them for their intended purpose at the moment: we really do want to pin to a specific commit of Coq, at least while Coq development is going on.  It's conceivable that once Coq 8.5 is out, we'll want to stick with that for a while.

**Comment by spitters** [comment]
Yes, it would be nice to stick to a stable version for a while, but it
won't last.
I was not saying that we should move away from submodules (yet?), just that
opam does not work with it nicely (and perhaps never will).

**Comment by JasonGross** [comment]
> What version of Coq does this use?  Our pinned version or 8.5beta or what?

#696 will make these the same.

**Comment by spitters** [comment]
This is progress towards issue #424

**Comment by spitters** [comment]
Opam packages seem to have moved [here](https://github.com/coq/opam-coq-archive/blob/b0a9bc0da6b1bbc0bf43fc3ea16429a5d64d430e/extra-dev/packages/coq-hott/coq-hott.0.9.0/opam).

**Comment by mattam82** [comment]
Why don't we have stable hott packages for opam for released versions?

**Comment by spitters** [comment]
There were problems with git submodules, which I think have been resolved, and with coq_makefile, which may now have been resolved in 8.7.

However, in any case, it seems opam should have been working since 8.6.

**Comment by mattam82** [comment]
I just copied the .dev files for 8.6 and it works out of the box, should I just submit that opam package? I'll make an 8.7 version as well.

**Comment by spitters** [comment]
Yes, please do.

from my phone

**Comment by spitters** [comment]
One can now do:
```
opam install coq-hott
```
