### ISSUE TITLE
Accidental commit

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#699]
This commit was accidental. I am trying to see how to undo it.
If you know the command by heart, please let me know.

https://github.com/HoTT/HoTT/commit/5587133cde0bfe58306bade603138e358b33ef60

**Comment by spitters** [comment]
```
git push -f origin HEAD^:master
```

**Comment by spitters** [comment]
That just made things worse...
We are now back 10 days.

**Comment by mikeshulman** [comment]
Find the hash of the correct commit, then do

git checkout master
git reset --hard HASH
git push -f upstream master

Where 'upstream' is your name for the github repository.

**Comment by spitters** [comment]
Back at Andrej's merge by using `gitk` and then
```
git  push -f origin master
```
