### ISSUE TITLE
W-types

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#701]
We don't seem to have those yet. There should be some information here
http://homotopytypetheory.org/2012/09/21/positive-h-levels-are-closed-under-w/
and here:
( Awodey, Gambino, Sojakova)
http://arxiv.org/abs/1201.3898

**Comment by mikeshulman** [comment]
I wonder whether we could make any use of AGS's code?

**Comment by kristinas** [comment]
Yes. I am planning on adding some more theorems concerning W-types in HoTT Coq.

**Comment by spitters** [comment]
Now that we have:
https://github.com/HoTT/HoTT/blob/master/theories/Types/Wtype.v
I am closing this.
