### ISSUE TITLE
EquivGroupoid?

### ISSUE THREAD

**Issue by JasonGross** [HoTT/HoTT#703]
Do we have a place for lemmas like these?  (Do we already have them?)

```coq
  Lemma equiv_right_id `{Funext} {A B} (e : A <~> B) : equiv_compose' e (equiv_idmap _) = e.
  Proof.
    apply path_equiv; reflexivity.
  Defined.

  Lemma equiv_left_id `{Funext} {A B} (e : A <~> B) : equiv_compose' (equiv_idmap _) e = e.
  Proof.
    apply path_equiv; reflexivity.
  Defined.
```

**Comment by JasonGross** [comment]
(Note: I *think* these wouldn't need funext if we had `1 @ p = p` and `p @ 1 = p` judgmentally, but I'm not completely sure.)

**Comment by mikeshulman** [comment]
Hmm, I don't recall having them.  I presume `SearchAbout` didn't find them.  Maybe in `Types/Equiv`?

**Comment by JasonGross** [comment]
`SearchAbout` did not give me anything.  But I'm not sure it really belongs in `Types/Equiv`; we can recreate all of `Basics/PathGroupoids`, but for equivalences, under the assumption of `Funext`, and that would be a pretty hefty `Types/Equiv` file.

**Comment by mikeshulman** [comment]
We *can*, but do we really need to?  However, I won't object to `theories/EquivGroupoids`.

**Comment by JasonGross** [comment]
I'm working on #691, and needed a few of these lemmas.

**Comment by mikeshulman** [comment]
Yeah, I was just saying we don't yet need *all* of `PathGroupoids` recreated for equivalences, so I don't think it would be very harmful to put just a few such lemmas in `Types/Equiv`.  But as I said, feel free to go with `EquivGroupoids` if you'd rather.

**Comment by andrejbauer** [comment]
And we can't have a super-theorem/tactic/magic-spells which convert the path versions to the equivalence versions?

**Comment by JasonGross** [comment]
@andrejbauer: We can convert the types reasonably easily with a tactic.  The proofs should actually be largely trivial, because we are lifting the structure on functions, which is all judgmental.  But do we really want to have a file full of theorems like:
```coq
Definition compose_p1 `{Funext} : $(transform (@concat_p1))$ := $(t)$.
```
?

**Comment by spitters** [comment]
Are the $s there for tactics in terms?
Can you explain the syntax?

**Comment by JasonGross** [comment]
Yes, `$(...)$` is syntax for tactics in terms.
