### ISSUE TITLE
INSTALL.txt

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#710]
Some changes INSTALL.txt. 
Just let me know if you have any suggestions before I submit a pull request. (I am not a mac user).

`autoconf` should be present on your machine
  (if not we get path-spec problems)
Should be included in the list under 1.

We could convert INSTALL.txt into markdown.

OSX
opam can be install by
   brew install opam
and then
   brew update; brew upgrade objective-caml

In step 3, we should advise -j2, where 2 is the number of cores you have on your machine.

**Comment by mikeshulman** [comment]
Is there anything we could say to tell people how to find out how many cores they have on their machine?

**Comment by andrejbauer** [comment]
On OSX? Apple menu -> About this Mac -> System Report, then look for "number of cores"

**Comment by andrejbauer** [comment]
I am pretty sure we're trying to be independent of `autoconf`.

**Comment by andrejbauer** [comment]
Do we want Opam or just the Homebrew version of ocaml? If we go for Opam, we could maybe install the correct version of Coq through Opam.

**Comment by mikeshulman** [comment]
On any OS.  I'm on linux and I don't know how to find out.

**Comment by spitters** [comment]
@andrejbauer Step 3 seems to use `autoreconf`
```
 etc/install_coq.sh
./autogen.sh
```

Yes, I think we can install the opam package for coq:hott, but then we should perhaps adapt `install_coq.sh` ? Coq-dev is still discussing on how to use opam for development.
The --root option seems to be an option.

@mikeshulman [This](http://www.cyberciti.biz/faq/linux-get-number-of-cpus-core-command/) suggests `nproc` and `lscpu`. Works for me.

**Comment by spitters** [comment]
It looks like git submodules are now better supported. Issue https://github.com/ocaml/opam/issues/1847 that I opened about this is now closed.

@JasonGross What's the status of opam on windows? Do you think we can depend on this?

**Comment by JasonGross** [comment]
I believe `-j` will automatically run with the number of cores you have (at least for makefiles).

`autogen.sh` has a fallback path for when `autoreconf` is not present.

Opam works for me on Windows, and I am willing to help people try to get it working.  It's more complicated than getting `autoreconf` on Windows; it requires installing cygwin, the ocaml packaged with cygwin (or the Coq SDK), and then building opam from source, and possibly some environment variable munging after that.

**Comment by andrejbauer** [comment]
In other words, there is no reasonable installation path for ocaml (and therefore HoTT) on Windows.

**Comment by mikeshulman** [comment]
Once we work with a released version of Coq 8.5, won't there be a binary install for that which won't require ocaml?

**Comment by JasonGross** [comment]
We should currently work fine with 8.5 beta 1, which has a binary install for Windows.  We should probably update the install files to say this.

**Comment by JasonGross** [comment]
> In other words, there is no reasonable installation path for ocaml (and therefore HoTT) on Windows.

There is a "reasonable" install path for someone already familiar with cygwin and compiling programs from source.

I may try to add relevant build scripts to get a CI bot building HoTT on Windows, a la [this Windows CI config for opam](https://github.com/ocaml/opam/pull/1764).

**Comment by spitters** [comment]
`-j` often opens starts too many processes and freezes my machine.

Recapitulating:

We could convert INSTALL.txt into markdown.

OSX
opam can be installed by
brew install opam
and then
brew update; brew upgrade objective-caml

In step 3, make -jn, where n is the number of cores you have on your machine.
On linux this can be found with nproc and lscpu. On OSX 
Apple menu -> About this Mac -> System Report, then look for "number of cores"

We have experimental opam packages to install both the correct Coq version and the library.
https://github.com/HoTT/HoTT/issues/694
However, the latter cannot be used by people using git to contribute to the library.
Moreover, opam support on windows is experimental.

We are compatible with [Coq8.5beta](https://coq.inria.fr/coq-85), so binary packages can be used. However, paths need to be set manually.
