### ISSUE TITLE
Git tutorial

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#714]
Here's a small set of hints on using git.
Would it be useful to turn this into git.md and commit it to the library?
Other can then elaborate if they want.

Elementary git usage. This is in addition to the instructions on how to set up git in INSTALL.md

USAGE 1: add + commit
To have git record your changes:
` git commit -m "description of edit" <files-you-changed>`

USAGE 2: pull
 To pull changes by others from GitHub:
 (Your local directory will still have your changes.)
 FIRST commit your changes as above, then
`git pull upstream master         `
(This is the central repo)

USAGE 3: compile + push
See [Contributing](https://github.com/HoTT/HoTT/blob/master/STYLE.md)
To push your changes to GitHub:
FIRST, commit your changes as above
SECOND, pull changes from GitHub as above, then
```
make -j2
git push origin master
```
(This is your own repo)
Now go to your github page and click create pull requests.
This will then be compiled (again) by Travis and reviewed by the developers.
After github discussion, and possible updates of the pull request, 
one of them else will pull your request.

*Only very minor* changes (spelling) can be pushed directly.
You can also edit directly in the github interface
`git push upstream master`

Which files did I change since the last commit?
`git status`

What changes did I make in those files?
`git diff`

Who wrote in this file?
`git praise`

Rewrite your master branch so that any commits of yours that
aren't already in upstream/master are replayed on top of that
other branch. See also [STYLE](STYLE.md)

`git rebase upstream/master`

If you've rebased your branch onto upstream/master you may need to force the push in order to push it to  your own forked repository on GitHub. You'd do that with:
`git push -f origin master`

Stash your local changes
`git stash`
When all else fails, get a fresh copy from your own clone on github.
`git reset --hard origin/master `

We have our own version of Coq in a git submodule. When it is updated upstream run:
`etc/install_coq.sh `
or by hand:
`cd coq-HoTT && make clean `
or, if that's not enough, 
`cd coq-HoTT && git clean -xfd`
Then
`git submodule update && cd coq-HoTT && configure -local && make -j2 -k coqide coqlight`

For more, there are [plenty][1] of [tutorials][2] online
[1]: https://www.atlassian.com/git/tutorials/
[2]: http://git-scm.com/docs/gittutorial

**Comment by andrejbauer** [comment]
I think you need to `git add remote upstream ...` before you can mention `upstream`.
