### ISSUE TITLE
"Anomaly: Incorrect universe" when trying to control size of an inductive type

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#722]
[bug 3808](https://coq.inria.fr/bugs/show_bug.cgi?id=3808) appears to only happen with hoq, but I can't yet figure out why; none of the usual `Set`s in our modified stdlib seems to be the culprit.  Any ideas would be welcome...

**Comment by JasonGross** [comment]
Have you tried -indices-matter?  Have you tried -coqlib coq/theories (or is
it -coqlib coq?) without -indices-matter?

**Comment by mikeshulman** [comment]
Yeah, of course it's `-indices-matter`; I realized that myself 5 minutes ago.  (-:
