### ISSUE TITLE
Old proofs don't work anymore under the new version of HoTT

### ISSUE THREAD

**Issue by kristinas** [HoTT/HoTT#725]
Dear all,

I updated to the newest version of HoTT/Coq and my proofs suddenly do not work anymore. Namely, i had a lot of "apply transitivity with X" statements that no longer go through. Now I get an error saying "Not the right number of missing arguments (expected 0)". What is going on?

Kristina

**Comment by andrejbauer** [comment]
For better diagonisis, please confirm that this is hapenning to your current master branch, and please point to a couple of cases of this. The library has changed quite a bit because we incorporated improvements to Coq (polymorphic universes, additional eta rules, primitive projections, etc.)

**Comment by kristinas** [comment]
The repository I am using is https://github.com/kristinas/HoTT which is up to date according to Github.
The transitivity tactic fails every time, for example:

Lemma fail : Unit <~> Unit.
Proof.
apply transitivity with Unit.
admit.
Defined.

The above fails in the first line. Not sure why because previously this tactic worked.

I know the library has changed quite a bit but as a user I expect it to stay compatible with proofs that are barely 6 months old.

**Comment by mikeshulman** [comment]
First of all, `apply transitivity` is not using the transitivity *tactic* but rather passing the function `transitivity` to the `apply` tactic.  The `apply` tactic is known to be quite broken in current Coq and I would recommend not using it for anything very complicated, including a `with` clause.  One substitute is to use use the actual `transitivity` tactic, e.g.

```coq
Lemma fail : Unit <~> Unit.
Proof.
transitivity Unit.
all:admit.
Defined.
```

For better or for worse, 6 months is an eternity in the life of the library at present.

**Comment by kristinas** [comment]
@mikeshulman I can certainly see that ... there are plenty of places where my proofs now fail. It is frustrating to say the least and if I could, I would switch back to the old version of the library since this one seems to be worse, from my point of view: there are places where I now have to supply arguments explicitly when I didn't have to before; I now have to simplify before calling some lemmas when I didn't have to before, etc.

Here is another one: The line
Check ({ l : Unit & { n : Unit & Unit }}).
produces a syntax error in a new file. Why is this?

**Comment by JasonGross** [comment]
Perhaps you forgot to `Require Import Basics` or `Require Import HoTT.Basics.Overture`?

**Comment by JasonGross** [comment]
@kristinas, if you switch from `apply` to `refine`, that might fix some of the arguments problems?

**Comment by JasonGross** [comment]
Alternatively, switch from `apply` to `rapply`.

**Comment by kristinas** [comment]
@JasonGross At the beginning of the file I have Require Import HoTT so this should include all the necessary files, no?
Regarding rapply: this indeed eliminated the issue for supplying explicit arguments in one place, thanks!

**Comment by mikeshulman** [comment]
Ugh, sorry Kristina, that's my fault.  #726.

**Comment by mikeshulman** [comment]
I'd be interested to see some more examples of where the current library broke your code.  I'm curious in particular whether it can be blamed on changes in our library or on changes in Coq; although it might be tricky to find out since the current library won't compile with an older Coq or vice versa.

**Comment by JasonGross** [comment]
@kristinas, you can simply add a space, so it's `{ l : Unit & { n : Unit & Unit } }`, and then it will work without that PR.

Are you sure you're using the updated version of Coq?

**Comment by kristinas** [comment]
@JasonGross Oh I see. That seems to fix it, yes. But also Mike was doing something in #726; maybe that will eliminate the need for the extra space?

The two (other) weirdest places where the code broke are the universe inconsistency I now get and the need for simplification before calling apply equiv_functor_sigma_id; intro n. These can be seen in the Coq file I sent around.
Another thing is the need for rapply instead of apply (line 52 in the same file).

I do not have a separate Coq installed. I just followed the steps in the INSTALL file for the HoTT library, in particular 

etc/install_coq.sh
./autogen.sh
./configure COQBIN="`pwd`/coq-HoTT/bin"
make

I have no idea which version of Coq this generated.

**Comment by JasonGross** [comment]
#726 should, hopefully, eliminate the need for a space

The universe inconsistency should not happen.  It is a bug in Coq.  I am tracking it down.  Note that `pose (@paths C)` works fine, as does `pose (@paths C). Check (@paths C).`  So it seems to be a subtle bug in `Check`.

In the file you sent, removing the `simpl` does not change the behavior.  Did you forget to put back what you had previously admitted?

Needing `rapply` instead of `apply` is a problem on Coq's side.  

The question I was asking was: did you follow these steps after the most recent version of the library you got, or did you do this a long time ago?

What does `./hoqc --version` say, and what does `(source ./hoq-config; echo | $COQTOP -nois)` say?

**Comment by kristinas** [comment]
Thanks for your help Jason!

The universe inconsistency also arises when I call a certain lemma, which is how I found it. It also occurs when calling Check (@paths C) because there might be the same underlying process which has a bug.

I sent you the original version of the file. It fails at line 57 with an error "Error: No applicable tactic.".
This is the original problem I had. I tried to figure out why it doesn't go through by calling Check on various subterms until I arrived at "Check (@paths C)" failing.

Also, if we remove the "simpl" at the end of line 47, line 50 fails. I didn't realize the truncated file I sent around does not have that issue, thanks for pointing that out.

Regarding the HoTT library, I reinstalled everything yesterday after my repo was found to be corrupted. So I should have the newest version of everything.

Running ./hoqc --version produces

The Coq Proof Assistant, version 8.5beta1 (February 2015)
compiled on Feb 22 2015 3:11:42 with OCaml 4.01.0

and  (source ./hoq-config; echo | $COQTOP -nois) produces

Welcome to Coq 8.5beta1 (February 2015)

Coq < Coq <

**Comment by JasonGross** [comment]
Here are replacements that work:
```coq
refine (equiv_functor_sigma' (equiv_inverse (equiv_path_forall _ _)) _).
erapply (equiv_functor_sigma' (equiv_inverse (equiv_path_forall _ _))).
assert Funext by admit; apply (equiv_functor_sigma' (equiv_inverse (equiv_path_forall _ _))).
```
or was it a different line you were having trouble with?

**Comment by kristinas** [comment]
Oh thanks a lot, yeah, that fixes the first problem! What is the reason why regular apply doesn't work anymore? It seems it has something to do with function extensionality, based on the third alternative you proposed, but then according to the first alternative, it seems Coq should have access to an instance of it. 
What does (e)rapply do?

And do you by any chance also know what causes the problem in line 47?

**Comment by JasonGross** [comment]
The first one leaves a goal of `Funext`, the second leaves an evar (speaking of which, here's another one that works: (`eapply`)
```coq
eapply (equiv_functor_sigma' (equiv_inverse (equiv_path_forall _ _))).
```
There's a description of `erapply` [here](https://github.com/HoTT/HoTT/blob/bdece51e2443e720da256aa5978e05f881532d80/STYLE.md#available-tactics).

I removed the `simpl` from line 47 and didn't run into any problems?  Do you have a version of the file displaying the problem you have (that doesn't depend on your PR)?

**Comment by kristinas** [comment]
Oh, it may be just a CoqIDE issue then - are you using Proof General? 
When I remove the simpl and hit line 50, I get an error
"Anomaly: variable U unbound. Please report.".
It allows me to go further, though. 

I am not sure what causes this or where to report it.

**Comment by JasonGross** [comment]
Try to reproduce it with hoqc, if you can.  Then one of us can minimize it with https://github.com/JasonGross/coq-tools, and report it on the official bug tracker.

**Comment by kristinas** [comment]
Also, the problem with (@paths C) remains, although I do not particularly care. But it is a bit disconcerting.

**Comment by kristinas** [comment]
The anomaly problem does not arise with hoqc.

**Comment by JasonGross** [comment]
[Bug report on the universe inconsistency](https://coq.inria.fr/bugs/show_bug.cgi?id=4089)

**Comment by JasonGross** [comment]
If you can, see if you can track down the anomaly to something with CoqIDE and not just hoqide?  But it might be annoying to do so.

**Comment by kristinas** [comment]
Hmm I don't know, I can't seem to reproduce it very easily. Is there someone in charge of HoqIDE?

**Comment by mikeshulman** [comment]
Have you verified that it doesn't happen with command-line hoqtop either?

**Comment by mikeshulman** [comment]
(Also, that sure is a strange bug!)

**Comment by kristinas** [comment]
How do I run hoqtop? I ran ./hoqc on my file and it did not complain.

**Comment by mikeshulman** [comment]
`./hoqtop <File.v` or `./hoqtop -load-vernac-source File.v`

**Comment by kristinas** [comment]
It doesn't happen there either.

**Comment by mikeshulman** [comment]
Bizarre.  I don't suppose there's any way for the bug minimizer to work on hoqide?  (-:

**Comment by kristinas** [comment]
Can either of you at least reproduce it?

**Comment by mikeshulman** [comment]
Can you send me the file?

**Comment by kristinas** [comment]
Sent.

**Comment by mikeshulman** [comment]
Thanks.  Now can someone remind me how to get hoqide?  Right now it tells me `coqide with -indices-matter was not found during configuration.`  I tried `cd coq-HoTT && make coqide` but that says "nothing to be done".  The only documentation I've found for hoqide in our library is "you can also use hoqide" and "At the moment there is no `hoqide`".

**Comment by JasonGross** [comment]
You need to run `./configure` again with `COQBIN` or `PATH` pointed at something that contains `coqide`.

**Comment by mikeshulman** [comment]
do you mean the configure of our library or the configure of coq?

**Comment by JasonGross** [comment]
Of our library.

**Comment by mikeshulman** [comment]
ok, and where do I get "something that contains coqide"?

**Comment by JasonGross** [comment]
Does `coq-HoTT/bin` contain `coqide`?  If not, you have to re`configure` in such a way that it finds gtk and builds coqide.

**Comment by JasonGross** [comment]
@kristinas: Yes, I can reproduce the anomaly.  I shall note that it happens on *every* command after the relevant point, both moving upwards and moving downwards, so I suspect the anomaly occurs in the process of CoqIDE querying the state of the goal.  I don't really have time to track it down at the moment.

**Comment by mikeshulman** [comment]
Ok, well then there's probably not much point in my also trying to reproduce it, since I don't have time to track it down any further either.

**Comment by JasonGross** [comment]
[Feature request for enabling automatic CoqIDE-bug-tracking](https://coq.inria.fr/bugs/show_bug.cgi?id=4090)

**Comment by kristinas** [comment]
Thanks a lot, at least I know it is not something with my code.

**Comment by kristinas** [comment]
More fun: Going past the problems you managed to solve, there is another anomaly happening at line 75 of the file; this time the offending unbound variable is k.
More to the point, this anomaly causes HoqIDE to not display the current goal in the next few lines, so I have no idea what is going on when in line 85, there is a genuine error.

This error also wasn't there under the previous version of HoTT. Under hoqc, we get the error

File "../hinitiality/two.v", line 86, characters 4-55:
Error:
Found no subterm matching "(equivcompmor U V k (l; (l0, l1)))
                             ((equivcompmor U V k (l; (l0, l1)))^-1 ?M5834)" in the current goal.

So this is another place where the new library breaks my code. I decided the best thing is to give up on hoqide altogether and install proof general. How do I do this? Do I need emacs with it? The installation instructions are not very clear on this.

**Comment by JasonGross** [comment]
You can download ProofGeneral [here](http://proofgeneral.inf.ed.ac.uk/devel); you will need to install emacs first.

**Comment by JasonGross** [comment]
@mattam82 has fixed the universe inconsistency with `Check` in the latest version of Coq trunk.

**Comment by kristinas** [comment]
I see but that is not the one bundled with HoTT, no?

**Comment by mikeshulman** [comment]
Right, but it's not hard to get that version manually.

**Comment by kristinas** [comment]
https://coq.inria.fr/bugs/show_bug.cgi?id=4094

**Comment by JasonGross** [comment]
@kristinas: Good progress, but unfortunately that file isn't stand-alone; it still has some `Require Import`s, and depends on the custom standard library of HoTT (e.g., it doesn't `Set Universe Polymorphism` itself).

**Comment by mikeshulman** [comment]
Are you using coq-bug-finder?

**Comment by kristinas** [comment]
No I did it by hand. Can't I just pack all the files into a zip folder?

**Comment by mikeshulman** [comment]
The point isn't just that they don't want to go download the HoTT library; the point is that they want a *small* example so that they don't have to root through the whole HoTT library to track down the bug.  coq-bug-finder systematically puts all the code into one file and then eliminates pieces that don't contribute to the bug.

**Comment by kristinas** [comment]
I do not have python. I am honestly just thinking it is easier to just revert to the old working version of HoTT & Coq.

**Comment by mikeshulman** [comment]
Easier in the short run, perhaps, but I don't think in the long run.  Python is easy to get.

**Comment by kristinas** [comment]
Also, it might take weeks before they even look at it and there are other bugs too.

**Comment by JasonGross** [comment]
I will minimize this bug, and will submit an update to the report on the bug tracker when the bug-minimizer finishes.  You can get rid of the anomaly by not `set`ing `F` the way you do; I suspect CoqIDE gets confused every time it tries to display your definition of `F` (something to do with your type annotation perhaps?)

**Comment by kristinas** [comment]
But this bug only occurs in CoqIDE. I think you said at one point that the bug minimizer doesn't catch those?

**Comment by mikeshulman** [comment]
If this is the bug that only occurs in CoqIDE, you should mention that in the Coq bug report!  Otherwise the developers won't know how to reproduce it.

**Comment by kristinas** [comment]
I included the bug in the category IDE (but maybe it is a good idea to emphasize it even further in the report). Thanks, Jason!

**Comment by JasonGross** [comment]
Although the bug-minimizer can't check that the bug remains after each change it makes, I'm working on the educated guess that if I don't change the body of `F`, the bug will still be there.  It can check that the body of `F` doesn't change, making it track the error given by `revert F; match goal with |- ?G => fail 1 G end.`

**Comment by kristinas** [comment]
Also, there is a bug which occurs after the anomaly (cannot find the occurrence of the term to rewrite) but thanks to the anomaly I cannot see what is happening because the goal isn't updated. That bug also occurs in hoqc. Jason said he will look at it when he has time (thanks again).
I will try to set up proof general tomorrow, that one at least doesn't have anomalies I hope.

**Comment by kristinas** [comment]
OK so with the help of Bas I have been able to set up PG and found out why some of these bugs arose.
Apparently the behavior of simpl has been changed and it no longer unfolds the definitions I want it to unfold. Namely, if I have a goal "F (a,b)" and F := fun u => match u with (a,b) blah end, the goal is not reduced to blah. I have to explicitly say unfold F before I attempt to rewrite. Not sure why change has been made but at least I know how to fix it.
Btw, PG is excruciatingly slow so I will only use it for diagnostics. I do not think my code is crazy complicated but alas...
Rearding the trunk version of Coq: my attempt at installing this new version was to call

etc/install_coq.sh
./autogen.sh
./configure COQBIN="`pwd`/coq-HoTT/bin"
make

according to the HoTT library instructions. Does this install the trunk version automatically or do I have to git pull something before? Because I am still getting universe inconsistencies when calling Check.

**Comment by mikeshulman** [comment]
Have you tried `cbn` instead of `simpl`?  `simpl` is really broken and arguably shouldn't be used any more.

`install_coq.sh` always grabs the pinned version of Coq, not the trunk.  To get trunk you have to do something like `cd coq-HoTT && git pull origin trunk && git clean -xfd && ./configure -local && make coqlight coqide`.

**Comment by kristinas** [comment]
Yes cnb doesn't unfold it either. Is there a documentation somewhere that says which tactics are broken and should not be used anymore?

**Comment by mikeshulman** [comment]
Sadly, not that I know of.  But if we manage to do #709, this one won't matter.

**Comment by kristinas** [comment]
When I do
cd coq-HoTT && git pull origin trunk && git clean -xfd && ./configure -local && make coqlight coqide
and then

./autogen.sh
./configure COQBIN="`pwd`/coq-HoTT/bin"
make

I get an error 

File "./theories/Types/Sigma.v", line 317, characters 0-255:
Anomaly: Uncaught exception Retyping.RetypeError(3). Please report.
make: *** [theories/Types/Sigma.vo] Error 1

**Comment by mikeshulman** [comment]
I never do autogen/configure in the HoTT directory since my first clone, just make (occasionally with make clean first).  Not sure whether that's your problem, but you could try make clean and then just make.

**Comment by JasonGross** [comment]
That sounds like you are using .vo files compiled with a different version
of Coq, so, yes, make clean, then make.  Or `find theories coq -name "*.vo"
| xargs rm`.

-Jason

**Comment by kristinas** [comment]
I do not know how to make the trunk version work on my computer. If I install it as above, I can no longer load HoqIDE. I cannot even perform the autogen and configure steps, it always tells me no such file or directory.

**Comment by kristinas** [comment]
When trying to run python find-bug.py hinitiality/two.v output.v I get

Traceback (most recent call last):
  File "find-bug.py", line 3, in <module>
    from replace_imports import include_imports
ImportError: No module named replace_imports

**Comment by JasonGross** [comment]
Perhaps you downloaded find-bug.py rather than cloning the whole
repository?  find-bug.py needs most of the other python scripts in that
repo to be in the same folder that it is in.

**Comment by mikeshulman** [comment]
What is the file or directory that there is "no such"?

**Comment by kristinas** [comment]
The "no such" thing does not occur anymore after I cleaned up everything and ran the scripts again. 
The problem with the trunk Coq is now twofold: 
1) ./hoqide displays the error message 

Connection with coqtop failed!
Command was: '/home/kristina/HoTT/coq-HoTT/bin/coqtop' -batch -ideslave '-no-native-compiler' '-coqlib' '/home/kristina/HoTT/coq' '-R' '/home/kristina/HoTT/theories' 'HoTT' '-indices-matter'
Answer was: 
Exception was: Coq.WrongExitStatus("WEXITED 1")

2) When running make clean and then make in the HoTT folder, the library doesn't compile due to the error 

File "./theories/Types/Sigma.v", line 317, characters 0-255:
Anomaly: Uncaught exception Retyping.RetypeError(3). Please report.
make: *** [theories/Types/Sigma.vo] Error 1


Neither of the above occurs with the pinned version of trunk. However, that one has a universe inconsistency bug when calling the transitivity tactic to prove that two types are equivalent. I am now trying to minimize that one using Jason's tools.
I just thought that maybe the trunk version doesn't have that problem anymore but I just can't get that one running.

**Comment by mikeshulman** [comment]
I get (2) as well.  This looks to me like a bug introduced recently in Coq trunk; we should minimize (and perhaps bisect) and report it as well.

**Comment by kristinas** [comment]
@JasonGross Thanks, for some reason I assumed the find-bug.py was a standalone python script, my bad. Now I cloned the repository; however, when I call python find-bug.py buggyfile.v smallbuggyfile.v
I get a file which starts

Module Top_DOT_two.
Module Top.
Module two.
Import HoTT.

and then just copies buggyfile.v verbatim. This is not what we want, right? 
Also it doesn't compile because it says HoTT is not a module.

**Comment by mikeshulman** [comment]
you need something like `-R HoTT .`

**Comment by kristinas** [comment]
But isn't the whole point of minimization that we do not want to include the whole HoTT library there?

**Comment by mikeshulman** [comment]
The way minimization works is to first include the whole library and then progressively remove the parts that aren't needed to reproduce the bug.

**Comment by kristinas** [comment]
I do not understand what I am supposed to do exactly. I have a folder coq-tools in my home directory, which has the script find-bug.py. I also have a file two.v which is buggy. I moved it to the coq-tools directory.
Now I go to the coq-tools directory and say
python find-bug.py -R HoTT . two.v output.v
Is this the correct way to call the script?

I stil gives me the same output.v file.

**Comment by JasonGross** [comment]
Try putting `two.v` in `theories/` of HoTT, and then doing
```bash
cd /path/to/HoTT
make
cd theories
../hoqc two.v
python /path/to/find-bug.py -R HoTT . two.v output.v --coqc ../hoqc --coqtop ../hoqtop
```

You will have a better experience if you do `Require Import Basics Types` or whichever particular components you need, rather than, `Require Import HoTT`, so it doesn't need to build the entire library a few thousand times.

**Comment by kristinas** [comment]
The file still starts with

(* File reduced by coq-bug-finder from original input, then from 42 lines to 32 lines *)
(* coqc version 8.5beta1 (March 2015) compiled on Mar 1 2015 6:38:49 with OCaml 4.01.0
   coqtop version 8.5beta1 (March 2015) *)
Require HoTT.HoTT.
Import Basics.

Unless you want to try to minimize it yourself (if so I will send you the file), I will pack everything in a zip folder and submit it to Bugzilla.

**Comment by JasonGross** [comment]
Sorry, I flipped it, it's `-R . HoTT`, not `-R HoTT .`.

**Comment by kristinas** [comment]
Oh now it works, thanks a lot! The file starts with

Module Export HoTT_DOT_Basics_DOT_Overture.
Module Export HoTT.
Module Export Basics.
Module Export Overture.

Is this ok?

**Comment by JasonGross** [comment]
It should start with a comment up top, above that; you need to let it run for a while to minimize the file; the devs won't appreciate a 5000 line-long file.

**Comment by JasonGross** [comment]
But otherwise, yes, that's what it should initially start with.

**Comment by kristinas** [comment]
It';s just 103 lines because I only included Overture.
That is okay no?

**Comment by JasonGross** [comment]
That should be fine, though it should have managed to minimize away those initial modules if you let it run for a few minutes?

**Comment by JasonGross** [comment]
(It will ask you two questions; you should answer `y` to both of them)

**Comment by kristinas** [comment]
Yes. It finished running and those module declarations were still there. But I removed them so it;s fine.

**Comment by kristinas** [comment]
https://coq.inria.fr/bugs/show_bug.cgi?id=4096

**Comment by kristinas** [comment]
OK so as Matthieu said the above problem with transitivity can be avoided using equiv_compose' instead. As a user I would ideally like to use transitivity and have it work but maybe there is some issue for why it has to be homogeneous.
Regardless, I find it a bit unpleasant that equiv_compose' inverts the order of the subgoals, i.e., we first have to prove B <-> C before proving A <-> B.

**Comment by mikeshulman** [comment]
I don't fully understand what's going on, but I suspect that we can't make `transitivity` heterogeneous when applied to `Equiv`, because it has to be an instance of a general notion of "transitivity" that applies to a relation on any type, and for a general relation on a general type there is no "heterogeneous" version.

**Comment by mattam82** [comment]
Indeed, the Transitive class cannot be massaged to do that easily. However using universe annotations you can do the necessary lifting so that the homogeneous version Transitive Equiv(@{i i}) can be used.

**Comment by kristinas** [comment]
I just applied the equiv_compose' and equiv_inverse lemmas whenever I needed (universe annotations seem scary to me).  Thanks for everyone's help.
While we're at it, did we figure out why the library does not compile with the trunk version of Coq?

**Comment by JasonGross** [comment]
That was [bug 4097](https://coq.inria.fr/bugs/show_bug.cgi?id=4097), which Matthieu has since fixed (thanks!).

**Comment by JasonGross** [comment]
Unfortunately, @mattam82, there seem to be more retyping errors; I'll make bug reports soon.

**Comment by JasonGross** [comment]
@mattam82, do you know why all of the sudden there are lots of `Anomaly: Uncaught exception Retyping.RetypeError(3). Please report.` on things like `rewrite transport_forall_constant` and `apply path_forall`?

**Comment by mattam82** [comment]
Nope, but probably a wrong environment somewhere.

Le lundi 2 mars 2015, Jason Gross <notifications@github.com> a écrit :

> @mattam82 <https://github.com/mattam82>, do you know why all of the
> sudden there are lots of Anomaly: Uncaught exception
> Retyping.RetypeError(3). Please report. on things like rewrite
> transport_forall_constant and apply path_forall?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HoTT/HoTT/issues/725#issuecomment-76818015>.
>


--

**Comment by spitters** [comment]
Can this issue be closed?

**Comment by kristinas** [comment]
yes
