### ISSUE TITLE
Strings in Coq-HoTT

### ISSUE THREAD

**Issue by maggesi** [HoTT/HoTT#739]
Hi,

I'm trying to define strings in Coq-HoTT.  Following the style of the Coq Standard Library (see [Ascii](https://coq.inria.fr/distrib/current/stdlib/Coq.Strings.Ascii.html) and [String](https://coq.inria.fr/distrib/current/stdlib/Coq.Strings.String.html)) I declare a type Char for ascii codes:
```coq
Inductive Char : Type1 := ascii (_ _ _ _ _ _ _ _ : Bool) : Char.
```
and an inductive type for strings:
```coq
Inductive String : Type1 :=
  | empty : String
  | string (c : Char) (cs : String) : String.
```

Most things work without problems.  But I have run into something like universe inconsistency when I try to prove a discrimination lemma:
```coq
Definition ne_head (x y : Char) (xs ys: String)
: x <> y -> string x xs <> string y ys.
```
The full code follows, the error arises at the final "Defined".

Can you clarify the problem and suggest a way to get around this?

Marco

```coq
Require Export HoTT.
Require Export Types.Bool.

Local Unset Elimination Schemes.
Inductive Char : Type1 := ascii (_ _ _ _ _ _ _ _ : Bool) : Char.
Scheme Char_ind := Induction for Char Sort Type.
Scheme Char_rec := Minimality for Char Sort Type.

Local Unset Elimination Schemes.
Inductive String : Type1 :=
| empty : String
| string (c : Char) (cs : String) : String.
Scheme String_ind := Induction for String Sort Type.
Scheme String_rec := Minimality for String Sort Type.

Definition head_type (s : String) : Type :=
  match s with
  | empty => Unit
  | string _ _ => Char
  end.

Definition head (s : String) : head_type s :=
  match s return head_type s with
  | empty => tt
  | string c _ => c
  end.

Check (fun (x:Char) (xs:String) => @apD String head_type head (string x xs)).

Definition ne_head (x y : Char) (xs ys: String)
: x <> y -> string x xs <> string y ys.
intros ne H.
apply ne.
change (head (string x xs) = head (string y ys)).
destruct H.
reflexivity.
Defined.
```

**Comment by JasonGross** [comment]
One issue is that `destruct` is creating an ill-typed term; this is a bug in Coq I am now tracking down.

A separate issue is that what you're doing with `destruct H` is invalid.  If you replace it with a call to `rewrite H` or `pattern (string y ys)`, you'll see that your goal becomes ill-typed when you do this.

**Comment by JasonGross** [comment]
What made you think that this was a universe inconsistency?

**Comment by maggesi** [comment]
Ah, I see.
The fact that destruct worked without raising type errors took me on the wrong track.

**Comment by JasonGross** [comment]
I've reported [bug 4160](https://coq.inria.fr/bugs/show_bug.cgi?id=4160), and will thus close this issue.  Feel free to reopen or make a new one if you run into more issues.
