### ISSUE TITLE
Bug in pegged version of Coq, fixed in current v8.5 tip

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#758]
The version of Coq currently pegged for HoTT (8.5 beta, Coq/Coq@eaa3d0b) has a bug involving universe constraints, mutual fixpoints, and `Admitted`.  A MWE is below; it’s a bit problematic as it breaks the recommended replacements for `admit`.

However, it’s fixed in the current tip of branch v8.5 (8.5 beta 2, Coq/Coq@c4ffe2).  Any reason not to bump the pegged version?

```
Record setoid : Type := { setoidbase :> Type }.

Definition TypeAsSetoid : setoid := Build_setoid (Type).

Fixpoint
  mutual_1 (EE : TypeAsSetoid) (e : nat) : nat
with
  mutual_2 (EE : TypeAsSetoid) (e : nat) : nat.
Proof.
Admitted.
```

This fails with the message:

```
Toplevel input, characters 15-24:
Error: Unsatisfied constraints: Top.16 < Top.17
 (maybe a bugged tactic). *
```

Works fine with `Admitted.` replaced by `exact e. exact e. Defined.`

**Comment by spitters** [comment]
I don't know of a reason not to bump.

**Comment by peterlefanulumsdaine** [comment]
Oops!  In trying to bump, I find I was mistaken, and the bug hasn’t been fixed; I had just been forgetting to turn on universe polymorphism when testing it.  So I’ve reported it as [bug 4244](https://coq.inria.fr/bugs/show_bug.cgi?id=4244), and I guess we can reopen this issue when/if it gets fixed.
