### ISSUE TITLE
admit broken

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#761]
In the current library, the tactic `admit` fails with `Anomaly: cannot find Coq.Init.Logic.proof_admitted`.  Did we decide what to do about this?

**Comment by JasonGross** [comment]
Can we update the submodule of Coq to 8.5beta2?

**Comment by mikeshulman** [comment]
I don't have time to experiment with it right now, do you?

**Comment by JasonGross** [comment]
No, I don't, not right now.

**Comment by spitters** [comment]
[Coq Bench](https://coq-bench.github.io/clean/Linux-x86_64-4.02.1-1.2.1/unstable/8.5.dev/hott/0.9.0.html) shows that it compiles with [8.5-dev](https://github.com/coq/repo-coqs/tree/master/packages/coq.8.5.dev)
which may be 8.5beta2.

**Comment by mikeshulman** [comment]
We are now running 8.5beta2.
