### ISSUE TITLE
Why is "x < y" a Notation?

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#762]
In working with natural numbers, I'm finding it somewhat confusing that `m < n` is a `Notation` for `m.+1 <= n` rather than a `Definition`.  For instance, if I have a hypothesis `m <= n` and I do `induction m`, then in the inductive step my hypothesis suddenly starts displaying as `m < n` instead of the `m.+1 <= n` that I expected.  I find this confusing.  I see the advantage of having `m < n` and `m.+1 <= n` _judgmentally_ equal, but it feels unnatural to me to have them _syntactically_ equal.  I presume this is one of the things we borrowed from ssreflect.  Is there a good reason for it?

**Comment by JasonGross** [comment]
It is [borrowed from ssreflect](http://ssr.msr-inria.inria.fr/doc/ssreflect-1.5/Ssreflect.ssrnat.html#:nat_scope:x_'<'_x).  You can ask on the ssr mailing list, ssreflect@msr-inria.inria.fr, for more insight?

**Comment by mikeshulman** [comment]
According to Assia, it makes some proofs shorter because some things can be proven without unfolding and `apply` can apply lemmas about `<=` to goals involving `<`.  I think I would argue that for us, the disadvantage in terms of user confusion outweighs the advantage of slightly shorter proofs.  Any other opinions?

**Comment by andrejbauer** [comment]
My opinion is that we need to close more issues one way or another. So, I agree with any solution that closes the issue.
