### ISSUE TITLE
errors in _CoqProject

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#770]
It appears that if `_CoqProject` contains a nonexistent file, then `make` will silently stop when it encounters that file.  Can we make it give an error message?

**Comment by JasonGross** [comment]
You can get the list of non-existent files with `$(filter-out $(wildcard $(ALL_VFILES)),$(ALL_VFILES))`.  So if you update configure.ac to have something like this:
```bash
include_snippet='
ifeq ($(filter-out $(wildcard $(ALL_VFILES)),$(VFILES)),)
error-if-not-exist::
	echo "The files $(filter-out $(wildcard $(ALL_VFILES)),$(ALL_VFILES)) do not exist, but are in _CoqProject"
	exit 1
else
error-if-not-exist::
endif
'
```
and then make the .v.d files depend on this target, or something, that should do it.  I haven't tested most of this.

**Comment by ejgallego** [comment]
Isn't this an upstream / Coq issue? Anyways I think no point on worrying too much, this will be solved once `coq_dune` lands.

**Comment by Alizter** [comment]
Is this still an issue?

**Comment by Alizter** [comment]
Coq seems to now give an error message when encountering a nonexistent file:

```
make: *** No rule to make target 'theories/Foobar.v', needed by 'theories/Foobar.vo'.  Stop.
```

It also ignores things that don't have `.v` attached to them.

Therefore I am closing this issue.
