### ISSUE TITLE
Bug 3811 is fixed

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#779]
coq/coq#3811
apparently.  Once we bump Coq again, we can test this and remove the workarounds.

**Comment by spitters** [comment]
@mikeshulman meanwhile we have bumped Coq. However, I don't really know what this is about.
I am looking for something else at the moment.

**Comment by Alizter** [comment]
We need to only update ReflectiveSubuniverse.v

**Comment by Alizter** [comment]
What exactly needs to be done here?
