### ISSUE TITLE
How to implement the propositional resizing axiom?

### ISSUE THREAD

**Issue by jeshecdom** [HoTT/HoTT#783]
I am in need of using the propositional resizing axiom in a coq project. I need an impredicative hProp universe.

I tried [naively] writing the following, by looking at how function Lift is implemented in "Basics/UniverseLevel.v":

----------------------------------------------------------------------------------------------
Definition LiftProp (A: hProp@{i}) : hProp@{j} 
 := Eval hnf in let enforce_lt := Type@{i} : Type@{j} in A.

(* We state the propositional resizing axiom, which says that "LiftProp" 
is an equivalence. *)
Axiom LiftProp_is_equiv : forall, IsEquiv LiftProp.

(* So, the inverse of the equivalence should be our proposition lowering function. *) 
Definition LowerProp := @equiv_inv _ _ LiftProp LiftProp_is_equiv.

----------------------------------------------------------------------------------------------

.... But LowerProp does not work, as exemplified in the last line of the following coq file (poset_test.v):

https://drive.google.com/file/d/0B9Xx0afoFNzxOEJYQWFyTm8yLWM/view?usp=sharing

If you look at the coq file provided in the link, the last line fails to unify as I am trying to build the following function:

fun (F: (S -> hProp) -> hProp) (x: S) => hexists (fun A: S -> hProp => F A * A x)

Where "S: hSet" is already given. In other words, the function is representing the union of a family "F" of subsets of "S" (Here, a subset of "S" is represented by a function "S -> hProp"). It fails to unify  because the hProp level of the "hexists" is strictly higher than the hProp level of the terms "F A" and "A x", but, at that point in the coq script, it is required that the hProp level of the "hexists" be the same as the hProp level of the "A x". In other words, we require to resize the hProp level of the "hexists".

So, when I try to use the LoẁerProp function described above:

fun (F: (S -> hProp) -> hProp) (x: S) => 
                                  LowerProp (hexists (fun A: S -> hProp => F A * A x))

I still get a universe inconsistency error.

Any suggestions on how to implement the propositional resizing axiom properly? Maybe I made a trivial mistake in my declarations of the LowerProp function or a universe level variable is missing somewhere?

I'll appreciate any help you could provide.
Thank you.

**Comment by mikeshulman** [comment]
A little while ago on the HoTT mailing list I suggested this:

```coq
Axiom propresize : forall (A : Type) {H : IsHProp A}, Type.
Axiom equiv_propresize : forall (A : Type) {H : IsHProp A},
                           propresize A <~> A.
```

With universe polymorphism on, it doesn't even require universe annotations!

```coq
Set Printing Universes.
About propresize.
==>
propresize :
forall A : Type@{Top.149}, IsHProp A -> Type@{Top.151}
(* Top.149
  Top.151 |=  *)
```

In other words, it takes an hprop in one universe and produces a type
in some other universe, for any choices of those two universes.  The
second axiom then says that in all such cases the result is equivalent
to the original hprop.  Would this be sufficient for your needs?

**Comment by jeshecdom** [comment]
Awesome!! It works! Thank you! =)
