### ISSUE TITLE
Merging natural numbers as a space and as a type

### ISSUE THREAD

**Issue by andrejbauer** [HoTT/HoTT#790]
I am replying to @marcbezem's post in #788. The discussion should be a separate issue:

> It is good to discuss this before I do something. Here are two examples:
> 
> Types/Nat.v has Definition nat_plus_comm (n m : nat) : n + m = m + n.
> https://coq.inria.fr/library/Coq.Arith.Plus.html has Lemma plus_comm : forall n m, n + m = m + n.
> 
> Both https://coq.inria.fr/library/Coq.Arith.Factorial.html and Types/Nat.v have
> Fixpoint factorial (n : nat) : nat
> := match n with
> | 0 => 1
> | S n => S n \* factorial n
> end.
> 
> There might be subtle differences (Qed vs Defined, not here).
> I have not yet tested/changed anything. 
> We should first make a decision on policy. This could be: reuse as much of the Coq library as is >possible/convenient. If so, Types/Nat.v becomes obsolete, as far as I can see.

The decision was made already a long time ago: the standard library is incompatible with HoTT and we are not trying to mimick it. We can discuss a change of policy, but I am would be against it unless someone can present strong reasons in favor.

The folder `coq/theories` contains only as much of the standard library as is necessary to make Coq happy. It is not supposed to be maintined or updated, nor does it serve any purpose (other than to make Coq happy – it's unfortunate that Coq has a built-in ideas about there being a standard library).

We should follow our own naming conventions, such as they are, and only be compatible with the standard names when it is not inconvenient to do so.

**Comment by marcbezem** [comment]
Naming conventions are important (and actually "Nat" would suit better than Coq-induced "nat"). 
If I run:

HoTT> grep -r "port Coq" theories/*.v
theories/Utf8.v:Require Export Coq.Unicode.Utf8.
HoTT> grep -r "port Coq" theories/*/*.v
theories/Types/Nat.v:Require Export Coq.Init.Peano.

then the use of the standard library is indeed minimal. We also have:

 HoTT/coq/theories/Init/Peano.v

and I understand it that we do not want to extend that one. It has a 

Lemma plus_n_O : forall n:nat, n = n + 0

but not symmetry, no exponents, no factorial.

Let me just propose some merge in a pull request, and change it if people are not happy with my choices. What I do need to understand better is how 

theories/Types/Nat.v:      Require Export Coq.Init.Peano.

is resolved. Will it pick HoTT/coq/theories/Init/Peano.v? Are the dependencies made explicit somewhere?

Thanks in advance!

**Comment by mikeshulman** [comment]
Can we close this issue?

**Comment by spitters** [comment]
@marcbezem Yes, that's what the Require points to.

@mikeshulman It would be good if this could be resolved. However, it depends on having better support for Coq without the std lib. We are discussing this elsewhere.

**Comment by mikeshulman** [comment]
I don't quite understand what it is that needs to be resolved.  `Types/Nat` has already been merged into `Spaces/Nat`, hasn't it?

**Comment by spitters** [comment]
OK. We keep our own and do not try to mimick the stdlib

**Comment by marcbezem** [comment]
> Can we close this issue?

Sure!

Best,

Marc
