### ISSUE TITLE
axioms, rules, canonicity

### ISSUE THREAD

**Issue by louisGarde** [HoTT/HoTT#791]
At the end of chapter 1.1 it is stated that "(../..) the type theory presented in this chapter (../..) consists entirely of rules, without any axioms".
This is in contradiction with the explanations following in the same paragraph, for instance "the rules are the rules of the game, while the axioms are the starting position".
That implies that HoTT (without univalence) is a formal game without starting position !

From my point of view, the difference between axiom and rule in type theory can only be defined from the concept of canonicity: an axiom in type theory is a rule that breaks the canonicity property. I would suggest to clearly define the canonicity property, as for instance it is done in nLab, and to remove the reference to axioms as "starting position".

What is the state-of-the-art definition of an axiom in type theory ?

**Comment by mikeshulman** [comment]
This is the wrong place for this question; you should ask it either on the hott or hott-cafe mailing list or at the HoTT Book repository (https://github.com/HoTT/book).
