### ISSUE TITLE
Coq std lib

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#795]
[This](https://github.com/coq/coq/pull/145) tries to make Coq tactics independent of its std lib.

**Comment by ejgallego** [comment]
Hi, the relevant HoTT branch is:

https://github.com/ejgallego/HoTT/tree/no-stdlib

For now I've just pasted the relevant bits on `Notations.v`

IMO, before putting more work on the HoTT I'd wait to see what is the final solution Coq upstream adopts.

**Comment by spitters** [comment]
Thanks. That looks a lot cleaner than the current set up.

**Comment by andrejbauer** [comment]
I am closing this since it's not really an issue. If @ejgallego can notify us when his work is done, that would be great.

**Comment by ejgallego** [comment]
This won't happen earlier than 8.7, I'm afraid.

**Comment by spitters** [comment]
Continued at:
https://github.com/HoTT/HoTT/issues/963
