### ISSUE TITLE
Universe command

### ISSUE THREAD

**Issue by SkySkimmer** [HoTT/HoTT#810]
https://github.com/HoTT/HoTT/blob/master/STYLE.md#universe-annotations says
>(It is possible to explicitly declare and name universes globally with the Universe command, but we are not using that in the HoTT library. Note in particular that universes declared with Universe are not generalized upon closing sections; they are permanently global wherever they are defined.)

However the doc says https://coq.inria.fr/distrib/current/refman/Reference-Manual032.html#hevea_command304
>29.6.1  Universe ident.
In the monorphic case, this command declares a new global universe named ident. It supports the polymorphic flag only in sections, meaning the universe quantification will be discharged on each section definition independently.

Quick test (assuming universe polymorphism is set) : https://gist.github.com/SkySkimmer/f0593798d699e1aa13d71ea5d0c6f10e

Did something change since the STYLE.md was written?

**Comment by mikeshulman** [comment]
Must be.  We should fix STYLE.

**Comment by JasonGross** [comment]
Yes, Matthieu fixed the behavior of `Universe` at some point after 8.5beta2, which is around when we stopped actively tracking the latest Coq.
