### ISSUE TITLE
Construction of the contextual category. (Coercion vs Destruct)

### ISSUE THREAD

**Issue by georgydunaev** [HoTT/HoTT#812]
I am trying to construct a contextual category from category with universe and terminal object.
(I follow two articles:
 http://arxiv.org/abs/1211.2851 
 http://www.tac.mta.ca/tac/volumes/30/37/30-37.pdf .)
I have a problem with destruction and coercions.

(It occurs at this line:
https://github.com/georgydunaev/smuf/blob/master/contextual_category.v#L698  )

Description:
I have 4 objects: a, b, c, d.
b is propositionally equal to c. (p:b=c)
I have morphisms:
f1: a->b 
f2: b->d
g1: a->c 
g2: c->d
I need to show that 
f2 o f1 = g2 o g1.
It is true in reflexive case, but I cannot destruct path 'p'.
How should I fix such class of errors?

```
Error: Abstracting over the terms "ob.1" and "(((ob.2).2).2)^" leads to a term
fun (a : categories.object (categories.precategory_of_category (cat (un uc))))
  (p0 : A (pbschoice uc ((ob.2).2).1) = a) =>
P sqR o centerpb.1 =
proj ConstructGradCat X
o transport (morphism (categories.precategory_of_category (cat (un uc))) (astm.2).1) p0
    centerpb.1 which is ill-typed.
Reason is: Illegal application: 
The term "@compose (GM.cat ConstructGradCat)" of type
 "forall s d d' : object (GM.cat ConstructGradCat),
  morphism (GM.cat ConstructGradCat) d d' ->
  morphism (GM.cat ConstructGradCat) s d -> morphism (GM.cat ConstructGradCat) s d'"
cannot be applied to the terms
 "astm" : "SnOb"
 "X" : "{x : _ & ur x}"
 "ft ConstructGradCat X" : "object (GM.cat ConstructGradCat)"
 "proj ConstructGradCat X" : "morphism (GM.cat ConstructGradCat) X (ft ConstructGradCat X)"
 "transport (morphism (categories.precategory_of_category (cat (un uc))) (astm.2).1) p
    centerpb.1"
   : "morphism (categories.precategory_of_category (cat (un uc))) (astm.2).1 a"
The 5th term has type
 "morphism (categories.precategory_of_category (cat (un uc))) (astm.2).1 a"
which should be coercible to "morphism (GM.cat ConstructGradCat) astm X".
```

p.s. Shall I send a pull request to HoTT/HoTT project (in /contrib/) with code after its preparation? 
p.p.s A little amount of comments in Russian may be just ommited: I need them only to fast text sending from file '.v'  to tex/pdf.

**Comment by mikeshulman** [comment]
This looks like one of those annoying things that happen with coercions, but it probably depends on the details of the categories library.  @JasonGross, any thoughts?

**Comment by georgydunaev** [comment]
Oh, thanks. You've reminded me of this issue. I feel that there is a problem, but my example is too complicated and unclear(and can be simplified). I should have added the link to the specific commit. I suppose issue can be closed, because the problem was solved. (just because of unfolding, as far as i remember)

**Comment by JasonGross** [comment]
Yes, it seems like an issue with unfolding; `destruct` or `induction` or `rewrite` failed to find all of the instances it was supposed to generalize over.

And, sure, feel free to submit a pull request for a file in `contrib/`
