### ISSUE TITLE
Axioms

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#815]
We use type classes to keep track of which axioms are used. See [STYLE](https://github.com/HoTT/HoTT/blob/master/STYLE.md#axioms).
However, Coq now also supports the [printing of axioms](https://coq.inria.fr/refman/Reference-Manual008.html#hevea_command99). Wouldn't this be simpler?

There is a possibility that automation picks up funext while it is not needed, but I am not sure how often this would happen. Thoughts?

**Comment by mikeshulman** [comment]
It would be simpler.  The current setup forces the coder, and the reader of the code, to be aware of where axioms are used, rather than simply being able to notice after the fact where they got used.  I think that's an advantage, but if the majority opinion is against it I won't fight.

**Comment by JasonGross** [comment]
I agree that it's an advantage to be pushed in the direction of not using axioms; if I recall correctly, this led to an interesting blog post of @mikeshulman's once.

(Also, in practice, I almost never check to see whether or not `dependent destruction` has surreptitiously used Axiom K, in my other developments; I don't see `Print Assumptions` becoming part of the standard development process.  Perhaps if PG highlighted definitions that used axioms in a different color (@cpitclaudel, would this be easy to add to company-coq?), then I'd be fine with it.)

**Comment by cpitclaudel** [comment]
Hmm. Sounds tricky. Would you do a Print Assumptions and then pick the color of the Qed based on that?

**Comment by mikeshulman** [comment]
I don't hear an outpouring of support for switching to simple axioms, so maybe I'll go ahead and close this.
