### ISSUE TITLE
Install HoTT library on cygwin

### ISSUE THREAD

**Issue by theckl** [HoTT/HoTT#823]
I would like to install the HoTT library on Windows using cygwin (32-bit).
Following the instructions in `INSTALL.md` works until running the shell script `etc/install_coq.sh`
Then make stops with error message

`make[1]: *** No rule to make target 'parsing/compat.ml', needed by 'parsing/compat.cmo'. Stop.`

The same error message is discussed in the comments of 

[https://aur.archlinux.org/packages/coq/?comments=all](https://aur.archlinux.org/packages/coq/?comments=all)

on 2016-1-21. Here, the solution seems to have been forcing `camlp4` instead of `camlp5`, but that does not work with  `etc/install_coq.sh` either.
So what to do?

**Comment by ejgallego** [comment]
Note that Coq windows installer for 8.9 will include a nice selection of 3rd party packages thanks to the work of @MSoegtropIMC and others. Please open an issue in the Coq bug tracker if you would like to see HoTT included.

Also, this issue seem stale as newer Coq version shouldn't have that problem. I propose to close.
