### ISSUE TITLE
Should `make install` install a version of `coq_makefile`?

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/HoTT#828]
Currently, `make install` doesn’t install any version of `coq_makefile`.  So if you just install HoTT without an existing installation of vanilla Coq avaialble, then external HoTT-based projects relying on `coq_makefile` will not be able to build.

Should we install some version of it?  If we do, options I can see include:
1. install it as `hoq_makefile` or similar
2. install it as `coq_makefile`, regardless of whether there’s an existing version installed
3. install it as `coq_makefile` if there is no existing version in the `$PATH`
4. install it as `coq_makefile` if there is no newer version in the `$PATH`

(2) seems bad, since we are generally trying to avoid interfering with other Coq installations.  (1) seems the most principled, but won’t immediately solve the original problem — it’s only useful once external projects switch over to using `hoq_makefile`.  (3) and (4) both seem reasonable — (4) maybe slightly better, but (3) a bit easier to implement.

I think I lean towards (1), for consistency with the rest of our installation.

**Comment by mikeshulman** [comment]
Is our version of `coq_makefile` going to be any different from the one installed by some other installation of (the same version of) Coq?

**Comment by peterlefanulumsdaine** [comment]
Just installing a copy of Coq’s standard one would be a helpful start.  There are maybe also some tweaks we could make if we felt it worthwhile, but they’re pretty non-essential (at least for the ways I’ve used it).

In more detail: I have several projects at the moment which use `coq_makefile` over the HoTT library, via a wrapper `Makefile` based on one by Adam Chlipala — for example, in the [hott-limits](https://github.com/peterlefanulumsdaine/hott-limits/blob/master/Makefile) library.  They work generally fine with standard `coq_makefile`.

There is at least one small wart that we could try to patch: the `Makefile.coq` produced by `coq_makefile` refers to `$(COQBIN)coqtop` at [a](https://github.com/coq/coq/blob/trunk/tools/coq_makefile.ml#L400) [few](https://github.com/coq/coq/blob/trunk/tools/coq_makefile.ml#L584) [places](https://github.com/coq/coq/blob/trunk/tools/coq_makefile.ml#L598).  So we could change that to e.g. an optional environment variable `$(COQTOP)` instead, along the lines of how it treats `COQC`, `COQDEP`, etc.  (Indeed, I guess we could suggest that as a pull request to Coq itself — I can’t see any obvious reason why they don’t do it currently.)  However, for all the ways I’ve used `coq_makefile`, everything still works fine with no `coqtop` installed — the call(s) to `coqtop` don’t seem to be essential.

**Comment by peterlefanulumsdaine** [comment]
Has anyone else been using `coq_makefile` for projects based over the HoTT library, by the way?

**Comment by SkySkimmer** [comment]
I have https://github.com/SkySkimmer/HoTTClasses/ which calls coq_makefile telling it "$COQC = hoqc" and "$COQDEP = hoqdep" in this script https://github.com/SkySkimmer/HoTTClasses/blob/master/configure
It seems to just work.

**Comment by mikeshulman** [comment]
What exactly does our `make install` install?  I never use it.

Could we do both (1) and (3)/(4)?  If we do modify `coq_makefile` I wouldn't want to install it with the same name, but it seems unlikely to do any harm to also install the standard one with the standard name for the benefit of projects currently using it under that name.

**Comment by peterlefanulumsdaine** [comment]
Yes, agreed, (1) + (3) sounds good.  The only modification I can think we’d would want would be to change the default values of `COQC` (resp. `COQDEP`, etc.) to be `hoqc` instead of `coqc`.  I guess this could be achieved just running a search-and-replace pass of something like `s/$(COQBIN)coq/$(COQBIN)hoq/`, either on `coq_makefile.ml` before compilation, or on its output `Makefile.coq` via a wrapper script?  The latter is probably the simpler approach.

Our `make install` installs `hoq-config`, `hoqc`, `hoqdep`, `hoqide`, `hoqtop`, and `hoqtop.byte`. (At least: that’s all the matches for `hoq*` on my `$PATH`.)  Coq tools we *don’t* install analogues of include `coq-tex`, `coqchk`, `coqdep_boot` (??), `coqdoc`, `coqmktop`, and `coqwc`.  Of these, `coqdoc` seems similar to `coq_makefile` — the standard ones basically works fine for us without modification, so the only motivation for installing it is so that it’s available for someone who’s installed our library without previously installing coq.  (So perhaps we could do (3) for `coqdoc`.)  I’ve never really used `coqchk`, but if I understand right, it requires similar flags to `coqc` and `coqtop`; so it might be worth providing a `hoqchk`, and not difficult to do, basing it off `hoqc`/`hoqtop`.  Are any of the rest worth trying to provide?

I would be able to have a go at these some time next week, I think, if not sooner.

**Comment by JasonGross** [comment]
I don't think there's any need to do search-and-replace with `coq_makefile` to get `hoq_makefile`; we can simply pass along the arguments that we'd pass to `coqc` to get `hoqc`  (`coq_makefile` understands `-R` and `-Q`, though it might need `-arg -coqlib` or similar)

**Comment by andrejbauer** [comment]
Can we close this or make a decision?

**Comment by mikeshulman** [comment]
Nobody objected to the proposal of installing both the default coq_makefile and a hoq_makefile that makes it use hoqc.  So someone just has to make the change and PR.

**Comment by ejgallego** [comment]
Definitive HoTT should not install its own coq_makefile. This bug should be closed.

**Comment by ejgallego** [comment]
@peterlefanulumsdaine HoTT should depend on an already installed Coq and not install its own.

**Comment by Alizter** [comment]
This seems to be resolved.
