### ISSUE TITLE
Intro rule in HoTT/HoTT

### ISSUE THREAD

**Issue by FirstLast1** [HoTT/HoTT#830]
Hello!

Why introduction rules looks so different? 
BuildEquiv, Build_PreCategory, BuildContr, Build_morphism, ( , ).

Most part of time that I spend using Coq is when I am trying to find appropriate name of constructor. (like those above)

I see several possible solutions:

1)create command or tactic "construct m."(or "introd m")  that will show or apply m-th introduction rule.

2)Maybe it is good to collect them in table
"name of type former", "names of its constructors"?

3) Rename all constructors in unified way. 

4) Do nothing and let the people to suffer >)

What do you plan to do with it? I can try to help, but I need a permission and direction.

**Comment by SkySkimmer** [comment]
1) `constructor` should work (`constructor 1` etc when multiple constructors are possible)

**Comment by FirstLast1** [comment]
It is not always constructor. 
Sometimes it is just intro-rule. Like for Sect.
Is it possibly to unite them?
It doesn't also work for IsEquiv.

**Comment by FirstLast1** [comment]
Should every change of syntax go with script with regexps? Or backward compatibility is an aim?

**Comment by mikeshulman** [comment]
It doesn't seem onerous to me to remember that Sect is a function type rather than a record.

**Comment by JasonGross** [comment]
I'm not sure why `BuildEquiv` and `BuildContr` are the way they are; `Build_PreCategory` is named as such because I was following the pattern that Coq uses when you give no explicit name: `Build_` followed by the name of the record type.

**Comment by mikeshulman** [comment]
My guess is that `BuildEquiv` and `BuildContr` were trying to follow the camelcase pattern used for other things in the library, `IsEquiv`, `IsTrunc`, etc.  I suppose it would be nice to be consistent, but this has never been a problem for me.

**Comment by spitters** [comment]
Fine with me
