### ISSUE TITLE
Closing old issues

### ISSUE THREAD

**Issue by andrejbauer** [HoTT/HoTT#834]
We are running a real danger of accumulating so many old issues that the issue tracking will become a dump. In such situations it's better to just close old issues that nobody has touched for years. If any one them actually matters, they'll crop up again.

I propose that as a one-time measure we close every issue that is older than two years. If anyone cares about any of those, they should reopen it and give some indication that the issue will be resolved in the near future. Without such an indication the issue may as well be put to sleep.

**Comment by andrejbauer** [comment]
I do not recall creating the "y type theory philosophy" milestone, nor do I remember adding this issue to it. What is going on?

**Comment by JasonGross** [comment]
Perhaps you started typing in another window, and the focus switched to
GitHub without you noticing, and you hit enter before notifying your words
weren't working where you wanted them to?

**Comment by ejgallego** [comment]
This issue is stale so it can be closed I think.
