### ISSUE TITLE
8.6

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#839]
@ejgallego has ported hott to v8.6 on [jshott](https://x80.org/rhino-hott/). I am hoping he will tell us here which obstacles he met, so that we can do the same.

**Comment by ejgallego** [comment]
My current tree is at https://github.com/ejgallego/HoTT/tree/compat-8.6

Note that the port it is not yet complete, but I think the diff is reasonably small. There are a couple of strange things with notations.

Wondering if we should merge this with #804 ?

**Comment by mattam82** [comment]
Huh, isn't m'y PR enough? It's very small now.

**Comment by mattam82** [comment]
PR #831

**Comment by ejgallego** [comment]
Oh indeed I had missed it, I have too many versions on my HD :S

I did as Jason suggested and split the changes in 8.5 compatible (that are in a separate PR) and rebased @mattam82 's tree at: https://github.com/ejgallego/HoTT/tree/mz-8.6

It should be possible to fix the universe problems as highlighted by Matthieu.

**Comment by mattam82** [comment]
LGTM

**Comment by spitters** [comment]
It looks good to me too. However, we do not have a concrete PR now, do we?

**Comment by mattam82** [comment]
I guess @ejgallego can make one now?

**Comment by ejgallego** [comment]
I hesitate as this PR breaks compatibility with 8.5. As Matthieu pointed out, explicit universe annotations would be needed.

**Comment by spitters** [comment]
With 8.6 out, I think we should now create a 8.5 compatibility branch and have the main branch follow 8.6. Right?

**Comment by ejgallego** [comment]
IMVHO it really depends how robust you want to be vs "universe minimization" @JasonGross ?

Adding such annotations would increase compatibility and maybe remove the need for an 8.5 branch, however I ignore if the HoTT developers would like to have such annotations in the code.

**Comment by JasonGross** [comment]
I agree with @spitters, though, I'm not sure we want to keep maintaining an 8.5 branch.  I'm thinking an 8.5 tag rather than a branch.  @spitters (and @andrejbauer, @mikeshulman and others), thoughts?

I'd say, yeah, @ejgallego, make a PR which bumps the submodule to 8.6 released and makes breaking changes as needed.  If you can make universe annotations, that would be nice, but don't worry about it if it's hard.  (In either case, we'd need to do some fiddling with the standard library, which I don't know how to do in an 8.5+8.6 compatible way.)

**Comment by mikeshulman** [comment]
Unless there are any known issues that prevent anyone from upgrading to 8.6, I'd probably say don't bother with an 8.5 branch.

**Comment by spitters** [comment]
OK. Let's (make a 8.5 tag and) upgrade to 8.6.

**Comment by JasonGross** [comment]
I've pushed an 8.5 tag: https://github.com/HoTT/HoTT/tree/V8.5

**Comment by ejgallego** [comment]
@JasonGross this needs to be closed

**Comment by JasonGross** [comment]
Closed by #863
