### ISSUE TITLE
Error: Conversion test raised an anomaly, only with HoTT version of standard library

### ISSUE THREAD

**Issue by jdchristensen** [HoTT/HoTT#844]
Using hoqtop (latest version, c95a36259), the following code

    Definition graph := Type.
    Inductive paths (G : graph) : Type := .   (* Empty type. *)
    Variables (G : graph) (p : paths G).
    Check (paths G).

gives `Error: Conversion test raised an anomaly`.

It happens with `HoTT/coq-HoTT/bin/coqtop -coqlib HoTT/coq` but not with `HoTT/coq-HoTT/bin/coqtop`, so it seems to be related to the altered standard library.

The error goes away if I do any one of:
- Get rid of the unused p.
- Split the Variables declaration into two Variables commands.
- Remove G from the definition of paths.
- Replace "graph" with "Type" everywhere.

Variations of the above give `Anomaly: Universe Top.20 undefined. Please report.`

**Comment by JasonGross** [comment]
I think this might be a known bug in 8.5... If you `Set Universe Polymorphism.` at the top, and do not use the altered standard library, what happens?  Does the same thing happen in Coq 8.6rc1?

**Comment by jdchristensen** [comment]
If I add `Set Universe Polymorphism` at the top and use `HoTT/coq-HoTT/bin/coqtop`, I get the error.  So this is a bug in Coq.  Can someone with 8.6rc1 already installed test this with it?

**Comment by jdchristensen** [comment]
I just tried this in the newly released 8.6, and the problem is gone.  So this can either be closed now, or closed when the HoTT library upgrades to 8.6.
