### ISSUE TITLE
Integrating hott-colimits library

### ISSUE THREAD

**Issue by SimonBoulier** [HoTT/HoTT#845]
I developed a small library about colimits in HoTT:
   https://github.com/SimonBoulier/hott-colimits/tree/flattening_lemma_and_cie
(`flattening_lemma_and_cie` is the "dev" branch).

See also this blog post for an introduction:
   https://homotopytypetheory.org/2016/01/08/colimits-in-hott/

The results formalized are:
- definitions of graphs, diagrams, cocones and colimits
- the existence of a colimit with an HIT
- several functoriality results (giving ultimately: an equivalence of diagram induce an equivalence between the colimits)
- the unicity of colimit
- a commutation result of colimits with products and dependent products
- the flattening lemma for an arbitrary diagram (only the one for coequalizer seems present in the HoTT library for the moment)

Do you think that it is worthwhile to integrate those results in the HoTT library?
In that case I could clean up my code and prepare a PR.

**Comment by mikeshulman** [comment]
Yes!

**Comment by spitters** [comment]
I am hoping that you are closing this issue because you are creating a PR...
Looking forward to your work.

**Comment by andrejbauer** [comment]
Why is this closed? I hope we did not scare you away, @SimonBoulier. We would very much like your contribution. The suggestions we made were meant as well-intended improvements. If you're not willing to make them, just say so, we'll consider the PR anyhow to see whether someone else will take over. I am reopening.

**Comment by SimonBoulier** [comment]
I'm not scared at all, I planed to work on the PR this week! I just closed this issue because I decided on preparing the PR (and I did it). Anyway, thank you very much @JasonGross  and @andrejbauer for your comments, I'll fix them.

**Comment by andrejbauer** [comment]
Oops, I got confused and thought this issue is PR #850, sorry.
