### ISSUE TITLE
HoTT classes

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#884]
There are various people interested in building on the math-classes 
http://math-classes.github.io/
port for HoTT. 

I think it would be nice to include it in the main library. What do people think?
https://github.com/SkySkimmer/HoTTClasses/issues/3

Alternatively, we could have a collection of opam packages. 
This seems to be the way the Coq std lib is now developing.

**Comment by mikeshulman** [comment]
As @SkySkimmer says, it's an interesting question of how wide the vocation of this library is.  I don't think we've ever really discussed it.  We didn't start out with a vocation like UniMath to formalize all of mathematics.  At the same time I don't think we've ever declined a contribution, and there are some benefits to including subsidiary developments, e.g. keeping them all up to date together if we make changes to the core.  We already include the categories library, and I don't really see a dividing line that could be drawn in between categories and math-classes.  True, categories uses >0-types in some places (saturated/univalent categories) whereas math-classes probably doesn't (?), but there's plenty of other code in the library that certainly belongs there even though it's only about 0-types.  And it might be useful in other parts of the library to be able to use math-classes, e.g. group theory for BAut, or homological algebra for spectral sequences.  In fact, is there any useful prospect of combining the categories and math-classes libraries, e.g. defining univalent categories of algebraic structures?

All of which is to say, I think I would be in favor of inclusion, if @SkySkimmer is.  I guess one question is whether @SkySkimmer is willing to continue maintaining hott-classes within the HoTT library, e.g. if we change something in the core that breaks something in hott-classes, will you help us fix it?  Jason generally does that for the categories library.

**Comment by SkySkimmer** [comment]
>if we change something in the core that breaks something in hott-classes, will you help us fix it?

Yes.
I would have to do it even with no inclusion anyways ;)

**Comment by spitters** [comment]
Great!
So, we are looking forward to the PR. :-)

**Comment by mikeshulman** [comment]
> I would have to do it even with no inclusion anyways

As long as you are intending to continue maintaining hott-classes, anyway.  Thanks!

**Comment by SkySkimmer** [comment]
I forgot what was going on with #818 (Bool in Type0) but HoTTClasses uses Bool at a monomorphic universe which is kinda hacky. Can anyone remember what would need to be done to have Bool  : Type0?

**Comment by mikeshulman** [comment]
Rereading the discussion, it looks like there was a proposal for consistent
naming of universe aliases, but no one had yet tried it out and made the
necessary fixes throughout the library.

**Comment by SkySkimmer** [comment]
I made a merge of HoTTClasses into HoTT's contrib directory at https://github.com/SkySkimmer/HoTT/commits/HoTTClasses, my plan is to move and adapt files to HoTT's theories directory one by one. This allows retaining history for all files.
This does mean a history with no common root, is that a problem?

**Comment by SkySkimmer** [comment]
About licenses:
- mathclasses is public domain https://github.com/math-classes/math-classes/blob/v8.5/LICENSE
- HoTT is BSD 2 clause https://github.com/HoTT/HoTT/blob/master/LICENSE.txt
- the only non me commit in HoTTClasses is SkySkimmer/HoTTClasses@1c17c24596b8072df7bc6411e617bd1eedcaaffb so license is limited by what things I imported. This is mostly mathclasses, but I also started porting Coq's (LGPL2.1 https://github.com/coq/coq/blob/trunk/LICENSE) implementation of binary integers intending to use them for the ring tactic before deciding to use a HIT based approach. Since they're not used I have removed them.

I have to say I strongly disapprove of HoTT's licensing not following Coq's.

**Comment by mikeshulman** [comment]
What do you mean by "no common root"?

I don't see a licensing problem.

**Comment by spitters** [comment]
@SkySkimmer What is the status of this?

**Comment by SkySkimmer** [comment]
I don't know how to organize the code. Should I just make a directory `theories/Classes` and drop everything there as is?

**Comment by spitters** [comment]
I think starting by putting it all in a separate directory would be a good
start. We did the same with the category theory library.

from my phone

**Comment by spitters** [comment]
@SkySkimmer Since hottclasses has been integrated, I guess we can now close this issue?
However, before we do so, do we want code in the main library to depend on Classes?
@mikeshulman ?

I am currently discussing with @co-dan (and  @nmvdw) about integrating their library.
https://github.com/nmvdw/HITs-Examples/tree/master/FiniteSets

**Comment by SkySkimmer** [comment]
>@SkySkimmer Since hottclasses has been integrated, I guess we can now close this issue?

Yes.

>However, before we do so, do we want code in the main library to depend on Classes?

Keep in mind that `canonical_names` (included by everything in Classes) uses HITs for truncations to define eg CoTransitive.

**Comment by mikeshulman** [comment]
Is there currently-extant code in the main library that would benefit from using Classes?

I guess my instinct would be to just maintain a coherent dependency tree of subdirectories.  I would say nothing in Basics/, Types/, HIT/, or the root of theories/ should depend on Classes, but for any other subdirectory we can make an independent decision about whether it can use Classes.  For instance, some things in Algebra/ would certainly benefit, and probably some things in Spaces/ too.

**Comment by SkySkimmer** [comment]
>Is it good practice to call a commutative ring Ring? I would of thought CRing would be a more appropriate name given that in the future actual rings may be added.

This is inherited from mathclasses:
https://github.com/math-classes/math-classes/blob/403d8876abab48145df7bcae90e09284fc61662a/interfaces/abstract_algebra.v#L117-L123
```coq
  Class Ring : Prop :=
    { ring_group :> @AbGroup plus_is_sg_op zero_is_mon_unit _
    ; ring_monoid :> @CommutativeMonoid mult_is_sg_op one_is_mon_unit
    ; ring_dist :> LeftDistribute (.*.) (+) }.

  (* For now, we follow CoRN/ring_theory's example in having Ring and SemiRing
    require commutative multiplication. *)
```

**Comment by Alizter** [comment]
> This is inherited from mathclasses:

I understand however is this simply going to be a straight inheritance or will it be modified here? I would think that most people would agree that Ring isn't a good name for a commutative ring. If this library is going to be readable then the parts it inherits should still keep that ideal too.

However if this is just so people can convert their mathclasses coq work from previous projects its fine. This does however hold the question of when the HoTT library is going to get its proper Algebra stuff.

There could be multiple approaches to this but given the development of oo-cats here a higher algebra approach could be viable although I don't know how usable that is to the standard mathematician.

Perhaps this needs to be a new issue.

**Comment by spitters** [comment]
I'd rather deal with the issue once we have converged on #895 and https://github.com/coq/coq/issues/6890
At that point we can really start importing math-classes, and then start changing it when someone comes up with a substantial formalization of non-commutative rings.

**Comment by mikeshulman** [comment]
I'm not sure if there's anything remaining to discuss here.  If so, maybe it would be clearer to open a new issue if and when it becomes important.
