### ISSUE TITLE
Cumulative Inductive types

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#886]
Coq trunk now has cumulative inductive types.
https://github.com/coq/coq/commit/414890675cb72fd9286e19521a746677c06e784e

We should take advantage of this when we move to 8.7.

**Comment by SkySkimmer** [comment]
8.7 cumulative inductive types are probably difficult to use due to the issue I attempt to fix at coq/coq#6092.
See also https://github.com/coq/coq/pull/6092#issuecomment-343697424 for results of quickly experimenting with enabling it in HoTT with no other changes.

**Comment by spitters** [comment]
@SkySkimmer Since you closed coq/coq#6092 does that mean that this one is now hopeful too?

**Comment by SkySkimmer** [comment]
I tried enabling cumulativity with Coq master, both with and without minimisation to set. I ended up getting some error in `theories/Modalities/ReflectiveSubuniverse.v` where it's hard to tell what's going wrong (some simple change has to be done, or maybe Coq's universe heuristics should be improved, or who knows what else).
So I would say it's hopeful but not trivial.

**Comment by Alizter** [comment]
Related discussion in #1042, do we have any specific examples of inductive types we wish to be 'cumulative'?

**Comment by Alizter** [comment]
For reference:

Just as universes can be cumulative: `A : Type@{i}` means `A : Type@{j}` for `i < j`, coq allows inductive types marked with the `Cumulative` keyword to mimic this behaviour. Say you had an inductive type `A : Type@{i}` with a constructor `a : A@{i}`, then cumulativity will allow you to typecheck `a : A@{j}` for `i < j`.

Details can be found in: https://hal.inria.fr/hal-01952037/document

I am closing this issue as we are currently using such features of coq.
