### ISSUE TITLE
Broken in Coq master

### ISSUE THREAD

**Issue by ejgallego** [HoTT/HoTT#899]
Hi, I tried to update the branch used in Coq's CI but unfortunately one file fails:

```
COQDEP theories/Classes/implementations/natpair_integers.v
HOQC theories/Classes/implementations/natpair_integers
File "./theories/Classes/implementations/natpair_integers.v", line 509, characters 15-22:
Error: Cannot infer this placeholder of type "is_mere_relation Z Zle" (no
type class instance
found) in environment:
H : Funext
H0 : Univalence
N : Type
Aap : Apart N
Aplus : Plus N
Amult : Mult N
Azero : Zero N
Aone : One N
Ale : Le N
Alt : Lt N
U : NaturalsToSemiRing N
H1 : Naturals N

Makefile:949: fallo en las instrucciones para el objetivo 'theories/Classes/implementations/natpair_integers.vo'
make: *** [theories/Classes/implementations/natpair_integers.vo] Error 1
```

The good news is that this is the only faiulre. IMHO we should really try to add a mechanism to ship different `Notations.v` so HoTT works in both versions.

**Comment by ejgallego** [comment]
Branch used for testing https://github.com/ejgallego/HoTT/tree/test

**Comment by SkySkimmer** [comment]
See #900.
Is there some reason we can't do `cp $($COQBIN/coqc -where)/theories/Init/Notations.v coq/theories/Init/Notations.v` (or `ln` etc)?

**Comment by ejgallego** [comment]
@SkySkimmer thanks! That proposal looks interesting; another choice could be to ship version-specific notation files.

**Comment by JasonGross** [comment]
> Is there some reason we can't do cp $($COQBIN/coqc -where)/theories/Init/Notations.v coq/theories/Init/Notations.v (or ln etc)?

When we started, I think Coq did not install .v files, only .vo.  Note that it installs them, we should be able to set up the configure script to do this.
