### ISSUE TITLE
STYLE.md table of content duplicate entry

### ISSUE THREAD

**Issue by SkySkimmer** [HoTT/HoTT#912]
The table of content looks like this:
```
Axioms

    Univalence and function extensionality
    Higher inductive types
    Relationships between axioms
    Assuming axioms
    Technical note: Universe-polymorphic axioms

Higher Inductive Types
```
The two `Higher Inductive Types` entries are links to the same anchor (which is the anchor for the axioms subsection).
Probably the first one should be renamed `Axioms for higher inductive types` or some such thing.

**Comment by mikeshulman** [comment]
Yes, that seems the right thing to do.
