### ISSUE TITLE
installation trouble: 'aclocal-1.14' is missing on your system.

### ISSUE THREAD

**Issue by marcbezem** [HoTT/HoTT#917]
Installing the HoTT-library under Linux Mint 18, following the instructions in INSTALL.md, the
warnings below were issued. The last of them appears to be fatal in the sense that hoq didn't work.
I googled "'aclocal-1.14' is missing on your system" and got several suggestions, the combination of these two worked:

````
sudo apt-get install automake 
autoreconf -f -i
````

So I can work, but perhaps some  installation script has to be changed.

````COQDEP coq/theories/Init/Datatypes.v
*** Warning: in file coq/theories/Init/Datatypes.v, declared ML module nat_syntax_plugin has not been found!
*** Warning: in file coq/theories/Init/Datatypes.v, declared ML module nat_syntax_plugin has not been found!
COQDEP coq/theories/Init/Logic.v
COQDEP coq/theories/Init/Notations.v
*** Warning: in file coq/theories/Init/Notations.v, declared ML module ltac_plugin has not been found!
*** Warning: in file coq/theories/Init/Notations.v, declared ML module ltac_plugin has not been found!
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/bezem/git/HoTT/etc/missing aclocal-1.14 -I etc
/home/bezem/git/HoTT/etc/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:461: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
````

**Comment by mikeshulman** [comment]
I don't really understand the installation scripts at this level, but #874 (unmerged) seems relevant.  Originally the library was supposed to be installable without autoconf/automake, but possibly now that route is broken (?) and we may not be going to fix it.  If so, then we should certainly modify the instructions at least to include installing these as necessary packages.  Any thoughts @JasonGross ?

**Comment by JasonGross** [comment]
I'm in favor of marking them explicitly as dependencies.  I don't currently have the time (or motivation, for that matter), to figure out how to fully support that build setup.

**Comment by mikeshulman** [comment]
By "that build setup" do you mean the one with or without automake?

**Comment by JasonGross** [comment]
The one without.

**Comment by Alizter** [comment]
I guess this is no longer relevant since we don't rely on autoconf/automake anymore. Feel free to reopen otherwise.
