### ISSUE TITLE
HottBook.v contains references not (longer) occurring in the latex version

### ISSUE THREAD

**Issue by marcbezem** [HoTT/HoTT#918]
I ran into the error below. It turns out that Example 3.1.2 (and others) do not have labels anymore in the latex source. I propose to remove such entries from HoTTBook.v, as they are not deemed important. Also, in this particular case, formalizing the proof that Unit is a set by the proof that Unit is contractible, is not optimal.

Removing such entries widens the policy of Rule 2: "If a theorem is gone ..." in a way which makes sense to me.

````
HoTT> cat ../book/*.aux | etc/Book.py contrib/HoTTBook.v
Reading content of *.aux files from standard input...
                                                                                 
Statistics:
3661 lines of input
2677 lines skipped
430 labels found
0 labels confused me

Reading contrib/HoTTBook.v

 ***** FATAL ERROR: unknown entry eg:isset-unit found in Coq file, please fix this first.
````

**Comment by mikeshulman** [comment]
Actually the problem is that they don't have labels *yet*.  See hott/book#967.

**Comment by marcbezem** [comment]
Ahh, I see now you added them 4 days ago ... So I entered the critical section between two updates?

BTW my favorite proof would then be the combination of contr_unit and that contractible types are hsets. In any case not contr_unit.

**Comment by mikeshulman** [comment]
Well, feel free to improve it.

**Comment by marcbezem** [comment]
@mikeshulman I can do that, but want to first finish my short proof of Book_6_9.

**Comment by Alizter** [comment]
Is there still an issue here?

**Comment by mikeshulman** [comment]
I don't think so.
