### ISSUE TITLE
ocamlfind: Package `camlp5.gramlib' not found

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#926]
After pulling #925, updating the coq submodule, and running `etc/install_coq.sh` to compile the new Coq I get

```
ocamlfind: Package `camlp5.gramlib' not found
Makefile.build:398: recipe for target 'bin/coqtop' failed
```

Googling led me to coq/coq#6782, but it's not clear to me from the discussion there whether this is my problem (I'm not trying to compile camlp5 locally) or what I can do to fix it.

**Comment by mikeshulman** [comment]
Can nobody help me?  )-:

**Comment by spitters** [comment]
If you ask at coq/coq#6782 I'm sure you'll get expert advice.

**Comment by mikeshulman** [comment]
Okay, figured this problem out, though now I have a new one...
