### ISSUE TITLE
Switching to 8.7

### ISSUE THREAD

**Issue by andrejbauer** [HoTT/HoTT#927]
Is there a reason the HoTT library is becoming seriously stale and difficult to compile with new OCaml and new Coq? I have HoTT `V8.7` working on my machine. Why isn't it the official version of HoTT? Unless there's a good reason, we should switch ASAP.

**Comment by spitters** [comment]
Hasn't this been done in:
https://github.com/HoTT/HoTT/pull/925

**Comment by SkySkimmer** [comment]
The stable branch's coq submodule needs to be updated to 8.7.2 to compile with ocaml 4.06. Is that what you mean?
What is the official version of HoTT exactly? Where is that stated?

**Comment by spitters** [comment]
coq-HoTT currently points here:
https://github.com/coq/coq/tree/15331729aaab16678c2f7e29dd391f72df53d76e

@JasonGross  updated this 20days ago, so I expect it to be new enough.

**Comment by mikeshulman** [comment]
And I finally got it to compile on my machine by blowing away all my ubuntu ocaml packages and reinstalling them all with opam instead.

```
~/hott/coq$ ./hoqc --version
The Coq Proof Assistant, version 8.8+alpha (March 2018)
compiled on Mar 26 2018 9:53:25 with OCaml 4.06.1
```

So I'm also confused about what you mean, @andrejbauer .
