### ISSUE TITLE
Totality of relations as property or structure?

### ISSUE THREAD

**Issue by abooij** [HoTT/HoTT#934]
Currently, in Classes, a relation is considered total if it comes equipped with a choice of disjuncts
https://github.com/HoTT/HoTT/blob/eeaffdba64ff6d9c7d38871532375c45cb3166a8/theories/Classes/interfaces/canonical_names.v#L245

Would it perhaps be better to use truncated disjunction (`hor`)? Speaking of which, would it be reasonable to add notation for `hor`, `hexists` and `merely` (defined in `theories/HIT/Truncations.v`)? (Although some editors, such as company-coq, prettify the "exists" tactic to the reverse-E existential quantifier, which may be confusing, because it generates an element of a Σ-type. And the `\/` notation from the Coq Init library gets prettified to `∨`, even though it is `+`.)

**Comment by abooij** [comment]
I have [tried](https://github.com/abooij/HoTT/tree/total_hor) making this change from structure to property. Most proofs require very little change, but I have found two theorems (about the rationals) so far that require some redevelopment.

**Comment by mikeshulman** [comment]
Then are you saying that the HoTT library defines `\/` to mean `+`?!?  That's clearly the wrong thing to do; where is that?

**Comment by mikeshulman** [comment]
@abooij said "the `\/` notation from the Coq Init library" so I thought he was talking about vanilla Coq.

**Comment by abooij** [comment]
https://github.com/HoTT/HoTT/blob/eeaffdba64ff6d9c7d38871532375c45cb3166a8/coq/theories/Init/Notations.v#L16

**Comment by mikeshulman** [comment]
Sure, that's where the notaion is reserved -- where is it defined?

**Comment by abooij** [comment]
Sorry, I linked the wrong code, please refresh this page to see my updated comment :)

**Comment by mikeshulman** [comment]
Huh.  Well, we should get rid of that.  I suppose whoever wrote that was figuring that `\/` should mean _something_, and `hor` isn't defined yet in that file, but I think it's highly confusing to define `\/` to mean `+`.  It should mean `hor`; at least, that's how the book uses it.

**Comment by mikeshulman** [comment]
Regarding the original question, are there any examples of relations that are constructively total-as-property but not total-as-structure?  I think the order on the rationals is total-as-structure, since it is decidable, whereas the order on the reals is not even total-as-property.

**Comment by SkySkimmer** [comment]
IIRC I kept using `\/` in Classes because `+` is overloaded. The point is that we should have a notation for `+` which is less ambiguous than it.

**Comment by mikeshulman** [comment]
and less verbose than `(A + B)%type`?  I suppose that makes sense.  If we allowed unicode we could write `A ⊔ B`; is there some ASCII approximation of that?  Maybe `A |_| B`?

**Comment by abooij** [comment]
@mikeshulman The unicode version doesn't completely solve the ambiguity problem in this case as `x ⊔ y` is used for joins in Classes.

**Comment by SkySkimmer** [comment]
I don't like scope annotations, although I can't explain why. Maybe something to do with not wanting to have to parenthesize.
There should be some unicode + we could use, eg ⊕

**Comment by abooij** [comment]
@SkySkimmer Scope annotations would be more helpful for an uninformed reader than ⊕, which is used in a very wide range of contexts and so gives very little information.

In which cases does and doesn't Coq figure out the right meaning, if scope annotations are omitted?

**Comment by mikeshulman** [comment]
Well, there's `⊎` I guess.

**Comment by mikeshulman** [comment]
And also `⨿`.

**Comment by mikeshulman** [comment]
Back on the original subject of this issue... are there naturally occurring relations which are (constructively provably) hor-total but not sum-total?  I can't think of any offhand, which suggests that hor-total is maybe not that useful of a notion when we have sum-total available.

On the other hand, in showing that a relation such as `<=` on integers or rationals is sum-total, I presume one has to make an arbitrary choice of one summand in the case when the arguments are equal.  This makes sum-totality seem somewhat less canonical.

**Comment by abooij** [comment]
Here's a contrived example, I think.

By the locatedness axiom of dedekind reals (or alternatively by cotransitivity of `<`), we know that for any real `x`, we have `(0 < x) v (x < 1)` (`v` for `hor`).

Define the relation `R` on real numbers by `R x y := (0 < x) v (y < 1)`. By locatedness of either `x` or `y`, one can show that `R` is hor-total.

Suppose `R` were sum-total. Consider any real `x`. Consider sum-totality at `x := x` and `y := 1-x`. Sum-totality gives that `((0 < x) v (1-x < 1)) + ((0 < 1-x) v (x < 1))`. Equivalently, `((0 < x) v (0 < x)) + ((x < 1) v (x < 1))`. Equivalently `(0 < x) + (x < 1)`. Hence we obtain a sort of "strong locatedness" of an arbitrary real `x`. But for an arbitrary real `x` there should not be a canonical choice of `(0 < x) + (x < 1)`.  Though I'm not sure right now how to make that final thought more precise.
