### ISSUE TITLE
Correct definition of ordered/archimedean fields

### ISSUE THREAD

**Issue by abooij** [HoTT/HoTT#937]
I am working on constructive analysis in the HoTT library. So I'd like to formalise part of Chapter 11. I have formalised ordered fields as follows:
```coq
Class OrderedField (A : Type)`{Lt A} `{Le A} `{Apart A} `{Zero A} `{One A} `{Plus A}
      `{Negate A} `{Mult A} `{Recip A} `{Join A} `{Meet A} :=
  { ordered_field_field :> Field A
  ; ordered_field_lattice :> LatticeOrder (≤)
  ; ordered_field_fssro :> FullPseudoSemiRingOrder (≤) (<)
}.
```
(to be placed in `HoTT/theories/Classes/interfaces/orders.v`)
I have formalised archimedean fields as follows:
```coq
Require Import
        HoTT.Classes.interfaces.abstract_algebra
        HoTT.Classes.interfaces.rationals
        HoTT.Classes.interfaces.orders.

Section archimedean.

  Context (Q : Type) `{Rationals Q}.
  Context (A : Type) `{Lt A} `{Le A} `{Apart A} `{Zero A} `{One A}
          `{Plus A} `{Negate A} `{Mult A} `{Recip A} `{Join A} `{Meet A}.

  (* Eval compute in rationals_to_field Q A 0. *)
  Class ArchimedeanField  :=
    { archimedean_field :> OrderedField A
    ; archimedean_property :> forall x y, x < y -> hexists (fun q => x < (rationals_to_field Q A q) < y)
    }.

End archimedean.
```
(to be placed in a new file `HoTT/theories/Classes/interfaces/archimedean.v`). So a field is archimedean _with respect to some fixed type of rationals_. The following considerations apply:
- By univalence, if a field is archimedean with respect to some type of rationals, it should be archimedean with respect to all types of rationals. (I haven't shown this ostensibly straightforward theorem yet - perhaps there is a size issue lying around.)
- Alternatively, one could say that an ordered field is archimedean if given _any_ type of rationals we have the archimedean property with respect to those rationals, and expect an algebraic proof of this property. However, I found this more cumbersome to define because of universe levels, let alone prove. [Edit:] And I should add that the above choice is far easier to prove for the dedekind reals.
- Having said this, we do care about the different implementations of the rationals, for example for efficiency reasons. And one might wish to define the dedekind reals in terms of some type of rationals, but then do other computations in terms of some other type of rationals, or even in terms of some other type that is not a field such as the dyadic rationals.

Although I believe the above definitions to be accurate (by inspecting the proof goals generated after a `repeat split`), is there a protocol for verifying this?

(I have some work in a [branch](https://github.com/abooij/HoTT/tree/dedekind_reals) containing a definition of the [dedekind reals](https://github.com/abooij/HoTT/blob/dedekind_reals/theories/Classes/implementations/dedekind_reals.v) which currently uses `Axiom axiomatize : Empty.` which will of course be removed eventually. The purpose of introducing this inconsistency is that I can delay proof obligations, but maintain computation rules, which is useful both in proofs and for doing computations with numbers. Coq proofs that end in `Admitted.` do not reduce at all, but sometimes I would like part of a proof to compute. For example, this aids in finding and reducing the appropriate instances.)

**Comment by spitters** [comment]
Great to see this.

Yes, they look reasonable. One usually gains confidence in a definition by proving theorems with it, is that what you mean by protocol?

**Comment by Alizter** [comment]
@abooij Did you make anymore progress with this?

**Comment by spitters** [comment]
I see that I did not mention then that HoTT-classes only ports some parts of math-classes. Much more is available there.
See also the work on the stdlib:
https://github.com/coq/coq/pull/10445

**Comment by Alizter** [comment]
@spitters  Are you currently working on porting more? Do you need help?

**Comment by spitters** [comment]
I'm not currently porting more, but I think that would be interesting.
@andreaslyn ported part of the universal algebra already.

**Comment by abooij** [comment]
@Alizter: I did not make much progress on implementing the Dedekind reals beyond what I wrote and linked above. So I do not have a proof that they are an archimedean field in the sense of the above definition.

**Comment by abooij** [comment]
In fact there was a mistake in my definition of ordered fields above: it quietly accepted two different instances of `Zero A` because both `Field A` and `FullPseudoSemiRingOrder A` took one, and the definition above did not specify they had to be the same instance. Same for the `Le A` instance for `LatticeOrder (≤)`  resp. `FullPseudoSemiRingOrder (≤) (<)`.

I have a fixed version, which I will soon send in a PR. For a sneak preview, see [this branch](/abooij/HoTT/tree/fixing-locators).

I am closing this issue because @spitters' advise helped me.
