### ISSUE TITLE
etc/missing could be more helpful when versions are too new

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#941]
After moving to a new  computer with a newer version of Ubuntu, I got the following error:

```
configure.ac:12: error: version mismatch.  This is Automake 1.15.1,
configure.ac:12: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:12: comes from Automake 1.15.  You should recreate
configure.ac:12: aclocal.m4 with aclocal and run automake again.
WARNING: 'automake-1.15' is probably too old.
```

The error message "probably too old" comes from `etc/missing`, which reports this whenever there is a "version mismatch".  But apparently sometimes a version mismatch can happen when the program is too *new*.  In this case the solution was to just re-run `autogen.sh` and `configure`.

Is there a way for `etc/missing` to test whether a version mismatch is "too old" or "too new" and produce different error messages?

**Comment by JasonGross** [comment]
I think this file is generated automatically by aclocal or autoconf.  We could roll our own, but it's not clear to me that we want to

**Comment by mikeshulman** [comment]
`etc/missing` is generated automatically?

**Comment by JasonGross** [comment]
By "generated automatically" I mean "copied automatically from some system location of autotools" (if I recall correctly)

**Comment by mikeshulman** [comment]
Ok, well in that case I guess there's not much we can do.
