### ISSUE TITLE
Build error on Coq 8.7

### ISSUE THREAD

**Issue by abooij** [HoTT/HoTT#943]
Commit 650a2fab1d seems to have introduced a build error on coq 8.7.2, see [Travis](https://travis-ci.org/HoTT/HoTT/jobs/383323021).
```
HOQC theories/UnivalenceImpliesFunext
File "./theories/UnivalenceImpliesFunext.v", line 97, characters 7-38:
Error: Universe instance should have length 8
```

**Comment by JasonGross** [comment]
The master branch of this repo tracks the master branch of Coq.  If you want to build with Coq 8.7, you can use the [V8.7 tag](https://github.com/HoTT/HoTT/tree/V8.7).  However, we should make this clearer by dropping travis support for v8.7 and bumping it to v8.8.

**Comment by abooij** [comment]
In that case, `INSTALL.md` also needs updating:

> We are compatible with Coq 8.7, so binary packages can be used. Paths still need to be set manually.
