### ISSUE TITLE
(c * (c * c)) doesn't unify with (c * c * c) for categories.

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#957]
So we set up a coq file in HoTT like this:
```
Require Import Categories.

Local Open Scope category_scope.

Context {c : PreCategory}.
```
Then we run `Check (c*c*c).` and we get
```
c * c * c
     : Core.PreCategory
```
Next we run `Check ((c*c)*c).` and we get
```
c * c * c
     : Core.PreCategory
```
Finally we run `Check (c*(c*c)).` However this time we get
```
c * (c * c)
     : Core.PreCategory
```
This stops `c * c * c` and `c*(c*c)` from unifying.
I presume this stems from assocativity not working for the product of categories.

**Comment by JasonGross** [comment]
> I presume this stems from assocativity not working for the product of categories.

I'm not sure what you mean by this.  There's a way in which this stems from the fact that `(T * (T * T))%type` and `((T * T) * T)%type` don't unify as types, and has nothing to do with categories.

**Comment by mikeshulman** [comment]
I am not aware of any foundation for mathematics in which A x (B x C) and (A x B) x C are definitionally equal.  The best you can get is that with univalence they are typally equal, i.e. related by an identification = element of Id_Type.

**Comment by mikeshulman** [comment]
Mathematicians often pretend that they are the same when writing informally, which officially means transporting along the canonical isomorphism between them.  In particular, to be fully precise, the associator of a monoidal category has to be an isomorphism between two functors C x (C x C) --> C (or the other one, it doesn't matter which), where one of the functors is defined by first applying the isomorphism C x (C x C) \cong (C x C) x C and then multiplying.

**Comment by Alizter** [comment]
To me this seems like the kind of thing a proof assistant should do automatically. Does coq have any functionality that allows things like this to be done?

---

On the other hand I have defined a functor like this (perhaps it can be made more compact?)
```
Definition pa {A B C : PreCategory} : Functor (A * B * C) (A * (B * C)).
Proof.
  simple refine (Build_Functor _ _ _ _ _ _).
  + intros; destruct X, fst; refine (fst, (snd0, snd)).
  + intros; destruct X, fst; refine (fst, (snd0, snd)).
  + auto.
  + auto.
Defined.
```
Now precomposing with my first argument of the natural transformation in associator makes it work.

**Comment by mikeshulman** [comment]
There are many things that it seems to the average mathematician that a proof assistant "should" do automatically that proof assistants can't yet do automatically.  This is one of the reasons I think it will be a fairly long time until all mathematics is formalized.

**Comment by spitters** [comment]
There's a new generation of mathematicians being educated...
