### ISSUE TITLE
Drop HoTT's copy of the Coq prelude.

### ISSUE THREAD

**Issue by ejgallego** [HoTT/HoTT#963]
Coq's https://github.com/coq/coq/pull/186 has landed and while not perfect yet it should mean HoTT should be able to stop vendoring its own modified version of Coq's prelude.

Once this is done, this shall close #477

**Comment by ejgallego** [comment]
@Alizter TTBOMK this is still not solved, tho we are not far from actually doing it, however I think some bugs in Coq will appear when the full conversion is done.

**Comment by Alizter** [comment]
@ejgallego Thank you for letting me know, I have reopened the issue.

**Comment by Alizter** [comment]
@ejgallego Sorry I missed your gitter reply. Is this the issue you were talking about. I would be happy to lend a hand with finishing this.

**Comment by spitters** [comment]
https://github.com/HoTT/HoTT/issues/1424
