### ISSUE TITLE
Exception raised in hoqide

### ISSUE THREAD

**Issue by pavenvivek** [HoTT/HoTT#973]
Inductive vec (A : Type) : nat -> Type :=
  | nil : vec A 0
  | cons : forall n : nat, A -> vec A n -> vec A (S n).
   Arguments nil [A].

Definition hd (A : Type) (n : nat) (v : vec A (S n)) : A :=
  match v in (vec _ (S n)) return A with
  | cons _ h _ => h
  end.

The following error message is returned for definition "hd":
Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/.

This issue is observed only in hoqide. It does not occur in coqide.

OS:
Linux - Ubuntu

Coq version:
8.9+alpha

**Comment by SkySkimmer** [comment]
This is a Coq bug, please report there.

**Comment by SkySkimmer** [comment]
Anomalies are always Coq or plugin bugs, and hott doesn't have a plugin. The issue here is that Coq assumes that part of its standard library is present but hoqide doesn't load it. Coq should be fixed to give a more informative error message (probably something about some equality lemma not being found). Then perhaps the lemma should be added to HoTT.

**Comment by mikeshulman** [comment]
In principle, I don't believe that this sort of definition *should* be allowed in HoTT.  The fact that you don't need to consider the nil case is something that you have to prove in this instance, not a basic property of an inductive type.  (This also came up recently [here](https://math.stackexchange.com/a/3038521/91608).)  In particular, it seems possible to me that allowing this sort of definition for private inductives might be inconsistent with our use of them to fake HITs.

**Comment by SkySkimmer** [comment]
>In principle, I don't believe that this sort of definition should be allowed in HoTT. 

Coq just does inversion under the table.
~~~coq
Inductive vec (A : Type) : nat -> Type :=
| nil : vec A 0
| cons : forall n : nat, A -> vec A n -> vec A (S n).
Arguments nil [A].

Definition hd (A : Type) (n : nat) (v : vec A (S n)) : A :=
match v in (vec _ (S n)) return A with
| cons _ _ h _ => h
end.
Print hd.
(* 
hd = 
fun (A : Type) (n : nat) (v : vec A (S n)) =>
match
  v as v0 in (vec _ iV)
  return
    (match iV as iV0 return (vec A iV0 -> Type) with
     | 0 => fun _ : vec A 0 => IDProp
     | S n0 => fun _ : vec A (S n0) => A
     end v0)
with
| nil => idProp
| cons _ _ h _ => h
end
     : forall (A : Type) (n : nat), vec A (S n) -> A
*)
~~~
To avoid Prop a HoTTer would use `IDProp := unit` or some other inhabited type, that's the only difference.

**Comment by SkySkimmer** [comment]
In fact on Coq master you get `not found in table: core.IDProp.type` so the bug is fixed there.

**Comment by mikeshulman** [comment]
Right, it's that "under the table" business that worries me.  But I suppose there's no chance of this happening by accident for a private inductive since it only occurs when you write an explicit `match`, which is disallowed for private inductives?

Can you tell what HoTT would have to modify in our standard library to enable this behavior?

**Comment by SkySkimmer** [comment]
~~~coq
Definition IDProp := Unit. Definition idProp := tt.
Register IDProp as core.IDProp.type.
Register idProp as core.IDProp.idProp.

Inductive vec (A : Type) : nat -> Type :=
| nil : vec A 0
| cons : forall n : nat, A -> vec A n -> vec A (S n).
Arguments nil [A].

Definition hd (A : Type) (n : nat) (v : vec A (S n)) : A :=
match v in (vec _ (S n)) return A with
| cons _ h _ => h
end.
(* works *)
~~~

**Comment by mikeshulman** [comment]
Thanks.  Which library file should that go in?

**Comment by SkySkimmer** [comment]
Putting it next to the definition for Unit should be fine.

**Comment by mikeshulman** [comment]
Do the objects have to be named literally `IDProp` and `idProp`?  Could we just say `Register Unit as core.IDProp.type`?

**Comment by SkySkimmer** [comment]
They can be named anything, but for now if you use an inductive without wrapping it in a constant you hit https://github.com/coq/coq/issues/9240
