### ISSUE TITLE
Notations for record projections not displaying

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/HoTT#975]
```
Definition foo {A B} (e : A <~> B) (b : B) : A.
Proof.
  pose (a := e^-1 b).
```

displays in the hypotheses

```
a := e.(equiv_isequiv).(equiv_inv) b : A
```

Bleh.  Didn't this used to just display `a := e^-1 b : A` the way I wrote it?  Did something change in Coq?

**Comment by SkySkimmer** [comment]
There was a bug like that but it should have been reverted without getting into any release, what Coq version are you using?
See https://github.com/coq/coq/pull/8456 https://github.com/coq/coq/issues/6764

**Comment by JasonGross** [comment]
I'm not sure.  @silene was planning to release it in early December, but I pushed back against it being released without fixing https://github.com/coq/coq/issues/9244 (any "cannot infer this term" error message in a `Fixpoint` becomes an anomaly "grounding a non evar-free term"), and it seemed like there were a couple of other issues that might be holding up release.  (There's a thread on coqdev@ which has more details.)

**Comment by Alizter** [comment]
I tested this again and it doesn't seem to be the case anymore. I am therefore closing this issue, however if it still persists by all means reopen.
