### ISSUE TITLE
Adding and removing hints in the core database implicitly is deprecated

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#991]
>Warning: Adding and removing hints in the core database implicitly is
deprecated. Please specify a hint database.

I keep getting this warning when compiling the library after the push to 8.9. What should be done about these? They appear in Overture.v a lot.

**Comment by JasonGross** [comment]
We can just add `: core` to all the `Hint ...` statements, probably.

**Comment by Alizter** [comment]
If you do end up doing this it breaks a bunch of files. See #992.
