### ISSUE TITLE
Option Bracketing Last Introduction Pattern is deprecated

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#993]
```
File "./theories/Basics/Overture.v", line 8, characters 0-50:
Warning: Option Bracketing Last Introduction Pattern is deprecated
[deprecated-option,deprecated]
```

as found out in #992 this is essential for Sum.v and a few other files to compile. What is the reason for this to still be used and what should we do about it?

**Comment by JasonGross** [comment]
It allows us to turn a goal `forall x : A * B, ...` into `forall (x : A) (y : B), ...` using `intros []`.  This pattern can probably be replaced with `let x := fresh in intro x; case x; clear x`, which is a bit more annoying, but still workable.

**Comment by mikeshulman** [comment]
Or maybe `apply prod_ind`?

**Comment by mikeshulman** [comment]
I don't understand.  What would you expect induction to work for other than foralls?

**Comment by Alizter** [comment]
Function types, because you cannot give the variable a name it doesn't work.

**Comment by mikeshulman** [comment]
Ugh, why would you do that anyway?  It seems to me like a terrible idea to refer explicitly in a tactic script to the names of *bound* variables in the goal; in particular, it breaks the alpha-abstraction barrier.  I'm kind of shocked that Coq allows it, although now that you mention it I do maybe recall hearing about it before.

**Comment by Alizter** [comment]
Why not just have both be `induction`. It is pretty unambiguous, especially if used like intro.

**Comment by Alizter** [comment]
I would agree that `apply blah_ind` is the most correct and readable way to do it really. This still leaves us with what to do about the use of `intros []`. I say we find the culprits and change them to the more correct `apply blah_ind`.

**Comment by Alizter** [comment]
@mikeshulman you beat me to it. I was changing the proofs to use more `apply foo_ind` stuff. I thinking avoiding square brackets all together is more readable and maintainable. I'll make a pull request in a bit.

**Comment by Alizter** [comment]
I'll close this issue now since we have two pull-requests dealing with it.

**Comment by mikeshulman** [comment]
General practice is to close an issue *after* a pull request that fixes it has been merged.
