### ISSUE TITLE
Math classes and group theory

### ISSUE THREAD

**Issue by Alizter** [HoTT/HoTT#996]
Group theory as been alluded to in various past issues. The mathclasses library has groups but with that it brings its own problems:

 1. I has to be maintianed from source, making substantial name changes is therefore difficult. Thus is cannot adhere to the rest of the HoTT library.
 2. It is packaged together with lots of unrelated stuff.

I don't mind having mathclasses for things like rings and modules since it would be very tedious to write these out however I feel differently about this for groups.

In HoTT, we can model group theory arguments using paths. This would be awkward to add onto mathclasses. We can also experiment with ooGroups etc.

We need some standalone lemmas about groups since these will come in very useful for synthetic homotopy theory.

And on top of this a good theory of abelian groups may be worth developing, especially if we want to eventually catch up with the Spectral library.

I would be willing to spend some time developing it. But there will be a few initial design choices that we would need to agree on. First of which would be are groups more useful as classes or as connected 1-types.

**Comment by Alizter** [comment]
What I meant by model group theory arguments using paths is that we have a load of lemmas in PathGroupoids.v which can be used for manipulating paths around.

The class for groups is in `abstract_algebra.v`. If I want to talk about groups I will have to import all sorts of other stuff. Surely it would be better to have an algebra library similar to how Jason structured his categories library?

Naming is slightly superficial, but I think it is more obvious to have classes about groups in Group.v rather that abstract_algebra.v. I find the layout of math classes a bit dense, there is too much going on in one file.

Another problem I have with mathclasses is if we think of some lemmas or a better way to do something it is discouraged to change the code.

I have made this thread so I can at least log some of my discomforts with it. I have incoherently babbled about them in the past, and I am not sure this current thread is doing a better job but I guess it is better then nothing. I'll try to use mathclasses at least then.

**Comment by SkySkimmer** [comment]
>Another problem I have with mathclasses is if we think of some lemmas or a better way to do something it is discouraged to change the code.

I think you should feel free to change code in Classes/ or move it somewhere else if you feel that makes it integrate better with the rest of HoTT. It's already significantly changed from mathclasses (eg using paths instead of setoid relations everywhere).

**Comment by spitters** [comment]
If you want to change math-classes, please read the corresponding papers
and come up with a better solution for how to develop real numbers in HoTT.
Also, @andreaslyn has developed quite a bit of universal algebra on top of
HoTT-classes.
https://github.com/andreaslyn/hott-classes

It would be a pity to break all this.
